filodb/FiloDB

cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, spark/src/test/scala/filodb.spark/SaveAsFiloTest.scala
attempt to fix Travis test since there are error in test due to timeout
=> added implicit PatienceConfig

.gitignore, build.sbt, filo-cli
updated Scala version to 2.10.5 since that was being picked by SBT and minor changes in the build script
=> added script for filo-cli

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala, core/src/main/scala/filodb.core/columnstore/Segment.scala
Fix some scaladoc issues which prevent `sbt publish-local`. I could turn of scaladoc gen locally but IMO it's better to fix them.
However I didn't find a proper way to reference a project file, ideas are welcomed!
=> fix scaladoc issues

project/build.properties
just a quick update to the current SBT version
=> updated sbt to 0.3.11

spark/src/main/scala/filodb.spark/package.scala
Added fix for unique actor issue occurs during ingestion. Refer to issue 103.
=> Fix for unique actor issue - #103

build.sbt
Not sure if the explicit 17.0 in CassDep is useful. The other part really helped.
=> Guava shading

filo-cli
Hi guys, 
I have found interesting to create a bash function to check java and one more to check sbt tool. As it is done to check JDK version greater that 1.8.
=> creating a function for checking java and another to check sbt

build.sbt, coordinator/src/main/scala/filodb.coordinator/CoordinatorSetup.scala, core/src/main/scala/filodb.core/Iterators.scala
Updating to latest version, since the changes from 2.1.1 are significant.
=> Update "io.monix" % "monix" to 2.3.0

coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala, run_benchmarks.sh
=> feat(jmh): JMH Benchmark for Part Key Lucene Index

cli/src/main/scala/filodb.cli/CliMain.scala, coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
* SEGV was seen when invoking promQL time series API because of
prettyPrint regression
* LabelValues API should not accept promQL matcher. That can be
supported later.
* Earlier code was not skipping metadata for evicted partitions properly
* Default lookback time was not sufficient
=> bug(query): Fix for issues in metadata query capability

project/build.properties
- [-] Tests for the changes have been added (for bug fixes / features) ?
- [-] Docs have been added / updated (for bug fixes / features) ?
(Skipped)
I just upgraded the patch version of sbt. As far as I know, I've never seen any problems with the version.
No breaking change.
This project currently seems built on JDK8. When you upgrade JDK to 9+, 0.13.17 is the only version which is compatible with JDK 9+ in 0.13 series.
=> misc: Bump sbt version to the latest in 0.13 series

conf/timeseries-128shards-source.conf, conf/timeseries-dev-source.conf
We have two datasets - prometheus and timeseries. This consolidates the two.
=> bug(conf): Change dev source dataset from timeseries to prometheus

README.md
- [~] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [n/a] Tests for the changes have been added (for bug fixes / features) ?
- [y] Docs have been added / updated (for bug fixes / features) ?
broken links ;)
fewer broken links ;)
=> Fix docs/ -> doc/ links in README.md

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/test/scala/filodb/query/exec/BufferableCounterCorrectionIteratorSpec.scala
Fixed bug in counter correction, and added unit test for it.
=> bug(query): Fixed bug in counter correction

doc/compression.md
Documentation and proposal of an encoding scheme for compression of both floating point and other types of data such as histograms.
=> doc(all): Add compression and predictive nibblepacking doc/proposal

README.md, core/src/main/resources/filodb-defaults.conf
=> feat(config): Increase query-timeout in filodb

README.md, core/src/main/resources/filodb-defaults.conf, filodb-dev-start.sh, standalone/src/main/java/filodb/standalone/SimpleProfiler.java, standalone/src/main/scala/filodb.standalone/FiloServer.scala
This PR defines a simple profiler, which runs as a background task and writes results periodically to a file. This makes it easier to run perf tests without having to set up remote connections from a profiling client.
=> feat(standalone): Include a simple profiler.

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala, core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/RangeVector.scala
Additional metrics are added to capture the following
- Time Taken to RawChunks from datastore onto memory
- Number of TimeSeriesPartitions loaded from datastore
- Number of TimeSeriesPartitions loaded from memory
- Lucene Index lookup time
=> misc: additional metrics to capture time taken for ODP, lucene index lookup

core/src/main/scala/filodb.core/downsample/ShardDownsampler.scala
Fix for chunked encoding also for downsampling
=> fix(core): Limit chunked windowing range for downsampling

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
Just a few checks to prevent null ChunkSetInfos from leading to SEGVs
=> misc(core): Add debugging/checks to prevent NULL ChunkSetInfo during queries

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
Really simple fix to a bug introduced with exception catch logging
=> fix(query): Fix bug in exception logging code

query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala, query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala
fixes for Resets function
- Check for sliding window size for `removedFromWindow` call back
- make `ResetsFunction` a class for initializing `resets` counter to zero, for every query
=> bug(query): fix for resets function

query/src/main/scala/filodb/query/exec/ExecPlan.scala
**Current behavior :** Kamon trace context is not currently propagated properly during nested Akka calls due to an existing [issue](https://github.com/kamon-io/kamon-akka-http/issues/30).
**New behavior :** By wrapping the execPlan dispatcher with currentSpan, the span context is propagated properly.
=> feat(query): Fix broken tracing

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
=> feat(query): Add additional info in tracing

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> feat(memory): Add basic deadlock detection when shared lock owner tries to upgrade to exclusive.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
currentIndexTimeBucket is currently an int that is mutated in one thread, but can be read from another thread. Better to make it an AtomicInteger so the read happens safely.
=> bug(core): currentIndexTimeBucket should be atomically read and modified

doc/compression.md, memory/src/main/scala/filodb.memory/format/NibblePack.scala, memory/src/test/scala/filodb.memory/format/NibblePackTest.scala, memory/src/test/scala/filodb.memory/format/vectors/LongVectorTest.scala
Just the NibblePack.scala by itself for easy reviewing.
=> feat(memory): Implementation of NibblePacking compression/storage scheme

memory/src/main/scala/filodb.memory/format/NibblePack.scala
Minor fix for doc target to succeed again. :-p
=> fix(memory): fix minor Scaladoc formatting issue

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
Separate threads might modify a map concurrently, leading to initialization issues.
Finish initialization using a new message, ensuring only one thread is modifying the map and acting upon the result.
=> bug(coordinator): Finish dataset initialization using a message to avoid potential thread-safety issues.

README.md, project/FiloBuild.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/exec/rangefn/InstantFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala
Implements a `histogram_bucket` instant function to extract one histogram bucket from a HistogramColumn.
=> feat(query): histogram_bucket function

core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/downsample/ChunkDownsampler.scala, core/src/main/scala/filodb.core/downsample/ShardDownsampler.scala, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
Added an hSum downsampler for histogram columns, that computes sum_over_time for Histogram columns that are gauges (and not increasing counters).  Plus tests.
=> feat(core): hSum sum_over_time Histogram downsampler

core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
The wrong method was being called to detect if a shard already was set up.
=> bug(core): Fix duplicate shard setup detection.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, memory/src/main/scala/filodb.memory/BlockManager.scala
Adds more logging and one counter for the rare occurrence when the BlockManager cannot find blocks to reclaim and is out of new blocks to return.
Also, even when data is dropped, mark all blocks as reclaimable and flush/commit checkpoints, as we prefer availability.
=> feat(memory, core): Add logs/stats for block manager; reclaim blocks even if data dropped

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
avg() queries fail with an exception.
avg() queries should now work.  Exception is gone.
=> fix(query): Fix requirement preventing avg() aggregates from working

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/zipkin/Zipkin.scala
=> misc(core): Add zipkin configs to filodb-defaults

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
Snapshots of the shard mapping state are published only when an event occurs.
In case messages are dropped, publish the snapshot periodically to all nodes.
=> feat(coordinator): Publish shard mapping snapshots once a minute, to cope with dropped messages.

core/src/main/scala/filodb.core/memstore/WriteBufferPool.scala
WriteBufferPool uses Scala's `mutable.Queue` which isn't thread safe.  This may lead to problems.
Switch to using an MpscUnboundedArrayQueue which is thread safe.
=> fix(core): Switch to thread-safe Queue in WriteBufferPool

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
There is a limit to number of terms in a query, so we need batching to prevent exception when startTime for too many partIds needs to be fetched.
=> bug(core): startTimes Lucene query needs batching

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
=> test(core): Unit test for Lucene startTimes api for multiple partIds

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala, doc/http_api.md, http/src/main/scala/filodb/http/PrometheusApiRoute.scala, http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala, prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala
Adds ability to get ExecPlan from FiloDB HTTP
=> feat(http, coordinator): explainPlan support in FiloDB HTTP

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala, coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
Too much log spew.
Reduce the spew.
=> misc(coordinator): Remove redundant shard event logging, and lower some to debug level.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
On one occasion a partition ID collision was observed. This shouldn't be possible, but a lot of other fixes have been made since the observation. It might not be an issue any more.
In the rate event that a collision is detected, keep incrementing the ID.
=> bug(core): Fix very rare partition ID collision.

prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala, prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
Support multiline queries like:
sum(sum_over_time(mesos_master_disk{_ns="mesos_master",type="used"}[5m])) by (cluster)
/
sum(sum_over_time(mesos_master_disk{_ns="mesos_master",type="total"}[5m])) by (cluster)
=> feat(prometheus): Add multiline query support

core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
=> bug(core): Fix Kamon tag.

project/FiloBuild.scala, project/build.properties
**Changes :** 
- Minor version upgrades for akka libraries that seem to have JDK11 related fixes. 
- Upgraded sbt and kamonVersion as well.
=> JDK11: upgrade sbt, akka

project/FiloBuild.scala
- updated cassDriver, kamon and snappy versions
=> upgrade libs

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, core/src/main/scala/filodb.core/memstore/MemStore.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala, http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala
* Recovery reporting was not happening exactly when offset was reached. Fixed that.
* Added more consistent logging format for shards and partIds
=> bug(core): Recovery reporting was delayed for final 100% mark

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
Just adding a bit more logging for debugging, and also removing logging that's accidentally too verbose
=> feat(core): Fix and add more TSPartition detailed tracing/logging

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Just a bit more logging for shard and group number
=>  feat(core): More debug logging for traced TSPartitions

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> bug(core): More - Set ingestion flag explicitly and not assume defaults

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> bug(core): Need to check if bloom filter has been disposed.

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Placed the put into the ConcurrentHashMap correctly after removal of previous entry.
=> debug(memory): More debugging of ChunkMap lock release

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> misc(memory): Add shared lock debugging checks for ingestion thread.

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> misc(memory): More debug.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Another case of missed code path where index is not updated
=> bug(core): Update re-ingesting partition in index

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
More debugging around TSPartition switchBuffers and new chunk creation
=> debug(core): More debug/trace loggging around switchBuffers, initNewChunk

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
bug(core): Don't call isEmpty on chunk map iterator from the ingestion thread. It acquires the shared lock when the flush task thread was supposed to.
=> bug(core): Don't call isEmpty on chunk map iterator from the ingestion thread.

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
=> fix(core): ChunkSetInfo.debugString checks for null

coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
Reinstate shared assignment log message
=> bug(coord): Reinstate shared assignment log message

core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Removing some code added in PR #372 and #373.
=> misc(memory): Remove some temporary debug code.

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/rangefn/MiscellaneousFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/LableJoinSpec.scala
Support for prometheus label_join function
=> feat(query): Label Join function support

core/src/test/scala/filodb.core/TestData.scala
TimeSeriesMemStoreSpec sometimes fails in Travis.
Increase test memory.
=> misc(core): Increase shard-mem-size for tests.

project/FiloBuild.scala, project/build.properties
**Changes :** 
- Upgraded sbt version and few dependencies to use the jdk11 compatible versions.
- travis runs using jdk11 already. 
- Build should pass. Changes include minor version upgrades of dependencies.
=> misc(build): use jdk11 compatible sbt and libs

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Just a new metric for histogram column encoding itself
=> feat(core): Add memstore-hist-encoded-bytes metric

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Occasional SEGV observed shortly after service start.
Add explicit null checks which should prevent the SEGVs and provide better error reporting.
=> misc(memory): Add explicit null checks to ChunkMap.

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
* Remove races and concurrent access on non-concurrent IngestionActor
* Address issue of partKey being accessed during shutdown
=> bug(core): Fixes to address segv during rolling deploy

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
We attempt to re-intialize datasets in NodeCoordinatorActor everytime a new NodeClusterActor (leader) is registered. This should not be done. It causes exceptions from NodeCoordinatorActor such as:
```
[2019-06-18 05:15:10,588] ERROR filo-standalone-akka.actor.default-dispatcher-44 a.a.OneForOneStrategy [akka://filo-standalone/user/node/coordinator] - actor name [ingestion-prometheus] is not unique!
akka.actor.InvalidActorNameException: actor name [ingestion-prometheus] is not unique!
at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
at …
```
=> bug(coord): Should not re-initialize dataset

core/src/main/resources/filodb-defaults.conf, core/src/test/resources/application_test.conf, query/src/main/scala/filodb/query/QueryConfig.scala, query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala
Re-enables faster, chunk-optimized rate/increase/delta.  To be merged when data has been encoded using `detectDrops=true` after desired retention period.
=> feat(query): re-enable chunked/optimized rate/increase/delta

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Sample tracing can be enabled only for string partition key
Sample tracing can be enabled additionally for all types key types that can be matched with a string
=> feat(core): Ability to use non-string fields to determine which partition to trace

core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf, doc/compression.md, jmh/src/main/scala/filodb.jmh/HistogramIngestBenchmark.scala, memory/src/main/scala/filodb.memory/format/NibblePack.scala, memory/src/main/scala/filodb.memory/format/Ptr.scala, memory/src/main/scala/filodb.memory/format/Section.scala, memory/src/main/scala/filodb.memory/format/UnsafeUtils.scala, memory/src/main/scala/filodb.memory/format/WireFormat.scala, memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala, memory/src/main/scala/filodb.memory/format/vectors/HistogramCompressor.scala, memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala, memory/src/test/scala/filodb.memory/format/NibblePackTest.scala, memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala, memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala, project/FiloBuild.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/TransientRow.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala
=> Merge develop -> integration-0.8.6

doc/downsampling.md, http/src/test/scala/filodb/prom/downsample/GaugeDownsampleValidator.scala
Tool issues same query to downsampled and raw datasets and makes sure they are the same for all gauge type downsamplers.
Invoke with following system properties:
```
-Dquery-endpoint=https://myFiloDbEndpoint.com -Draw-data-promql=jvm_threads{_ns=\"myApplication\",measure=\"daemon\",__col__=\"value\"}[@@@@s] -Dflush-interval=12h -Dquery-range=6h
```
=> feat(downsample): A tool in test code to validate downsampled data

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Temporarily disable another contentious assertion of thread name
=> bug(core): Temporarily disable a thread assertion Take2

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
=> misc(coordinator) Log when ingestion cancel task is run.

memory/src/main/scala/filodb.memory/BlockManager.scala
bug[memory]: Guard BlockManager data structures with the lock. This should protect blocks from being reclaimed before they're fully switched to the "in use" state with a timestamp.
Observed MatchError exceptions when ODP'ng data older than the retention period. Possible cause is immediate reclamation of the blocks before they're moved to the "in use" state.
=> bug[memory]: Guard BlockManager data structures with the lock.

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala, coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala, project/FiloBuild.scala, query/src/main/scala/filodb/query/PromQlInvocationParams.scala, query/src/main/scala/filodb/query/ResultTypes.scala, query/src/main/scala/filodb/query/exec/PromQlExec.scala, query/src/test/scala/filodb/query/ResultTypesSpec.scala, query/src/test/scala/filodb/query/exec/PromQlExecSpec.scala
=> Integration from develop merge 0.8.7 take2

core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
filo-cli `labelValues` command results in a `StackOverflow`
Fixed, results printed
=>  fix(core): Fix filo-cli labelValues bug with MapColumn result pretty printing

core/src/test/scala/filodb.core/TestData.scala, memory/src/main/scala/filodb.memory/BlockDetective.scala, memory/src/main/scala/filodb.memory/BlockManager.scala
=> fix(memory: Fix BlockDetective ConcurrentModificationException

cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala, coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala, coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala, core/src/main/scala/filodb.core/memstore/MemStore.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/memstore/DemandPagedChunkStoreSpec.scala, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala, jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala, jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala, jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala, jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala, jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala, jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala, query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala, version.sbt
A hot fix containing a single commit:
[release-0.8.6.2 d03a9391] bug(core): Release IndexSearchers after each use (#453)
The commit fixes a Lucene disk space cleanup issue which was causing bloated local disk usage.
Version is updated to 0.8.6.2 for hot fix.
=> Release 0.8.6.2 HOTFIX

version.sbt
Version bump for build reasons
=> misc: Bump version to 0.8.6.3

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, core/src/main/scala/filodb.core/memstore/MemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala, jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
This is a simple isolated refactor in preparation for other changes. No need to merge them into a single PR.
=> misc(core): Remove the disk TTL parameter and access config directly.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Fix an observed NullPointerException.
=> fix(core): Fix NPE when partition has already been reclaimed.

project/FiloBuild.scala, project/plugins.sbt, spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala
* Logging downsample config on start for debugging
* Removing dependency of sparkJobs from standalone
=> feat(downsampler): Log downsample config during run

coordinator/src/main/scala/filodb.coordinator/StoreFactory.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/Instance.scala, spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala, spark-jobs/src/main/scala/filodb.downsampler/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala, spark-jobs/src/main/scala/filodb.downsampler/Utils.scala
=> feat(downsampler): Allow custom cassandra session provider for downsampling

core/src/main/scala/filodb.core/store/package.scala
Use function in Java 8 so we don't get NoSuchMethodError when Java8 is used.
=> bug(core): Use floorMod function that is in java8

coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala
Queries were not getting through at all.
Turns out the problem is that the `Schema` class was not using the custom serializer that we defined.  Kryo's default serialization logic for it doesn't work (besides being very expensive).
SchemaSerializer initialization was silently failing due to `FilodbSettings.global().get` failing, as at initialization time it was not defined yet.
Instead of getting the schemas at initialization time, now we just obtain the schemas at each read(), and by then it should definitely be initialized.
Verified locally that the fix works.
NOTE: Schemas are …
=> fix(coordinator): Fix Schema serializer initialization

CONTRIBUTING.md, README.md
README lacks a few small details for Kafka end-to-end testing.
Included details for running FiloDB successfully.
=> misc(core): Add more details for README

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
=> bug(core): Use debugString to log chunk info

core/src/main/scala/filodb.core/metadata/Schemas.scala, gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala, gateway/src/test/scala/filodb/gateway/conversion/InputRecordBuilderSpec.scala
A couple methods to write BinaryRecords for standard gauge/counter/histogram schemas.
=> feat(gateway): InputRecord static methods to write standard gauge/counter/histogram schema BRs

gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
=> misc(gateway): Map prom remote_write records to untyped

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
Holt winters (double exponential smoothing) support
=> feat(query): Holt Winters support

memory/src/main/scala/filodb.memory/MemFactory.scala
Scaladoc fails with: Could not find any member to link for "IllegalStateException"
Disabled the throws tag and ran "doc" command to verify that scaladoc works now.
=> bug(memory): Workaround scaladoc bug

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/TransientRow.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
Prometheus stdvar function support
=> feat(query): stdvar support

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
Returns non NaN value when the length of the window is 1. 
Returns NaN when length is < 2.
=> bug(query): Handle holt_winter windows with length 1

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala, spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala
Fixing/logging downsample config after config change a few days ago in the "Faster Cassandra reads" PR.
=> bug(sparkJobs): Fixing downsampling issue due to config change

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, core/src/main/scala/filodb.core/store/package.scala, spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala
More logging to debug downsampler failure
=> debug(sparkJobs): Add more logging to debug downsampler

core/src/main/scala/filodb.core/memstore/MemStore.scala
=> scaladoc(core): Scaladoc error fix

cli/src/main/scala/filodb.cli/CliMain.scala
fill-cli queries do not output schema of current query result
Schema of query result is dumped out for easier debugging
=> debug(cli): Dump output schema of result in CLI

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
Not considering the case when mean = NaN in reduceAggregator
Add the check condition when mean = NaN in reduceAggregator
=> bug(query): Handle stdvar NaN case in reduceAggregator

query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/rangefn/InstantFunction.scala
Scala docs throws error discarding unmoored doc comment
Remove the scala doc comments
=> docs(query): discard unmoored doc comment

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
=> debug(query): Additional logging to debug ArrayIndexOOB

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
=> feat(query): predict_linear support

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/TransientRow.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
Prometheus stddev function support
=> feat(query): stddev support

core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala
This is another bug/case which can make startRow > endRow
=> bug(sparkJobs): Fix another case when startRow > endRow

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
=> debug(core): Log partition key hash when adding document

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
Adds a very detailed `debugString` method to `RecordSchema` with offsets and details on every map key value. 
Adds debugging to addPartition before it creates a partKey.
=> debug(core): Add very detailed debugString() BR method; add debugging to addPartition

README.md, prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/exec/InternalRangeFunction.scala, query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
=> feat(query): z_score support added

README.md, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala, core/src/test/scala/filodb.core/metadata/SchemasSpec.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala, query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala, version.sbt
Changes:
config: Change metric partition column to _metric_ to avoid clashes w… 
bug(core): Fix/change predefined keys hashing algorithm for keys < 4 …
=> Integration merge 0.9.2 dev

version.sbt
update version number for maintenance branch
=> update version number in 0.8-maintenance branch

cassandra/src/main/scala/filodb.cassandra/CassandraTSStoreFactory.scala, coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, core/src/main/scala/filodb.core/store/MetaStore.scala
DownsampledTSStoreFactory needs a metastore.
=> bug(core): Fix metastore in DownsampledTSStoreFactory

standalone/src/main/scala/filodb.standalone/FiloServer.scala
=> debug(standalone): Debug akka boostrapper config

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala, spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
An NPE is thrown if a query happens to hit a partition/time series with a schema ID that is not known to FiloDB.  In theory this should not be possible, as both ingestion and the index/partkey recovery process skips partitions with unknown schema IDs. 
Unknown schemas will result in a new, specific `UnknownSchemaQueryErr`.  Upon seeing this error, operators need to truncate the data tables as this should only occur when an existing schema is changed, which is extremely rare.
=> bug(query): Throw more precise error if unknown schema ID found

build.sbt, project/Dependencies.scala, project/FiloBuild.scala, project/FiloSettings.scala, project/build.properties
Build functions the same, but subprojects inheriting from this repo can more easily override build.sbt and extend it.
=> misc(tooling): Move projects back to FiloBuild.scala

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobSettings.scala
- try block for catching and logging exceptions in a task
- fix a bug where wrong timeout config being used for c* writes
=> misc(downsampler): index migration job - log task exceptions

coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
- additional loggers are added in ShardManager for debugging
=> debug(core): add loggers for shard management events

memory/src/main/scala/filodb.memory/format/NibblePack.scala, memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
=> debug(memory): Add logging around histogram vector repacking exceptions

core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/store/ChunkSetInfoReader.scala, core/src/main/scala/filodb.core/store/IngestionConfig.scala, core/src/main/scala/filodb.core/store/ReadablePartition.scala, spark-jobs/src/main/scala/filodb/downsampler/BatchDownsampler.scala
Added metrics to FiloDB downsample cluster
Removed logging of chunk hex since it can be looked up in cassandra using chunkId and partKeyHex
=> feat(core): Metrics for FiloDB downsample cluster

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
Purge old entries from downsample cluster index
=> feat(downsample): Purge expired entries from downsample cluster index

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala, coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala, coordinator/src/main/scala/filodb.coordinator/ShardManager.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
Downsample shard status doesnt switch to active state since there inst any ingestion happening.
Simply changing state to active upon initialization of shard after index recovery
=> bug(downsample): Downsample shard status needs to be active

spark-jobs/src/main/scala/filodb/downsampler/BatchDownsampler.scala, spark-jobs/src/main/scala/filodb/downsampler/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
More metrics for spark downsampler job
=> feat(downsampler): More metrics

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
add debug statement for logging TimeSeries details for ingestion exception
=> misc(debug): debug statement for debugging ingestion error

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
use ingestionschema debug statement for debugging ingestion error
=> misc(debug): use ingestionschema debug statement for debugging ingestion error

memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
=> misc(debug): remove DirectBuffer logging

project/Dependencies.scala
=> feat(sparkJobs): Upgrade spark to 2.4.4

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
=> bug(query): diskTtlSeconds.toLong before conversion to millis

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/DistConcatExec.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala, query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/main/scala/filodb/query/exec/StitchRvsExec.scala, query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, spark-jobs/src/main/scala/filodb/downsampler/BatchDownsampler.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
1. We were returning empty results instead of throwing error when leaf plan errors out.
2. Downsampler Main spec ingested data in multiple downsample periods - changed data.
3. Misc code formatting changes
4. Removed some extraneous logging during queries
=> bug(query): Query module code formatting with misc fixes

standalone/src/multi-jvm/scala/filodb/standalone/StandaloneMultiJvmSpec.scala
A test breaks randomly. Cause is due to an earlier commit #eeec3279aadbf32c618d5cfd912b7008827d7524
=> fix(standalone): Fix flakey test.

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
=> fix(misc): fix compilation errors

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
fix scaladoc issue - remove `@throws`
=> fix(misc): fix scaladoc

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala, spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala, spark-jobs/src/test/scala/filodb/repair/ChunkCopierSpec.scala
=> feat(spark-jobs): Define a basic Spark job which copies chunks between Cassandra stores.

coordinator/src/main/scala/filodb.coordinator/client/FiloKryoSerializers.scala, coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala, coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
Config inside PromQlQueryParams in ExecPlan throws NullPointerException when serializing
Add KryoSerializer for PromQlQueryParams
=> fix(query) : add KryoSerializerfor PromQlQueryParams

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
=> bug(sparkJobs): Kamon init should initialize first on spark tasks

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
=> bug(sparkJobs): Make chunk/index downsample jobs consistent to debug kamon

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
Remove `Kamon` instrumentation from downsample index job.
=> misc(spark-jobs): remove kamon instrumentation from downsample index job

core/src/main/scala/filodb.core/query/RangeVector.scala, query/src/test/scala/filodb/query/exec/rangefn/ScalarFunctionSpec.scala
dayOfWeek function returns 7 for Sunday
Call getValue on dayOfWeek enum. Return 0 if it is 7
=> bug(query): dayOfWeek  function returns 7 for Sunday

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/main/scala/filodb.core/query/ResultTypes.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
Reverts filodb/FiloDB#664
- causing regression issue, needs more analysis on the original issue
=> Revert "fix(query): fix for schema mismatch error in binaryOp with fixed scalar value"

spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
- [ x The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
The stack trace can get lost if the job fails.
Capture the trace in the message, and also keep the original exception.
=> fix(spark-jobs): Wrap all exceptions and capture the stack trace in the message.

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
=> debug(core): Include multiple schema names in query error

core/src/main/resources/filodb-defaults.conf
=> fix(core): Fix ignoreShardKeyColumnSuffixes for histogram and summaries

core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
=> bug(core): Index refresh was using wrong PK val

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
* Unit test that verifies completeness of PartKey migration during downsampling
* Some debug logs to root cause PK downsampling bug
=> debug(sparkJobs): More detailed testing/debug for completeness of PK downsample

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
Acknowledgements to Brian for helping me recall that hash can be negative too.
=> bug(cassandra): Fix bug in calculation of split during writes to pk table

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
=> bug(sparkJobs): Try to reinstate Kamon metrics in index downsampler

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
=> feat(sparkJobs): Index migration metric for skipped partKeys

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
* Support blacklisting for index downsampler
* More logging of information
* Metrics to log completion of spark jobs
* Rerun of index downsampler will run job for subsequent hours until last period
=> feat(sparkJobs): Index Downsampler blacklisting

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala, cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala, spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
Make sure Kamon is initialized early in the JVM, and update stats.
=> fix(spark-jobs): Integrate Kamon stats.

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/exec/InternalRangeFunction.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala
Cherry-pick changes to support `Last` function from 0.8-maintenance branch
=> Cherry-pick changes to support `Last` function from 0.8-maintenance branch 

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> debug(core): More logging for ODP debug

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/test/scala/filodb.core/TestData.scala
Grouping by `__name__` is not supported
Replace PromMetricLabel with metric column of dataset
=> feat(query): support __name__ in group by, without, on and ignoring

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
=> log(sparkJobs): Log entries with explicit property to rerun job

cli/src/main/scala/filodb.cli/CliMain.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala, core/src/main/scala/filodb.core/memstore/MemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala, prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala, prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
When string-pairing BR columns, different base/offset needs to be applied.
=> bug(core): RecordSchema.toStringPairs had bug with BR columns

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
=> fix(core): Revert hole expansion fix for now.

coordinator/src/main/scala/filodb.coordinator/client/FiloKryoSerializers.scala, coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, core/src/test/scala/filodb.core/query/RangeVectorSpec.scala, prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
Add schema name to RangeVectorKey so that the same can be printed in results if needed.
=> feat(query): add schema name to RangeVectorKey

core/src/main/scala/filodb.core/query/ResultTypes.scala
=> misc(core): add utility method to verify histogram column

query/src/main/scala/filodb/query/util/LogicalPlanUtil.scala
getLabelValueFromLogicalPlan throws Invalid Logical Plan exception for ScalarBinaryOperation
Return Nil when Logical plan is ScalarBinaryOperation
=> misc(query):  handle ScalarBinaryOperation in LogicalPlanUtils

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
=> fix(core): Bring back hole expansion fix.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
Preparing to guard reclaims with shard level locks. This PR introduces shared/read locks. Subsequent PRs will introduce write locks.
=> bug(core): Reclaim shared lock for pinning blocks during queries

memory/src/main/scala/filodb.memory/BlockManager.scala, memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala
Blocks can be reclaimed in the middle of an ODP operation.
Adding the ability to reclaim early is one step in fixing the ODP problem. Later a background task will be added to ensure free space.
=> feat(memory): Add method to ensure free space.

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/store/IngestionConfig.scala, memory/src/main/scala/filodb.memory/BlockManager.scala
Launch a background task per shard which helps ensure that enough free blocks are available. This reduces the likelihood that ODP ends up reclaiming what it just fetched.
=> feat(core): Add periodic headroom task.

core/src/main/resources/filodb-defaults.conf, spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
=> feat(sparkJobs): Ability to trace downsampling of TS partitions

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
=> debug(sparkJobs): Fixing debug string

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
=> debug(core) Tracing Partition should log at info level since explicitly enabled

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
Testing was done by verifying logs in local run
=> feat(sparkJobs): If tracing downsampler log chunks read from cassandra

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
=> debug(core): Debug Full ODP code path

jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
`PartKeyLuceneBenchmark` throws an exception after launch:
```
[info] java.lang.ArrayIndexOutOfBoundsException: Index 114 out of bounds for length 114
[info] 	at org.apache.lucene.util.StringHelper.murmurhash3_x86_32(StringHelper.java:159)
[info] 	at org.apache.lucene.util.BytesRefHash.doHash(BytesRefHash.java:439)
[info] 	at org.apache.lucene.util.BytesRefHash.findHash(BytesRefHash.java:325)
[info] 	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:255)
[info] 	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151)
[info] 	at …
```
=> fix(jmh): Fix PartKeyIndexBenchmark

memory/src/main/scala/filodb.memory/BlockManager.scala
=> feat(memory): Updates for stall time.

jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
Allows us to simulate the case where data is spread over many shards, and explore query issues with that setup
Changes `QueryInMemoryBenchmark` to simulate 64 shards with each metric still using 100 time series.  Possibility of empty shards is quite high.  Queries must distribute to all shards.
=> feat(jmh): Change QueryInMemoryBenchmark to simulate high-spread queries

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
=> misc(query): Do not query downsample cluster for metadata queries

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
The state resync task fixes ingestion state in case messages were dropped during deployments, etc. Once stopped, the ack is sent once, but it might be dropped too.
Send the ack message every time the state is resync'd, even if already stopped.
=> feat(coordinator): Ensure that stop message is sent when state is resync'd

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
=> debug(core): More ODP logging to debug full ODP

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, memory/src/main/java/filodb/memory/Latch.java, memory/src/main/scala/filodb.memory/BlockManager.scala
Apparent bug in JDK11 implementation of StampedLock.
Replace StampedLock with a different class for now.
=> fix(memory,core) Add a Latch class and use it instead of StampedLock.

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/test/scala/filodb/query/LogicalPlanSpec.scala
=> misc(query): update logicalPlan utility methods

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Earlier commit seems to be causing test failures. Partially rolling it back.
=> fix(memory): Comment out halt for now.

cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala, core/src/main/scala/filodb.core/downsample/OffHeapMemory.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
Callback was not being invoked if partition creation was needed for concurrent queries.
Also added much needed unit test for ODP.
=> bug(core): ODP Bug fix for Concurrent queries + ODP Unit Test 

memory/src/main/scala/filodb.memory/data/ChunkMap.scala, query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
=> fix(query): Add test validation to be enabled later.

CONTRIBUTING.md, doc/FiloDB_Taxi_Geo_demo.snb
=> misc(doc): Rename master to main in docs

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
After matching the regex in the shard key, before executing the query on a remote partition, the actual query needs to be updated with the new regex value.
=> bug(coord): Fix shardKeyRegexPlanner queryContext

project/Dependencies.scala
=> maint(core): Upgrade kamon to 2.1.4

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
=> perf(coord): Query Scheduler switch to ForkJoinPool

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
=> perf(coord): Query Scheduler switch to ForkJoinPool (#828)

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, http/src/main/scala/filodb/http/PrometheusApiRoute.scala, prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala, query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
=> bug(query): Fixes for step == 0 cases

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala, query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala, query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala
When step == 0 there are more places where loop does not terminate.
=> bug(query): More step==0 fixes in PeriodicSamplesMapper

memory/src/main/scala/filodb.memory/Block.scala
=> fix(memory): Reset the meta position when reclaiming blocks.

coordinator/src/main/scala/filodb.coordinator/FilodbCluster.scala, coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala, core/src/main/resources/filodb-defaults.conf, project/Dependencies.scala
Updating to versions that are supported by both Scala 2.11 and 2.12 (issue #457 )
=> misc: update ficus and akka-kryo to 2.12 supported version

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
=>  fix(coordinator): Query threads should start with "query-sched" for compatibility.

core/src/main/resources/filodb-defaults.conf, project/Dependencies.scala, project/FiloSettings.scala
Depends on unsupported downing provider.
Switched to supported downing provider which provides same functionality.
=> misc(akka): Switching downing provider.

cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala, cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
Remove shuffling since it is eating too much resources and creating other problems.
=> perf(sparkJobs): Remove shuffling since it is doing too much IO

cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
=> debug(cass): Log CQL scan that runs into timeout

project/Dependencies.scala
Some potential concurrency issues have been observed which might be related to monix.
Updating to a newer version which fixes a critical issue, although it might not be directly related to issues we've been seeing.
=> misc(core): Update monix.

akka-bootstrapper/src/multi-jvm/scala/filodb/akkabootstrapper/multijvm/BaseAkkaBootstrapperSpec.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/FailureProviderSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala
Support Failure routing for metadata and instant queries
=> feat(query): support failure routing for metadata and instant queries

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
=> refactor(query): move shardkeyfilters to logical plan util

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
* Use utf8 string instead of regular string to add extra join keys
* Apply previous fix to set join operators
=> bug(core): More Binary join fixes to include step and pi tags in join key

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
Log BinaryJoin queries between Aggregate and NonAggregate
=> log(query): Log BinaryJoin queries between Agg and NonAgg

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, core/src/main/resources/filodb-defaults.conf, gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala, query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
=> Cherry-pick '_step_' binary join fix into integration-0.9.9 

coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
Log BinaryJoin queries between Aggregate and NonAggregate for SinglePartitionPlanner
=> log(query): log BinaryJoin queries between Aggr and NonAgg for SinglePartitionPlanner

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
=> fix(query): Remove unused param from PartKeysExec

conf/logback-perf.xml, conf/promperf-filodb-server.conf, conf/promperf-source.conf, gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
Adding 1 node FiloDB server configuration with 8 shards to do local performance testing
=> perf(conf): Adding dev gatling performance test config

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/PlanDispatcher.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
More metrics to measure time elapsed since start of query execution.
Very useful to identify at which point query execution is stalling.
=> measure(query): Measure time elapsed for different points in execplan

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/ExtraOnByKeysUtilSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/query/QueryConfig.scala, core/src/test/resources/application_test.conf, query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala, version.sbt
Cherry-pick hotfixes to 0.9.9.2
=> Cherry-pick hotfixes to 0.9.9.2

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/ExtraOnByKeysUtilSpec.scala
Cherry-pick PR# 904 back to develop
=> bug(coord): Extra on-keys should be added only if on is nonEmpty (#904)

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
If memory cannot be reclaimed (perhaps a memory leak), the process must be manually restarted.
Exit and restart automatically after 5 minutes.
=> fix(core): Shutdown process if headroom task is failing.

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala, memory/src/main/scala/filodb.memory/data/Shutdown.scala
Cherry-Pick PR #915 to develop
=> bug(core): Shutdown when out of ingestion blocks; Mark ingestion blocks reclaimable on cassandra failure (#915)

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/WriteBufferPool.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Strongly type usage of NativeMemoryManager to make reclaim requirements pop out in code. Helps establish correctness in code more easily.
=> maint(core): Strongly type NativeMemoryMgr usage

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, memory/src/main/scala/filodb.memory/MemFactory.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala, query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala
Small misc low-risk cleanup fixes.
Remove some `span.mark` calls since they are not really in the right place.
=> bug(query): Misc small cleanup

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
=> feat(query): Allow custom AsyncHttpClientConfig in RemoteExec

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/test/scala/filodb.core/query/RangeVectorSpec.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala, query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, version.sbt
=> Cherry-pick "Restore chunk-map-lock debugging" from develop

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/test/scala/filodb.core/query/RangeVectorSpec.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala, query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, version.sbt
Retain TimeSeriesPartition.toString
=> Revert "debug(core): Restore chunk-map-lock debugging since we have a case of unreleased lock"

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, memory/src/main/scala/filodb.memory/MemFactory.scala, memory/src/main/scala/filodb.memory/data/Shutdown.scala
* BlockMemFactory.endMetaSpan not synchronized causing block position corruption
* Remove old spans
* Flush metrics on forced shutdown
=> bug(memory): BlockMemFactory.endMetaSpan not synchronized

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> bug(memory): Log lingering locks for debugging purposes

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> debug(core): TracingTimeSeriesPartition trace chunkmap locks

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> debug(core): TracingTimeSeriesPartition trace chunkmap locks (#950)

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> bug(memory): Log lingering locks for debugging purposes (#948)

core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala, project/FiloBuild.scala
=> maint(build): Remove unnecessary exclusion in sbt build

core/src/main/scala/filodb.core/query/ResultTypes.scala, prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/PromCirceSupport.scala, query/src/main/scala/filodb/query/PromQueryResponse.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
Support for stddev & stdvar for shard key regex using skip aggregate present
=> feat(query): stddev, stdvar for shard key regex

memory/src/main/scala/filodb.memory/BlockManager.scala
=> bug(memory): Update used block metric after reclaim

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, core/src/main/resources/filodb-defaults.conf
Simplify to remove heap in actor mailbox. No evidence that actor mailbox is the bottleneck.
=> maint(coord): Remove priority mailbox for query actor

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala, memory/src/main/scala/filodb.memory/format/MemoryLogger.scala, memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala, query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
=> debug(memory): Additional debugging for root causing faster-rate bug

query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
Time in record which is added to builder in TopBottomKRowAggregator is in seconds 
Convert time to millisecond
=> bug(query): time added to builder in TopBottomKRowAggregator is in seconds 

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Additional logging when Chunk Map lock state becomes negative
=> debug(memory): Additional debugging for debugging negative lock state

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
Support for binary join for metrics across multiple partitions and having queries with shard key regex
=> feat(query): binary join for metrics across multiple partitions and having shard key regex

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
* Dont log ask timeout exceptions
* For query-timeout, log message only, not stack
* consolidate error logging calls in query path
=> perf(query): Consolidate and reduce query exception logging further

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
=> bug(coord): Finish span properly

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
=> bug(coord): Finish span properly (#976)

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala
Absent and topk instant queries throw `step cannot be 0` error
Change for loop to use Iterator
=> bug(query): step cannot be 0 error for instant query

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
=> bug(memory): Faster-Rate bugfix mutating counter correction vectors - Part2

cli/src/main/scala/filodb.cli/CliMain.scala, cli/src/test/scala/filodb/cli/FilodbCliSpec.scala
-  bug in hexString to byteArray conversion causing errors in decoding partkeys
=> fix(misc): fix hexString to bytearray conversion

cassandra/src/main/scala/filodb.cassandra/Util.scala
`iter.hasNext` throws ReadTimeoutException as well. Need to wrap it with exponential backoff too.
=> bug(cass): Need to retry with expBackOff hasNext call too

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
=> bug(core): Cardinality tracker default quota increase

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
Additional tracing loggers for TracingTimeSeriesPartition
=> misc(core): additional tracing loggers for TracingTimeSeriesPartition

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> misc(core): Capture active timeseries count against shardKey

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, core/src/test/resources/application_test.conf, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
* Flag to enable/disable metrics with shard key tags (workspace / namespace)
* Report chunks queried with shard key tags
* Add one more metric to count time series by metric type
Important Note: The shard-key tags should be enabled only if the number of namespaces is bound. Otherwise metrics will be unbounded and slowly cause memory/heap bottlenecks.
Shard-key level metrics not enabled for downsample cluster
=> feat(core): ChunksQueried metric per namespace

query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
add debug level logging to TopBottomKRowAggregator to debug an issue with TopK queries
=> misc(query): add logging to TopBottomKRowAggregator to debug an issue

cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala, conf/timeseries-dev-source.conf, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/store/IngestionConfig.scala, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
add config driven flag to IngestionConfig, to allow duplicate samples
=> misc(core): add config override to accept/drop duplicate samples

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
fix a bug in condition to check whether to allow duplicate samples.
- if the timestamp of incoming sample is greater than or equal to (acceptDuplicateSamples=true) last seen timestamp, allow ingestion. otherwise drop sample. Former condition will be evaluated to true in most cases.
=> fix(core): fix a bug in condition to check whether to allow duplicate samples

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> bug(core): NPE in TimeSeriesShard due to UnknownSchema

cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala, core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala, gateway/src/main/scala/filodb/gateway/conversion/InfluxProtocolParser.scala, gateway/src/main/scala/filodb/gateway/conversion/InfluxRecord.scala, memory/src/main/scala/filodb.memory/format/ZeroCopyBinary.scala
In few places Strings use platform default character encoding. This change is to use `UTF-8` encoding.
=> misc(core): fix character encoding to use UTF-8 instead of platform default

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, project/FiloBuild.scala, spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala, spark-jobs/src/test/scala/filodb/repair/ChunkCopierSpec.scala
ChunkCopier modifications to support downsample schema.
=> Chunkcopier downsample

cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala, core/src/main/scala/filodb.core/metadata/Dataset.scala, core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala, gateway/src/main/scala/filodb/gateway/conversion/InfluxProtocolParser.scala, gateway/src/main/scala/filodb/gateway/conversion/InfluxRecord.scala, gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala, jmh/src/main/scala/filodb.jmh/GatewayBenchmark.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
- use UTF-8 encoding in `String.getBytes`
=> misc(core): change String.getBytes to use UTF-8 charset

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Addendum to earlier bug fix on time series purge. This PR captures time series count metrics and cardinality tracker.
=> bug(core): Capture counts of TS not on heap during purge

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
=> bug(core): Purge partitions log fix

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf
=> bug(core) Fixing config typo to enable shard level metrics

query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
=> fix(query): Handle NoSuchElementException in columnId retrieval

core/src/main/scala/filodb.core/store/IngestionConfig.scala
Cardinality Tracker will be enabled by default for all clusters.
It is NOT enabled for downsample mode.
=> feat(core): Enable Cardinality Tracker by default

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala, cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/test/resources/application_test.conf
Introducing parallelism in index recovery scans within a shard.
=> perf(core): Faster index recovery with parallel index scans

core/src/main/scala/filodb.core/GlobalConfig.scala, http/src/main/resources/reference.conf, http/src/main/scala/filodb/http/FiloHttpServer.scala, http/src/main/scala/filodb/http/HttpSettings.scala
Add the ability to load api routes at runtime.
=> Runtime routes

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/GlobalConfig.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, http/src/main/resources/reference.conf, http/src/main/scala/filodb/http/FiloHttpServer.scala, http/src/main/scala/filodb/http/HttpSettings.scala, memory/src/main/scala/filodb.memory/data/ChunkMap.scala
=> Merge develop into integration-0.9.13 - take2

prometheus/src/main/scala/filodb/prometheus/ast/TimeUnits.scala, prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala, prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
=> feat (query): subquery parsing

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
Adding more information in error message to help user decipher issue in binary join queries.
=> bug(query): More information in Binary Join Errors to help user

query/src/main/scala/filodb/query/exec/ExecPlan.scala
=> bug(query): Bug while checking if schema is empty

memory/src/main/scala/filodb.memory/data/ChunkMap.scala, prometheus/src/main/scala/filodb/prometheus/ast/Aggregates.scala, prometheus/src/main/scala/filodb/prometheus/ast/Base.scala, prometheus/src/main/scala/filodb/prometheus/ast/Expressions.scala, prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala, prometheus/src/main/scala/filodb/prometheus/ast/Operators.scala, prometheus/src/main/scala/filodb/prometheus/ast/Scalars.scala, prometheus/src/main/scala/filodb/prometheus/ast/TimeUnits.scala, prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala, prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
=> misc(parser): Rename AST and Parser class names for clarity.

prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala
=> bug(core): Partial results flag was skipped when result schema was empty

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Parallel additions into lucene index for downsample cluster
=> perf(core): Parallel bootstrap into lucene index for downsample cluster

cli/src/main/scala/filodb.cli/CliMain.scala
* Sort by cardinality in Card Tracker Cli output
* Also print counter dropped bit while printing vector contents
=> feat(cli): Minor CLI output improvements

query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala, query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala
Reset value does not increase for samples like 10, NaN
Increment reset value for counter restart
=> bug(reset): increment reset for counter restart

core/src/main/resources/filodb-defaults.conf
Tested locally and verified compression is happening
=> feat(core): Enable lz4 compression of akka remote serialized actor messages

core/src/test/scala/filodb.core/TestData.scala, query/src/main/scala/filodb/query/exec/StitchRvsExec.scala, query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
=> bug(query): Wrong Output Range in StitchRvsExec

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, memory/src/main/scala/filodb.memory/BlockManager.scala
Silly mistake in percent calculation
=> bug(core): Percent calculation bug

standalone/src/main/scala/filodb.standalone/FiloServer.scala
Fixes the following -
1. Server not shutting down on initialization errors.
2. NPE during shutdown due to http server not being initialised.
=> fix(standalone): shutdown server on initialization errors

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
=> fix:  fix for NaN values for min/max over time functions

core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
=> bug(core): Close rocksdb iterator after consuming results

core/src/main/scala/filodb.core/metadata/Schemas.scala
=> bug(core): Error when formulating limit error message

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
=> misc(coordinator): add temp debug log in LongTimeRangePlanner

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala, version.sbt
=> misc(coordinator): update logs in LongTimeRangePlanner

core/src/main/scala/filodb.core/memstore/IndexWriterPlus.scala, core/src/main/scala/filodb.core/memstore/MemStore.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
* Metrics on direct and mapped memory usage.
* Metrics on lucene segment merge activity.
Ideas adopted from: https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/metrics/AltBufferPoolMetricSet.java
and 
https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/update/SolrIndexWriter.java
=> feat(core): Basic lucene metrics on memory map usage and merge activity

spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
- test cases are broken due to regression caused by commit - #1152
=> fix(sparkJobs): fix failing test cases due to regression

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/query/QueryConfig.scala, core/src/test/resources/application_test.conf, doc/query-engine.md, query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala, query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala, query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala, query/src/test/scala/filodb/query/exec/SplitLocalPartitionDistConcatExecSpec.scala
Provide support for following Prometheus Histogram Queries:
- my_hist_sum{...}
- my_hist_count{...}
- my_hist_bucket{..., le="0.5"}
- count(my_hist_bucket{...})
- sum(my_hist_bucket{...}) by (le)
- histogram_quantile(0.9, sum(rate(my_hist_bucket{...}[5m])) by (le))
=> feat(query) : histogram backward compatibility

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
=> fix(query): Syntactic change for a comment

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
=> fix (comment) fixing a comment

project/Dependencies.scala, spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopierValidator.scala, spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierValidatorSpec.scala
**New behavior :** Add a validator spark job to validate data copied by PartitionKeysCopier.
=> Add validator for PartitionKeysCopier

spark-jobs/src/main/scala/filodb/repair/ChunkCopierValidator.scala, spark-jobs/src/test/scala/filodb/repair/ChunkCopierValidatorSpec.scala
**New behavior :** Add a validator spark job to validate data copied by ChunksCopier.
=> Add chunk copier validator

core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala, memory/src/main/scala/filodb.memory/EvictionLock.scala
Fix crash when update metrics is attempted after rocksdb is closed during shutdown of a shard.
=> bug(core): Fix race between rocksdb metrics update and close

.github/workflows/scala.yml
=> test: Attempt to create github action for CI

.github/workflows/runtests.sh, .github/workflows/scala.yml
=> misc: add git action for unit tests

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/FindMyShards.scala
=> misc(coordinator): Added an utility to print shard ranges

cassandra/src/main/scala/filodb.cassandra/Util.scala
This reverts commit 86de6c26f15b5fa2e9d93a4150412363f659b31c.
=> Revert "bug(cass): Backward compatibility with older versions of Guava (#1197)"

.github/workflows/scala.yml
=> enabling git actions on integration/main branches

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
'_bucket` is not removed for PeriodicSeriesWithWindowing
Remove _bucket from PeriodicSeriesWithWindowing
=> bug(query): remove _bucket from window functions

cli/src/main/scala/filodb.cli/CliMain.scala
```
./filo-cli '-Dakka.remote.netty.tcp.hostname=127.0.0.1' --host 127.0.0.1 --dataset prometheus --command findqueryshards --spread 1 --queries 'heap_usage{_ns_="App-0",_ws_="filodb-demo"}'
```
Prints the list of shards for the given query.
=> feat(cli): Added an option to find the shards for given queries

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
=> feat (query): support for absent_over_time for subqueries

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/ChangesFunctionSpec.scala
=> feat(query): add support for changes function for subqueries

project/FiloSettings.scala
=> misc(build): do not relocate guava/commons.google package

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/QuantileOverTimeSpec.scala
=> feat(query): add support for quantile_over_time function for subqueries

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf, memory/src/main/scala/filodb.memory/BlockManager.scala, memory/src/main/scala/filodb.memory/EvictionLock.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
1. Reduced logging during eviction
2. Query Tracking on eviction log driven by config
3. Timeout check immediately after start of async task to prevent wasted work.
4. Force evict when < 1% headroom
5. Increase dire circumstance max timeout to 90s
=> maint(core): Misc fixes - logging, timeout, config

core/src/main/scala/filodb.core/Messages.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, memory/src/main/scala/filodb.memory/EvictionLock.scala, query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala, query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
Addendum to previous fix on shared lock. Don't add lock to session (to be released) if it was not acquired due to timeout.
=> bug(core): Dont release shared lock on shared-lock timeout

query/src/test/scala/filodb/query/exec/rangefn/ChangesFunctionSpec.scala
=> bug(query) Fix for function changes unit test

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
When logical plan for instant query is converted to query window is not added
Add window for instant queries
=> bug(query): window is not added to instant query 

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/main/scala/filodb.core/store/ChunkSetInfo.scala, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
* Rename some query stat names
* Add dataset name in group-by for query utilization breakdown
* Change stats to use long instead of int
=> bug(core): DataBytesScanned query stat must be a long

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf
=> maint(core): Remove dataset from query stats and add partitionName

http/src/main/scala/filodb/http/PrometheusApiRoute.scala, prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala, query/src/main/scala/filodb/query/PromCirceSupport.scala, query/src/main/scala/filodb/query/PromQueryResponse.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala, query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
=> feat(query): Handle queryStats from remote response

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerHelper.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
Schema is getting instantiated for each call
Change schema to be a val instead of def
=> refactor(query):  change schemas type to val

core/src/main/resources/filodb-defaults.conf
Increase default token scan splits from 10 to 20
=> config(core): Increase default token scan split to 20

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
* Add downsample period as a tag in metric that tracks completion of jobs
* Add downsample period as a tag in log event that tracks completion of jobs
=> log(sparkJobs): Log downsample period in completion metric and log event

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
=> feat(sparkJobs): Publish downsample time as a metric to enable better alerts

query/src/main/scala/filodb/query/exec/ExecPlan.scala
When a query similar to below is issued, the results are not always aggregated and instead a series of 1s is returned.
For example:
sum_over_time(absent(foo)[5m:1m])
can return
1
1
1
1
1 
This happens because there is no schema returned by the raw query and RangeVectorTransformers that do not support empty schemas are not executed. sum_over_time does not support empty schemas but absent actually generates the schema on its own, nevertheless sum_over_time is removed before the schema is produced.
sum_over_time works properly, ie for query
sum_over_time(absent(foo)[5m:1m]) if no foo is found 5 is returned
To accomplish the above we only remove RangeVectorTransformer when the result of the previous RangeVectorTransformer …
=> fix(query): fix for sum_over_time(absent(foo)[10:1m]) when no time series can be found

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala
Return error response and status code for remote metadata queries
=> feat(query): return error response and status code for remote metadata

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
- check for UnknownSchema before shardKey retrieval. It is moved to code block where it is being used.
=> fix(core): check for UnknownSchema before shardkey retrieval

cli/src/main/scala/filodb.cli/CliMain.scala, coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/test/scala/filodb/query/LogicalPlanSpec.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
Adds `TsCardinalities` `LogicalPlan` to `SinglePartitionPlanner`.
Additionally changes `groupDepth` to 1-indexed.
=> feat(query): add TsCardinalities to SPP

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/PromCirceSupport.scala, query/src/main/scala/filodb/query/PromQueryResponse.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
Adds `TsCardinalities` logic to `MultiPartitionPlanner` infrastructure.
=> feat(query): add TsCardinalities MPP infrastructure

query/src/main/scala/filodb/query/LogicalPlan.scala
=> fix(query) Typo in return annotation

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
- Not using the nonMetricShardKey ColumnFilters to reduce the number of partitions a metadata query can be executed against.
- Using the nonMetricShardKey ColumnFilters to reduce the number of partitions a metadata query can be executed against.
=> feat(coord): use metadata columnfilters to reduce partitions

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerHelper.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
=> feat(query): Multipartition implementation for subquery

project/FiloSettings.scala, project/plugins.sbt
=> bug(packaging): Restore packaging issue due to sbt-jmh version bump

query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala
**Current behavior :** No change in user behavior.
**New behavior :** Changes to use HashJoins instead of nested loop.
=> perf(query) Changes to UNLESS  SetOperator to use hash join

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala, gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala, jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala, memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala, memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala, project/Dependencies.scala
third integration merge for 0.9.16
=> Merge 'develop' into 0.9.16-integration

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
=> Tests to verify aggrgate pushdown for subqueries

coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
fix failing testcases due to interface changes. These test cases were committed after the other commits PR build passed but before it is committed.
=> fix(misc): fix failing testcases due to interface changes

project/FiloSettings.scala
=> bug(build): Fix packaging conflict after introduction of caffeine dependency

cli/src/main/scala/filodb.cli/CliMain.scala, coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala, coordinator/src/main/scala/filodb.coordinator/queryengine/Utils.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/TargetSchemaProvider.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, core/src/test/resources/application_test.conf, core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala, core/src/test/scala/filodb.core/binaryrecord2/HashRandomnessSpec.scala, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala, gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala, gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala, gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala, jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala, memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala, memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala, project/Dependencies.scala, project/FiloSettings.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, standalone/src/main/java/filodb/standalone/SimpleProfiler.java
=> Merge 'develop' into 0.9.16-integration 

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala, cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala, conf/timeseries-filodb-server.conf, core/src/main/resources/filodb-defaults.conf, core/src/test/resources/application_test.conf, spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala, spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala, spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
Support simulation mode for Cardinality Buster
=> feat(sparkJobs): Card Buster simulation mode

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
Single label value query backward compatibility
- older version returns Map type where as newer version works with List type, this change handles Map type results returned by older version and converts it into StringList.
=> fix(query): handle labelvalue query serialization for backward compatibility

query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
LabelCardinality now uses lucene faceting to count label cardinalities, as opposed to iterating each time series that match filters.
Benchmarks show that faceting call is several orders of magnitude faster than iteration. So we make multiple calls to iterate over each label's values and add to the sketch instead of loading each partKey into heap.
=> perf(query): Label cardinality uses faceting improvement

spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
=> perf(sparkJobs) Reduce log volume for cardinality buster

core/src/main/java/filodb/core/memstore/DownsampleIndexCheckpointer.java, core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/test/scala/filodb.core/memstore/DownsampleIndexCheckpointerSpec.scala
=> first revision of persisent index storage for downsample filodb clusters

doc/akka-bootstrapper.md
=> bug(docs): Fix documentation link

core/src/main/resources/filodb-defaults.conf
=> switching to antlr

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/metadata/Dataset.scala, core/src/main/scala/filodb.core/metadata/Schemas.scala, core/src/test/scala/filodb.core/TestData.scala, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala, core/src/test/scala/filodb.core/metadata/SchemasSpec.scala, version.sbt
cherry-pick following commits from develop
https://github.com/filodb/FiloDB/commit/0e05d8ce10acf811a0787513fe4a1e9eb975052b
https://github.com/filodb/FiloDB/commit/2b59f4e6d1730ca3d0a24af4ff763871b2f35ad9
=> cherry-pick commit: add support for multi-field facets to partition-key columns

conf/timeseries-durable-downsample-index-dev-source.conf, conf/timeseries-filodb-durable-downsample-index-server.conf, core/src/main/java/filodb/core/memstore/DownsampleIndexCheckpointer.java, core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala, core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala, core/src/main/scala/filodb.core/memstore/IndexMetadataStore.scala, core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesStore.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
=> test (core): Updated test for durable index storage

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, query/src/main/scala/filodb/query/exec/PlanDispatcher.scala
=> feat(exec): add uncaught exception metric

CONTRIBUTING.md, README.md, doc/sharding.md
Change period to comma.  Remove pre colon space. Remove orphaned doc example brace.
Same as main
Same as main; slight doc updates for formatting
=> bug(docs): small typos, remove orphan doc brace

query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/exec/InternalRangeFunction.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
Implement present over time function
=> feat(query): present over time function

project/Dependencies.scala
This reverts commit 1c995cbd7e912cb1a391117069b753d0a5efcf9f.
=> Revert "maint(core): Upgrade kamon 2.2.2 -> 2.5.6 (#1434)"

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
Protecting read-modify-write paths in CardinalityTracker which are not threadsafe They get invoked in the ingestion pipeline from multiple threads.
=> bug(core): Make cardinality tracker read-modify-write methods synchronized

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, memory/src/main/scala/filodb.memory/EvictionLock.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
Close Query Session was missed in one case.
=> bug(query): Release eviction lock bug fix

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/metadata/Schemas.scala, gateway/src/main/scala/filodb/gateway/GatewayServer.scala, gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala, gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala, gateway/src/test/scala/filodb/gateway/conversion/InputRecordBuilderSpec.scala
add support for delta measurements in addition to cumulative measurements.
[OTEP Temporal quality](https://github.com/open-telemetry/oteps/blob/main/text/metrics/0098-metric-instruments-explained.md#temporal-quality)
=> feat(core): add support for delta counters and delta histograms

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/DistConcatExec.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/main/scala/filodb/query/exec/SetOperatorExec.scala, query/src/main/scala/filodb/query/exec/StitchRvsExec.scala, query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
Refactor & simplify the reduceSchema method.
=> refactor(query): Refactor and simplify reduceSchema method in ExecPlan

query/src/main/scala/filodb/query/exec/ExecPlan.scala
Disabling pipeThrough to debug performance issue we are seeing.
=> debug(core): Disable pipeThrough to debug performance issue

query/src/main/scala/filodb/query/exec/ExecPlan.scala
Cherrry pick back to develop 
```
commit 869cd2d6e0b64def5f21f8a303c10335aa72c1c3
debug(core): Disable pipeThrough to debug performance issue (#1471)
```
=> debug(core): Disable pipeThrough to debug performance issue (#1471)

README.md
=> docs: Update dev setup documentation

.travis.yml, project/FiloSettings.scala, scripts/schema-truncate.sh
* fix `sbt standalone/assembly`
* fix schema-truncate script
* Run assembly target in Travis PRB
=> build(filodb): Fix assembly; add assembly to PRB

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala
Fix for errors such as 
```
Expected schema 
ResultSchema(List(ColumnInfo(timestamp,TimestampColumn), ColumnInfo(value,DoubleColumn)),1,Map(),Some(168),List(0, 1)), found schema 
ResultSchema(List(ColumnInfo(timestamp,TimestampColumn), ColumnInfo(value,DoubleColumn)),1,Map(),Some(1),List(0, 5))
```
occurring due to strict result schema enforcement for Multi-partition aggregation.
=> bug(query): Schema mismatch bug fix for multi-partition aggregation

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
* New metric to measure total cpu time
* Unit test to confirm backward compat
=> feat(core): Query CPU time metric and unit test for backward compat

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala, version.sbt
b8f07c5f1
fix(misc): make shardKey labels in targetSchema config implicit (#1504)
=> cherry-pick commit to support implicit target-schemas

README.md
HomeBrew does not set the right java home for kafka on M1 Mac. Update the fix on ReadMe.
=> docs(core) Update readme for Kafka troubleshooting on M1

prometheus/src/main/scala/filodb/prometheus/parse/AntlrParser.scala, prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
378d1509ef79f7ffca0b523e6fa0ce76981c0b13
fix(parser): add support for zero-value time units
=> cherry-pick from develop to integration

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/main/scala/filodb.coordinator/queryengine/Utils.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/test/resources/application_test.conf, gatling/src/test/scala/filodb/gatling/QueryRangeSimulation.scala, query/src/main/scala/filodb/query/exec/PlanDispatcher.scala
Minor code refactor for reusability
=> refactor(core,coord): Minor code refactoring for reusability

core/src/main/resources/filodb-defaults.conf
Added missing downsampler configuration to `delta` data-schemas
=> fix(core): add downsampler config to delta-counter/delta-histogram schemas

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, version.sbt
commit ae5f1ad1b9766683363e5340c284285d104a0d6e
fix(query): relax target-schema agg/bin-join pushdown requirements (#1511)
=> cherry-pick from develop to main

memory/src/main/scala/filodb.memory/EvictionLock.scala
=> feat(core): Metric to track acquisition latency of shared eviction lock

memory/src/main/scala/filodb.memory/EvictionLock.scala
cherry picking @vishramachandran's PR to track the eviction time in the integration
=> cherry picking PR "feat(core): Metric to track acquisition of shared eviction lock (#1524)" to get 

project/plugins.sbt, project/protoc.sbt
=> trying to fix M1 build

project/Dependencies.scala
=> removing duplicate dependencies on akka coming from various libraries

version.sbt
Fix erroneously updated version.sbt
=> fix(core) Fix erroneously updated version.sbt

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala, query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala
vector(static_value) on rhs returns TS of static_value when lhs returns empty. The fix is added to re-enable the failing `OperatorPrecedence` integration tests.
In a binary join query of format "lhs or vector(static_value)",  FiloDB returns empty TS when lhs evaluates to empty result. However, prometheus returns a TS of static_value based on the range parameters given. This is a corner case scenario we found for or vector(static_val) scenario.
FiloDB is compliant to the prometheus results on the given above scenario.
=> fix(query): vector(static_value) on rhs returns TS of static_value when lhs returns empty

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
We can use the timestamp in the container as the time the metrics enter the pipeline. Create a histogram to record the time difference between after ingestion time with the container timestamp.
- Changes to the HTTP public …
=> Add a metric to measure ingestion pipeline time cost.

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/metadata/Schemas.scala
Today, when histogram count or sum is queried, the data scanned estimation takes the entire histogram schema (all columns) instead of just the queried columns.
This fix ensures the the estimate is counted only for the queried columns.
=> fix(core): Fix for overestimation of data scanned when querying histogram sum or count

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala, core/src/main/scala/filodb.core/query/QueryContext.scala, core/src/main/scala/filodb.core/query/ResultTypes.scala, core/src/test/scala/filodb.core/query/QueryContextSpec.scala, query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala, query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala, query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
=> Fixes for enforcing limits

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
**Other information**: Simplifying local data-structure while modifying cardinality count
=> Simplifying local data-structure while modifying cardinality count

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala, core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala, core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
Adding collector to iterate through all lucene index documents and calculate cardinality count
**New behavior :** Adding a new collector, to help with calculating cardinality by iterating through the lucene index documents
=> feat(core) Adding collector to iterate through all lucene index documents and calculate cardinality count

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
Added missing increments to activeTimeSeries count.
=> fix(core): Negative active time series cardnality due to missed increments

http/src/main/scala/filodb/http/PromQLGrpcServer.scala, query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala
Trace context is not propagated with the gRPC Query service and no latency metrics are reported
Trace context is propagated with the gRPC Query service and latency metrics are reported
=> feat(query) Add tracing capabilities to gRPC QS along with histogram metrics

query/src/main/scala/filodb/query/PromCirceSupport.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
If histogram from a Remote exec contains a NaN, the decoding fails with an error like the following
```Caused by: io.circe.DecodingFailure$$anon$2: Double: DownField(0.001),MoveRight,DownArray,DownArray,DownField(values),DownArray,DownField(result),DownField(data)```
Specifically the history shows the bucket whose value is ``NaN`` in the response.
Instead of relying on circe to decode the ``Map[String, Double]`` we have implemented a decoder that attempts to parse the ``String`` value to ``NaN``.
=> fix(query) Handle NaN values as part of histogram map response

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
Currently, aggregation reductions may not be evenly distribute across FiloDB nodes. Since that the dispatcher is not chosen randomly, a fixed set of nodes might perform all reductions. This PR instead selects a random dispatcher to perform each reduction.
=> fix(coordinator): select random dispatcher for aggregation

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
=> fix(core) make the error message more friendly to users

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
Co-authored-by: Yu Zhang <yzhang999272@apple.com>
(cherry picked from commit 5b05779aa36475bb5c91c7a71ae092795ae79b06)
=> fix(core) make the error message more frendly to users. (#1593)

spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
=> fix(job) handle null pointer in cardinality busting job

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
Default alloc configs should sum to 100.
=> fix(core): Fix memory alloc config

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
For regex shard key we need to aggregate across all nodes. InProcessPlanDispatcher is needed.
=> fix(core) fix the binary join aggregation across different partitions.

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
Co-authored-by: Yu Zhang <yzhang999272@apple.com>
(cherry picked from commit 5b05779aa36475bb5c91c7a71ae092795ae79b06) (cherry picked from commit f14a13cedaa9dbf62bc800cbfa71b019585f23df)
- …
=> fix(core) make the error message more frendly to users. (#1593) (#1630)

spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
skip busting the problematic entry.
Co-authored-by: Yu Zhang <yzhang999272@apple.com>
(cherry picked from commit 6ac025558a1f8ae7e879227434b9e5014d28b3a8)
- Changes to query parsing / PromQL …
=> fix nullpointer happened in cardinality busting job. (#1631)

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/PromCirceSupport.scala, query/src/main/scala/filodb/query/PromQueryResponse.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/test/scala/filodb/query/LogicalPlanSpec.scala, query/src/test/scala/filodb/query/PromCirceSupportSpec.scala, query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala, query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala
Cherry pick Cardinality V2 Query plan change.
=> feat(query): Cardinality V2 API Query Plan changes (#1637)

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
Adding CPU Nanos Time consumed for Lucene index lookups in query stats, especially since we are seeing this in frequently as a hotspot in CPU profile information
=> feat(core): Add Query CPU Time for Index Lookups

core/src/main/resources/filodb-defaults.conf
add schema changes to support downsampling of pre-aggregated data.
=> misc(core): add downsample support for aggregated data

version.sbt
=> Bump filodb version to 0.9.23.

coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala, coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala, coordinator/src/main/scala/filodb/coordinator/v2/FiloDbClusterDiscovery.scala
**Current behavior :** There were two issues in the ClusterV2 setup. They are:
i.  Incorrect resolution of hostnames, resulting in no communication between pods
ii. ShardHealthStats reporting assigned and unassigned status incorrectly
**New behavior :** Fixes for above issues is added
=> fix(cluster): Fixes for clusterV2 in kubernetes setup 

version.sbt
=> Bump filodb version to 0.9.24

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
Number of samples queried is currently valued same whether or not the sample is a histogram or a counter.
This PR adds a factor to histogram buckets so the number accounts for bigger histogram samples
=> fix(core): Add histogram bucket factor in samples queried metric

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
Include a metric to count number of rows exported (number of rows in filteredRDD) being sent to be written to the Iceberg Table.
=> misc(iceberg-export): Include a metric to count number of rows exported (number of rows in filteredRDD)

query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala, query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala
When there is only one sample available for delta counters during irate function, we do not return any result for the same since we do not have info about the publish interval. 
When there is only one sample for delta counters, we will assume a default 60 second publish interval to return the value for that instant.
=> Irate delta fix

query/src/main/scala/filodb/query/exec/ScalarBinaryOperationExec.scala, query/src/test/scala/filodb/query/exec/rangefn/ScalarFunctionSpec.scala
Queries such as ``time() - 60 * 60`` generate plans like
```
T~ScalarOperationMapper(operator=SUB, scalarOnLhs=true)
-FA1~TimeFuncArgs(RangeParams(1711402246,0,1711402246))
-E~ScalarBinaryOperationExec(params = RangeParams(1711402246,0,1711402246), operator = MUL, lhs = Left(60.0), rhs = Left(60.0)) on InProcessPlanDispatcher(QueryConfig(...)))
```
However, the ``RangeVectorTransformer`` never gets applied during evaluating.  This result this is simply executing ``60*60`` which gives ``3600``
Now we execute the transformers which should give the tight result for ``time() - 60*60``
=> fix(query) Range Vector Transformers were not applied for ScalarBinaryOperationExec

version.sbt
fix(version): Updating version for main branch
=> fix(version): Updating version for main branch

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala, coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, core/src/test/resources/application_test.conf, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala, query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala, query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
**Current behavior :**  We don't have any validation check for the cardinality queries. 
1. Adding a filodb partition check for TsCardinalities queries.
2. Passing filodb-partition in QueryContext for Metering queries
=> fix(Cardinality): Adding filodb partition check for cardinality queries 

query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
``hasNext`` check is not called before ``next`` is called
Check added.
=> fix(query) next on empty iterator to check if the iterator has a value before calling next

grpc/src/main/protobuf/query_service.proto, query/src/main/scala/filodb/query/ProtoConverters.scala
=> fix(grpc): add missing PlannerParams proto field

grpc/src/main/protobuf/query_service.proto, query/src/main/scala/filodb/query/ProtoConverters.scala
=> cherry-pick missing PlannerParams field

query/src/main/scala/filodb/query/ProtoConverters.scala
=> fix(query): add missing PlannerParams converter value

query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala
=> cherry-pick revert commits from main

query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala, query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala
=> cherry-pick RemoteExec transformer hotfix commits

query/src/main/scala/filodb/query/exec/ExecPlan.scala, query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala, query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala, query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala, query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala, version.sbt
=> hotfix 0.9.25.8: apply transformers to RemoteExecs

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
Currently when we stitch the data from partitions after migration of assignments the step size in second and subsequent partitions is off by ``periofOfUncertainty`` seconds from the expected snapped time. 
The fix first adds the period and then snaps the intervals
=> fix(query) Fix alignment of dates based on step and period of uncertainty for stitch

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
=> cherry-pick: do not apply limits to metadata queries

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala, version.sbt
=> hotfix cherry-pick 0.9.25.9: do not apply limits to metadata queries

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala, version.sbt
Merge export changes from integration to main branch.
=> Merge Export changes from integration to main

project/Dependencies.scala, project/FiloSettings.scala
**Changes :** Updated Kamon Version from 2.2.2 to 2.7.3 to upgrade kamon.openTelemetry dependencies
=> misc(core): Updated Kamon version

core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/metadata/Schemas.scala
Adding a new schema to support preagg otel delta histograms
=> Adding a new schema for Preagg Otel Delta Histogram support

query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala
Currently, `RemoteExec` plans do not correctly update `QueryStats`. This PR adds this missing update step.
=> fix(query): update QueryStats in RemoteExec

README.md
Fix two doc issues found while running through end to end setup:
* Add a note that newer ZooKeeper versions conflict with port 8080 and how to resolve
* Update filo-cli usage to not pass the filodb.v2-cluster-enabled flag.  The default configs do not enable v2 so this flag causes errors
=> docs(core): Fix E2E dev setup

query/src/main/scala/filodb/query/exec/RemoteExec.scala, query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala
=> cherry-pick fix(query): update QueryStats in RemoteExec (#1812)

README.md, coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/TargetSchemaProvider.scala, core/src/main/scala/filodb.core/Utils.scala, core/src/main/scala/filodb.core/metadata/Schemas.scala, core/src/main/scala/filodb.core/query/ColumnFilterMap.scala, core/src/test/scala/filodb.core/query/ColumnFilterMapSpec.scala, grpc/src/main/protobuf/query_service.proto, project/Dependencies.scala, project/FiloSettings.scala, prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/exec/InternalRangeFunction.scala, query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala, query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala, query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala, spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala, version.sbt
=> merge develop->integration for 0.9.27

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
- [ X ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
NullPointerException is thrown if shard is unassigned
Exception is not thrown
=> cherry-pick fix(query): fixing shard level failover for clustering V2

core/src/test/scala/filodb.core/TestData.scala, query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala, query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala
Histogram selectors with 'offset' throw "unsupported_operation" errors
Histogram queries work fine with offset
=> Histogram Selectors with Offset handling

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala, project/Dependencies.scala
- Upgrading 8 year old JCTools library to latest available version
=> misc(core): upgrade jctool library to latest version

core/src/main/scala/filodb.core/query/TransientRow.scala, query/src/main/scala/filodb/query/exec/StitchRvsExec.scala, query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
**New behavior :** fix for StitchRvsExec bugs
=> fix(query):  cherry picking StitchRvsExec's bugfixes 

prometheus/src/main/scala/filodb/prometheus/parse/LegacyParser.scala, prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala, prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
handle escaped dot character in query
=> fix(query): fix parse issue with escaped dot character

version.sbt
incrementing minor version for 0.9.27 release
=> fix(version): incrementingminor version 

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/GlobalConfig.scala, prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala, query/src/test/scala/filodb/query/LogicalPlanSpec.scala, query/src/test/scala/filodb/query/util/HierarchicalQueryExperienceSpec.scala
**New behavior :**  Adding support for LogicalPlan updates, to use higher level aggregation metric if applicable based on the given tags
=> feat(query): Add support for LogicalPlan updates, to use higher level aggregation metric if applicable based on the given tags

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/aggregator/CountRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/QuantileRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/LocalPartitionDistConcatExecSpec.scala
=> fix(query) Fixed mismatched schema regarding fixedVectorLen.

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/aggregator/CountRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/QuantileRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/LocalPartitionDistConcatExecSpec.scala, version.sbt
=> Fixed mismatched schema regarding fixedVectorLen

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala, query/src/main/scala/filodb/query/exec/aggregator/CountRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/QuantileRowAggregator.scala, query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala, query/src/test/scala/filodb/query/exec/LocalPartitionDistConcatExecSpec.scala
* Fixed mismatched schema regarding fixedVectorLen.
* Do not compare against colIds on schema match. ---------
=> fix(query) Fixed mismatched schema regarding fixedVectorLen. (#1855)

conf/logback-dev.xml, coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/main/resources/filodb-defaults.conf, core/src/main/scala/filodb.core/query/QueryConfig.scala, core/src/main/scala/filodb.core/query/QueryUtils.scala, core/src/main/scala/filodb.core/query/RangeVector.scala, core/src/test/resources/application_test.conf, jmh/src/main/scala/filodb.jmh/PlannerBenchmark.scala, project/Dependencies.scala, query/src/main/scala/filodb/query/ProtoConverters.scala
=> cherry pick perf fixes

http/src/main/scala/filodb/http/PromQLGrpcServer.scala
PromQLGrpcServer does not process requests bigger than 4MB.
PromQLGrpcServer would process requests up to the limit given in the configuraiton.
n/a
=> feat(query): allowing the GRPC service to handle bigger input messages.

http/src/main/scala/filodb/http/PromQLGrpcServer.scala
=> Cherry-pick: Allowing the GRPC service to handle bigger input messages.

.github/workflows/scala.yml, core/src/rust/filodb_core/src/ingestion/fields.rs, core/src/rust/filodb_core/src/query_parser.rs, core/src/rust/tantivy_utils/src/collectors/column_cache.rs, core/src/rust/tantivy_utils/src/collectors/string_field_collector.rs, core/src/rust/tantivy_utils/src/collectors/time_collector.rs, core/src/rust/tantivy_utils/src/collectors/time_range_filter.rs, core/src/rust/tantivy_utils/src/query/cache.rs, version.sbt
build tests were failing due to the rust lint issues
rust lint failure is fixed and tests are run properly
=> fix(core): Fix latest clippy errors in Rust code and bumping the version

core/src/rust/filodb_core/src/index.rs, core/src/test/scala/filodb.core/memstore/PartKeyIndexRawSpec.scala
cherry-pick making type field fast in tantivy
=> cherry-pick making type field fast in tantivy

.github/workflows/scala.yml
=> upgrade the upload-artifact to v4.

coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala, grpc/src/main/protobuf/query_service.proto, http/src/main/scala/filodb/http/PromQLGrpcServer.scala
=> misc(server): Developer setup for FiloDB grpc service

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala, query/src/main/scala/filodb/query/PlanEnums.scala
Fix logical plan to query generation for `last_over_time_is_mad_outlier` function so plan can be forwarded to other partitions
=> bug(coord): Fix plan to query generation for outlier function

coordinator/src/main/scala/filodb.coordinator/ShardStatus.scala
**New behavior :** Adding helper functions for debugging and logging the state of ShardMapperV2. Also fixing the value of `nodeNum`  in `prettyPrint` function.
=> misc(cluster): Adding helper functions for ShardMapperV2

conf/timeseries-dev-source.conf, core/src/main/scala/filodb.core/Utils.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, core/src/main/scala/filodb.core/store/ReadablePartition.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala, core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
Cherry-picking commits to Integration branch
=> Cherry-picking commits to Integration branch

conf/timeseries-dev-source.conf, core/src/main/scala/filodb.core/Utils.scala, core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala, core/src/main/scala/filodb.core/store/ChunkSource.scala, core/src/main/scala/filodb.core/store/ReadablePartition.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala, core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala, spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala, version.sbt
Cherry Picking changes from integration to main for 0.9.29.4
=> Cherry Picking changes from integration to main for 0.9.29.4

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
=> Revert "perf(memstore) TimeRangeChunkScan optimization when querying data in current ingesting chunk"

coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala, core/src/test/resources/application_test.conf
- [ X ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [ X ] Tests for the changes have been added (for bug fixes / features) ?
Unit tests are run with the legacy style of partkeys C* table
Unit tests are run with the parkeys C* table v2
n/a
=> test(core): switching to part keys v2 table and minor serialization test

coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala, coordinator/src/main/scala/filodb.coordinator/ShardStatus.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/PartitionLocationPlanner.scala, coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala, coordinator/src/main/scala/filodb/coordinator/v2/FiloDbClusterDiscovery.scala, coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
=> Dev integ merge 9 30 v2

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
**New behavior :** Adding counter to better track the partkey index changes ( both adds and updates ). This will help us better track the index churn.
=> misc(index): Adding counters to track partkey index additions and updations during kafka ingestion

core/src/rust/Cargo.lock, core/src/rust/filodb_core/Cargo.toml, core/src/rust/filodb_core/src/ingestion.rs, core/src/rust/filodb_core/src/ingestion/fields.rs, core/src/rust/filodb_core/src/query_parser.rs, core/src/rust/filodb_core/src/query_parser/filodb_query.rs, core/src/rust/tantivy_utils/Cargo.toml, core/src/rust/tantivy_utils/src/collectors/column_cache.rs, core/src/rust/tantivy_utils/src/collectors/part_key_collector.rs, core/src/rust/tantivy_utils/src/collectors/part_key_record_collector.rs, core/src/rust/tantivy_utils/src/query/cache.rs, version.sbt
cherry-pick maint(index) Upgrade tantivy 0.22 -> 0.24 (#2001)
=> cherry-pick maint(index) Upgrade tantivy 0.22 -> 0.24 (#2001)

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala, coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala, core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
raw columnstore initialization is missed during Downsample cluster's Dataset setup phase.
added raw columnstore initilization to Dataset setup phase.
=> fix(downsample): raw columnstore initialization is missing

core/src/main/scala/filodb.core/Utils.scala
**Current behavior :**  Dup hardcoded schema names were used.
**New behavior :** Removed the hard coded names and using the name from schema definitions itself.
=> misc(naming): Removing hard-coded schema names from Utils.scala

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala, coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala, coordinator/src/test/scala/filodb.coordinator/queryplanner/AggLpOptimizationSpec.scala, grpc/src/main/protobuf/query_service.proto, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/PlanEnums.scala, query/src/main/scala/filodb/query/lpopt/AggLpOptimization.scala, query/src/main/scala/filodb/query/lpopt/AggRuleProvider.scala, query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala
=> feat(query): Translate raw to pre-agg with rule versions

coordinator/src/test/scala/filodb.coordinator/queryplanner/AggLpOptimizationSpec.scala, query/src/main/scala/filodb/query/LogicalPlan.scala, query/src/main/scala/filodb/query/lpopt/AggLpOptimization.scala, query/src/main/scala/filodb/query/lpopt/AggRuleProvider.scala, query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala
test case refactor, more test cases, rule versions with active/inactive status, more comments and docs
=> feat(query): Raw to aggregated query translation Round 2

version.sbt
=> version bump to 0.9.30.9

spark-jobs/src/main/scala/filodb/labelchurnfinder/LabelChurnFinder.scala
Simple main entry point rename since it collides with another class
=> feat(spark-jobs): Label churn main class rename

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala, core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
Add tenant tags for out of order samples metrics to help clients get to root cause
=> feat(core): Emit metrics on which tenants are emitting out of order samples
