filodb/FiloDB

spark/src/main/scala/filodb.spark/FiloRelation.scala

A minor fix. 
If we log the `schema` before its init, it's always `null` in logging.

log schema after its init in FiloRelation

---

README.md
cassandra/src/main/scala/filodb.cassandra/FiloCassandraConnector.scala

This PR adds config keys for username and password to application.conf, as follows:
cassandra {
hosts = ["localhost"]
port = 9042
keyspace = "filodb"
username = "cassandra"
password = "cassandra"
}
There are two tests that appear to be failing to pick up the auth settings.  After stepping through with the debugger I am unable to determine the root cause of this, as the session in scope always contains the settings.  My real-world tests don't exhibit this behavior, so I'm at a bit of a loss as to where the issue is.

Added support for Cassandra Authentication

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/test/scala/filodb.cassandra/metastore/ColumnTableSpec.scala
cassandra/src/test/scala/filodb.cassandra/metastore/DatasetTableSpec.scala

The getScanSplits function in filodb.cassandra.columnstore.CassandraColumnStore.scala has been changed to ensure that the splits of token ranges per node conforms to the splits_per_node parameter specified. Timeout set in the tests in ColumnTableSpec and DatasetTableSpec.

Changes made in getScanSplits function

---

filo-cli

The previous expression was dropping the initial '0.', resulting in 2.1-SNAPSHOT instead of 0.2.1-SNAPSHOT

fixed regex to grab everything in version.sbt quotes

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala

Unwrap token ranges before querying by token range to fix read path issues like count mismatch and unable to read few partitions. Issue #101

Unwrap token ranges before querying by token range to fix read path issues

---

cassandra/src/main/scala/filodb.cassandra/FiloCassandraConnector.scala

This allows to be compatible with SparkConf.set("spark.filodb.cassandra.hosts","someIP,anotherIP")

Change Cassandra hosts parameter from List to String

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/ChunkRowMapTable.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/store/ColumnStore.scala
core/src/main/scala/filodb.core/store/InMemoryColumnStore.scala
core/src/test/resources/application_test.conf
spark/src/main/scala/filodb.spark/FiloRelation.scala
spark/src/test/scala/filodb.spark/SaveAsFiloTest.scala

This feature avoids full table scan when multiple partition keys are provided via IN clause in select query. Issue #109.

Ability to scan multiple partitions using IN operator

---

README.md
core/src/main/scala/filodb.core/KeyType.scala
core/src/test/scala/filodb.core/metadata/ComputedColumnSpec.scala

This fixes the bug where using a DoubleColumn as the segment key was not possible. Also added a test for using `:round` to round to non-integer values and fixed the URL to Travis. Tests pass on my end.

Fix double segment key rounding

---

cassandra/src/main/scala/filodb.cassandra/Util.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/ChunkRowMapTable.scala

Related to issue: No error is displayed when cassandra nodes are down for read path #120

Modified to handle errors during read path

---

cassandra/src/main/scala/filodb.cassandra/Util.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/ChunkTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/FilterTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IndexTable.scala

No error is displayed when cassandra nodes are down for read path #120

Modified to hanlde read path errors

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/test/scala/filodb.coordinator/ReassignShardsSpec.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
doc/http_api.md
http/src/main/scala/filodb/http/ClusterApiRoute.scala
http/src/test/scala/filodb/http/ClusterApiRouteSpec.scala
scalastyle-config.xml

We currently have a single /reassignshards request endpoint that unassigns and assigns the shards.
https://github.com/filodb/FiloDB/commit/0a8dc865e41da491d618902de7d37dc249560ff0
Removing the /reassignshards endpoint and creating following two new endpoint:
1. POST /api/v1/cluster/datasethere/stopshards - shard stop request that accepts the following payload:
```
{
"shardList": [23, 24]
}
```
2. POST /api/v1/cluster/datasethere/startshards - shard start request that accepts the following payload:
Sample input as follows:
```
{
"address": "akka.tcp://filo-standalone@23.13.16.45:91007",
"shardList": [23, 24]
}
```

feat(coordinator): Add start/stop shard support

---

README.md
conf/timeseries-standalonetest-source.conf
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
project/FiloSettings.scala
prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/ClusterSingletonFailoverSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/IngestionAndRecoverySpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/StandaloneMultiJvmSpec.scala

This PR creates a new special function, parseable through PromQL, `_filodb_chunkmeta_all` which returns `ChunkSetInfo` records for matching time series.  It returns all the fields from the ChunkSetInfo plus additional data (# bytes and the Reader class) for chunks in one particular column.  This data can be used to debug many issues including potential missing chunks or missing data, as well as to debug encoding and compression issues.
other related changes:
- One line minor fix for index startTime
- Fixed the standalone IngestionAndRecoverySpec; switched TestTimeseriesProducer to use the new Gateway pipeline

feat(core,query,prom): LP, ExecPlan, and _filodb_chunkmeta_all function to debug chunk metadata info

---

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
project/FiloSettings.scala

… Speeds up in-memory queries
An ODP task is always created on the ingestion thread for every query, whether there are on-demand paging partitions or not.   This leads to higher query latencies and potential timeouts if the ingestion thread gets stuck.
If there are no new partitions to on-demand page (i.e. all partitions asked are already in memory, which is vast majority of times), an empty task with Nil is returned immediately rather than being scheduled on the ingestion thread.  Thus in most cases the ingestion thread will not block queries.

fix(core): Don't schedule an empty ODP task on the ingestion thread

---

http/src/main/scala/filodb/http/PrometheusApiRoute.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/util/IndexedArrayQueue.scala
query/src/test/scala/filodb/query/exec/SlidingWindowIteratorSpec.scala

Bug Fixes for:
1. Sliding window keeps a last sample even after time series stops ingesting,
so functions like SumOverTime return incorrect value after stop.
2. Sliding window should not include values at window start time.
Otherwise, values are double counted for the case where step==window

bug(query): Sliding window bug fixes

---

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

DropOutOfOrderSamples iterator does an eager invocation of getNext
The getNext invocation has been changed to be lazy. We do not want iteration to start during the setup  phase of the query pipeline.

bug(query): Fix eager getNext in iteration chain

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

Reduction of aggregates to calculate average had a bug where zero count and NaN was not being handled correctly.

bug(query): Avg aggr over RVs did not handle 0 counts properly

---

README.md
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

There is no way to specify the target column name for PromQL queries.  Instead, it is assumed the schema is timestamp/value, and the second column is always used as the value column.
1. A special PromQL tag, `__col`, is exposed and can be used to target a specific column for querying
2. `SelectRawPartitionsExec` now takes numeric ColumnIDs, and column name to ID validation is done during LP to EP materialize call.
3. `__name__` filter is transformed into the right filter if the dataset metricColumn is not __name__

feat(query,coordinator): Special __col PromQL filter for target column name

---

core/src/main/scala/filodb.core/query/RangeVector.scala
memory/src/main/scala/filodb.memory/data/OffheapLFSortedIDMap.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala

Locks may be released on a different thread than the one it is acquired in.
Locks are released on same thread as the are acquired. Acquisition happens when iterator consumption begins. Release is done immediately after that on the same thread.

Release ChunkMap locks on acquisition thread

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
memory/src/main/scala/filodb.memory/data/ElementIterator.scala
memory/src/main/scala/filodb.memory/data/OffheapLFSortedIDMap.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala

We filter out Range Vectors that are returned by the index, but do not have any data in memory. In order to do that we do a hasNext in the query data pipeline setup phase itself. This can cause unreleased locks in some cases. 
There is one other place where we materialize a SerializableRangeVector, and needs to be protected with the lock release logic.
Fix is to check if nonEmpty using a different chunk iterator than the one used to iterate through the data. We release lock for that check immediately.

bug(core): Remove more eager iteration by ChunkIterators

---

coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala

A simple refactor where `count` can replace `filter(...).size` (based on 
- ~[ ] Tests for the changes have been added (for bug fixes / features) ?~
- ~[ ] Docs have been added / updated (for bug fixes / features) ?~

refactor(coordinator): replace filter.size with more concise count

---

jmh/src/main/scala/filodb.jmh/IngestionBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
run_benchmarks.sh

Two benchmarks are added - a much more realistic 100-record container ingestion benchmark, and a combined ingestion+querying benchmark.  Before, the IngestionBenchmark only benchmarked very small portions of ingestion, such as comparing a BinaryRecord to existing partitions.  This is the first benchmark that comprehensively covers ingesting multiple records, dealing with write buffer flushing, memory allocations, etc.
Current numbers on my 2017 MBP:
```
[info]  26.8%  26.8% filodb.core.binaryrecord2.RecordContainer.consumeRecords
[info]  16.3%  16.3% filodb.memory.format.BinaryAppendableVector$mcJ$sp$class.addVector$mcJ$sp
[info]  14.7%  14.7% com.kenai.jffi.Foreign.allocateMemory
[info]  14.6%  14.6% …
```

feat(jmh): 100-record container ingestion benchmark; query+ingest benchmark

---

README.md
cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
coordinator/src/test/scala/filodb.coordinator/ReassignShardsSpec.scala
coordinator/src/test/scala/filodb.coordinator/ShardManagerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
doc/sharding.md
filodb-dev-start.sh
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala

When shard errors out, it stays in error state. We do not automatically restart the shards.
When shard results in in IngestionError event, ShardManager attempts to reassign it another node. Reassignment is attempted only if last reassignment is more than 2 hours earlier. This is so that we do not keep bouncing the shard for errors which are more related to data, than the node itself.
Fixed a possible bug that existed in code on race condition between IngestionStopped vs. MemberDown event that would be exacerbated with the automatic reassignment feature. When member goes down, all shards …

feat(coord): Automatically Reassign error shard

---

core/src/main/scala/filodb.core/query/RangeVector.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/util/IndexedArrayQueue.scala
run_benchmarks.sh

Fixed following bugs/optimizations:
* fixed QueryAndIngestionBenchmark to not ingest same timestamps
repeatedly and cause out of order samples and contention in
out-of-order samples counter
* Array.size replaced with Array.length. There is a hot code path
method due to ArrayOps$ofRef object allocation for each size() call.
* BinaryJoinExec used function references with primitive args which
causes boxing for each sample.
* Seq.foreach with the closure's last function returning long strangely
causes boxing of the Long
* run_benchmarks automatically creates JFR file

bug(query): Some query optimizations to remove top allocation

---

coordinator/src/main/scala/filodb.coordinator/client/NodeCommands.scala
coordinator/src/test/scala/filodb.coordinator/ShardMapperSpec.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/memstore/BitmapIndex.scala
core/src/main/scala/filodb.core/memstore/PartitionSet.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
memory/src/main/scala/filodb.memory/Block.scala
prometheus/src/main/scala/filodb/prometheus/ast/Expressions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala

This pull request fixes the minor typos/misspells detected by https://github.com/client9/misspell
- [-] Tests for the changes have been added (for bug fixes / features) ?
- [ -] Docs have been added / updated (for bug fixes / features) ?
```
$ find . -name *.scala | xargs misspell
./coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala:165:76: "levle" is a misspelling of "level"
./coordinator/src/test/scala/filodb.coordinator/ShardMapperSpec.scala:189:83: "transitionable" is a misspelling of "transitional"
./coordinator/src/main/scala/filodb.coordinator/client/NodeCommands.scala:80:69 …
```

misc: Correct typo/misspell in scaladocs, test suites

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordComparator.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Column.scala
core/src/main/scala/filodb.core/metadata/SimpleComputations.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/StandaloneMultiJvmSpec.scala

In metadata query results, we were assuming that partKeys returned was
always a map. This is not necessarily true.
* Partition Keys can now be sent across as a binary record column.
* The schema of the binary record column is sent in separately
as part of the ResultSchema object itself.
* RecordSchema now also includes column names so that client can
string/mapify the binary record that is returned in results
* Fixed isses in metadata API which returns partition keys.
We dont assume that it is a map now.
Has changes in RecordSchema object. May not be able to do …

feat(core, query): Full support for BinaryRecordColumn

---

cassandra/src/main/scala/filodb.cassandra/metastore/IngestionConfigTable.scala
cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/BaseActor.scala
coordinator/src/main/scala/filodb.coordinator/FilodbCluster.scala
coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeGuardian.scala
coordinator/src/main/scala/filodb.coordinator/NodeLifecycleStrategy.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/NodeClusterSpec.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/NodeClusterSpecMultiJvmNode3.opts
coordinator/src/test/scala/filodb.coordinator/FilodbClusterNodeSpec.scala
coordinator/src/test/scala/filodb.coordinator/FilodbClusterSpec.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/SupervisorSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
http/src/test/scala/filodb/http/ClusterApiRouteSpec.scala
project/FiloBuild.scala
project/FiloSettings.scala

Currently we are using Akka Cluster's auto-downing in several places, which is really not recommended for production and also leads to split brains with each side not coming down.
1. Switch to use akka-cluster-custom-downing provider, with a default strategy of majority-quorum.  The default settings cause the minority side to shut itself down automatically, thus preventing a lingering split brain situation, and leading to smooth resolution of split brains.
2. Switch to Akka's CoordinatedShutdown sequence instead of our custom one.  Add hooks for shutdown of the memstore, etc.  One …

feat(coordinator): Custom downing provider and CoordinatedShutdown for split brains

---

core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

For now we just transform the Long values to Doubles.  Future Chunk-based iterations will take advantage of faster methods.
One can query raw data from non-Double columns but cannot run any non-raw queries.
Non-raw queries from Long columns are now possible.

feat(query): Add support and tests for querying from LongColumns

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

No of values returned by Mosaic are more than Prometheus are more for Aggregate Functions (Sum, Count,Max, Min,Avg 
Sum, count and avg has value 0, max has value as -1.7976931348623157E308 and min has 1.7976931348623157E308 when no data point is available for the instant
Removed values from result when no data point is available for that instant
None

bug(query): Aggregate results were wrong when no data points are available for the instant

---

README.md
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
jmh/src/main/scala/filodb.jmh/IngestionBenchmark.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/main/scala/filodb.memory/data/OffheapLFSortedIDMap.scala
memory/src/test/scala/filodb.memory/data/OffheapLFSortedIDMapTest.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/SlidingWindowIteratorSpec.scala

Currently new data samples are appended as they are.  During query time, out of order samples are dropped in an iterator.
A new field, `lastTime` is added to the `TimeSeriesPartition`.  During ingestion, timestamp of new sample is compared with lastTime and dropped if it is less than lastTime.  A new counter keeps track of dropped samples.
The iterator which dropped out of order samples is skipped during query.
Before:
```
[info] Benchmark                                Mode  Cnt     Score    Error  Units
[info] QueryInMemoryBenchmark.parallelQueries  thrpt   30  1347.586 ± 27.054  ops/s …
```

 feat(core, query): Drop out of order samples at ingestion time, not query time

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala

Fix the assumption that PartitionKey will have only one column of type MapColumn, while serving the Label queries. With the fix, TimeSeriesParition will be decoded based on the PartitionKeySchema

fix(query): fix the assumption that PartitionKey will have only one column of type MapColumn

---

README.md
coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordContainer.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/WriteBufferPool.scala
core/src/main/scala/filodb.core/query/PartitionTimeRangeReader.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
doc/query-engine.md
jmh/src/main/scala/filodb.jmh/BasicFiloBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
memory/src/main/scala/filodb.memory/data/OffheapLFSortedIDMap.scala
memory/src/main/scala/filodb.memory/format/vectors/DeltaDeltaVector.scala
memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/main/scala/filodb.memory/format/vectors/IntBinaryVector.scala
memory/src/main/scala/filodb.memory/format/vectors/LongBinaryVector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala
memory/src/test/scala/filodb.memory/format/vectors/LongVectorTest.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/LastSampleFunctionSpec.scala
query/src/test/scala/filodb/query/exec/SlidingWindowIteratorSpec.scala
query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Currently almost all queries (except raw ones) use the `SlidingWindowIterator` for windowing operations.  It goes through every "row" in each Time series, spanning the first row of the earliest time window to the last row of the last time window, regardless of the step size or window length.  This works but does not take advantage of various optimizations that are possible with columnar layout.
This PR introduces a couple new classes/concepts:
- A `ChunkedWindowIterator` which gives the parameters of each window plus each applicable chunkSet within that window, instead of a sliding …

feat(memory, core, query): ChunkedWindowIterator for up to 7.5x faster queries

---

gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala
gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala
prometheus/src/main/scala/filodb/prometheus/FormatConversion.scala

Labels `__name__` and `app` are being used as sharding key.
Labels `__name__` and `_ns` will be used as sharding key.

misc(prometheus): Update sharding key to use "_ns" instead of "app"

---

.gitattributes

During git merge across branches, even version.sbt is getting merged.
Adding .gitattribute to avoid merging version.sbt file.

misc(git): Avoid merging version file during git merge

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

Unit Test for validating the failure while extracting time buckets from cassandra. This is causing SEGV errors while instance restarts. It is happening if the schema has multiple string partition columns.

misc(core): unit test for testing extractTimebucket with multiple string partition columns

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

Currently when input has NaN, topK returns range vector  with _name_ as null and all samples with value -1.7976931348623157E308  and bottomK returns range vector  with _name_ as null and all samples with value 1.7976931348623157E30 
Result does not have the range vector with name as null and sample values as -1.7976931348623157E308 / 1.7976931348623157E308

bug(query): fix bug in topK and bottomK for NaN values

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
query/src/main/scala/filodb/query/QueryConfig.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala

Apply limit on total number of samples returned from query or sub-query instead
of sample limit per range vector paired with limit on number of range vectors.
New approach allows us to query high cardinality metrics across smaller time ranges.
This is necessary for query-based pre-aggregation.
It even allows us to query large number of samples for few range vectors.
Earlier approach could not handle these use cases.
Semantics of limit has changed from samples-per-rangevector to total-number-of-samples
Query clients need to raise this limit.

feat(query): Apply limits on total number of samples

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
memory/src/main/scala/filodb.memory/format/RowReader.scala
prometheus/src/main/scala/filodb/prometheus/FormatConversion.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

Metadata Execplan is modified to support querying a subset of label values. Earlier implementation has support for querying single label or all the series labels. With this change, a subset of label values can be queried.

feat(query): support for querying subset of series label values - (series metadata)

---

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala

Query server does not return value present at time: timestamp - staleSampleAfterMs 
Increase window by 1 to include value present at at time: timestamp - staleSampleAfterMs

bug(query): fix bug in ChunkedWindowIterator to include value present at time, timestamp - staleSampleAfterMs 

---

core/src/main/scala/filodb.core/zipkin/Zipkin.scala
project/FiloBuild.scala

There is no support for https zipkin collector endpoint in the oss [kamon-zipkin-reporter](https://github.com/kamon-io/kamon-zipkin/blob/v1.0.0/src/main/scala/kamon/zipkin/Zipkin.scala#L140). Hence had to port the class to support the same.

feat(core): Add https support in Kamon ZipkinReporter

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala

Since mapAsync by default has a parallelism of 1, child plans are being executed sequentially.
Fixing parallelism.

bug(query): Sub queries are being executed sequentially

---

memory/src/main/scala/filodb.memory/format/vectors/DeltaDeltaVector.scala
memory/src/test/scala/filodb.memory/format/vectors/LongVectorTest.scala

…ope=0 and binarySearch called
When `binarySearch` method called on a DeltaDeltaConstVector with slope=0, it throws a DivideByZero exception.
When the slope is 0, for a const vector, that means all values are the same.  If the slope is 0 then what we do is either return the first or last item depending on if the value is higher or lower.

fix(memory): Fix DivideByZero exception when DDV has slope=0

---

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala

NPE was seen in ShardManager when performing the following comparison:
`currentCoord.path.address == sender.path.address`
Essentially means that current coordinator for shard was null, and shard was unassigned, and yet we got a shard event. Could this be from the previous assignee of the shard?
This PR prevents the NPE and failure of the actor and logs the information for further debugging, but we still need to understand how this can happen.
@velvia Can you help verify/confirm that sender.path or currentCoord.path cannot be null too ?

bug(coord): NPE seen in ShardManager when processing shard events

---

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
memory/src/main/scala/filodb.memory/format/vectors/DeltaDeltaVector.scala
memory/src/main/scala/filodb.memory/format/vectors/LongBinaryVector.scala
memory/src/test/scala/filodb.memory/format/vectors/LongVectorTest.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

Multiple bugs in chunked query iteration and binary search of Long/TS vectors are leading to SEGVs and out of bound sum() queries on vectors.
Multiple bugs in binary search and sum calculation are fixed.  Additional debugging is added for bound errors in chunked iteration to confirm a theory: that remaining bugs is due to off-by-1 length errors - it is possible for some vectors to be slightly longer than the official ChunkSetInfo chunk length, and queries should not go over that ChunkSetInfo limit.  Right now if the TS vector is longer than the others than it might return out of bounds …

fix(memory): Fix binarySearch bugs in Long/TS vectors; add more debugging

---

conf/timeseries-dev-source.conf
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
kafka/src/main/scala/filodb/kafka/KafkaDownsamplePublisher.scala

No need to use queues and monix-kafka for downsampling since Kafka producer takes care of the batching. 
To use monix-kafka producer, it is necessary for the message source to be transformed into an Observable. The queues were a workaround for that, but it is not necessary anymore since Kafka driver takes care of the batching.

bug(kafka): Replace monix-kafka usage in downsampling Kafka producer

---

jmh/src/main/scala/filodb.jmh/QueryLeafScanInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/ScanInMemoryBenchmark.scala
query/src/main/scala/filodb/query/util/IndexedArrayQueue.scala
run_benchmarks.sh

* Scan for leaf queries that exclude the higher level aggregation nodes in a query
* Benchmark in latency instead of throughput
* Optimization to move IndexArrayQueue's members as constructor args - gives around 15% reduction in latency
Before
```
[info] Benchmark                                                Mode  Cnt     Score     Error  Units
[info] ScanInMemoryBenchmark.scanSumOfRateBenchmark             avgt   45  6023.666 ± 355.420  us/op
[info] ScanInMemoryBenchmark.scanSumOfRateBenchmark:JFR         avgt            NaN              N/A
[info] ScanInMemoryBenchmark.scanSumOfSumOverTimeBenchmark      avgt   45   465.685 ±  16.946  us/op
[info] ScanInMemoryBenchmark.scanSumOfSumOverTimeBenchmark:JFR  avgt            NaN              N/A
```
After
``` …
```

feat(jmh): Benchmark for Leaf/Scan queries

---

cassandra/src/main/scala/filodb.cassandra/CassandraTSStoreFactory.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala

A StoreFactory for a TimeSeriesMemStore with Cassandra for metadata, but NullColumnStore for
disabling write of chunks to a persistent column store. This can be used in environments
where we would like to test in-memory aspects of the store and ignore persistence and
on-demand-paging.

feat(core): Factory with Cassandra Metastore and Null Column Store

---

core/src/main/scala/filodb.core/downsample/ShardDownsampler.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala

Sometimes timestamp vector can be longer than official chunk length.  Limit range of chunked window queries.
binarySearches based on timestamp vector might return an upper bound that is out of range of other vectors if their lengths are not equal.   (The lengths not being equal is an artifact of how ingestion is capped by write buffers).
Limit the upper bound to the official length of a chunk based on ChunkSetInfo, not the length of the timestamp vector.

fix(query): Limit chunked windowing range to ChunkSetInfo.numRows

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

`chunks-paged-in` metric is changed to counter to capture number of raw chunks paged into memory from datastore.

misc: fix chunks-paged-in metric type to capture counter instead of gauge

---

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartitionSet.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
scalastyle-config.xml

Native memory can be freed too soon, due to various race conditions.
Locks are put in place to ensure that partitions are added/removed in a thread-safe fashion, and finalization is used to safely free the memory occupied by an entire shard. Shard removal is rare, and so delayed reclamation due to finalization isn't much of an issue.

bug(core): Improve safety of freeing native memory.

---

core/src/main/scala/filodb.core/memstore/WriteBufferPool.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala

Num rows in chunk metadata is not reset immediately when it is recycled.  Could be a race condition when reading old chunk metadata
Num rows in chunk metadata is now reset immediately.

fix(core): Reset # rows in recycled chunk metadata for consistent metadata<->vectors

---

akka-bootstrapper/src/main/scala/filodb/akkabootstrapper/ClusterSeedDiscovery.scala
coordinator/src/test/scala/filodb.coordinator/ActorSpecConfig.scala

Test suite for coordinator fails randomly, because the Akka port cannot be bound again right away.
Added a sleep before the ActorSystem is crated, top hopefully provide enough allowance for the bind to work.

feat(coordinator): Fix port binding issue when running tests.

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala

One of the recent changes to execute child plans in parallel with mapAsync(numProcs) has caused regression in Binary Join. Since LHS and RHS results can arrive different order, results are sometimes incorrect.
Keep track of original order of execplan nodes and use them while composing the results.
Requires redeployment of clients using the Query planner since new ExecPlan nodes are used.

bug(query): Binary Join sometimes results in incorrect results

---

memory/src/main/scala/filodb.memory/format/vectors/DeltaDeltaVector.scala

…at was out of bounds
Occasionally a binary search was failing the randomized property testing.
The DeltaDelta vector binary search function had a bug as it was reading memory that was out of bounds.  Added a bounds check.  Randomized testing no longer fails.

fix(memory): Fix bug where binarySearch of DDVs was reading memory out of bounds

---

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala

Fix to accurately capture the latency for On Demand Paging of RawChunks. Span is created only if there are partitions that needs to be paged-in from datastore.

misc: fix for On Demand Chunk page-in span

---

prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Instant queries used a smaller dummy step that would not pass validation in PeriodicSamplesMapper.

bug(prometheus): Use a bigger dummy step for instant queries

---

coordinator/src/test/scala/filodb.coordinator/FilodbClusterNodeSpec.scala
coordinator/src/test/scala/filodb.coordinator/ShardSubscriptionsSpec.scala

We use a long timeout to reduce failures between tests that run Akka Cluster on a port.
Randomize the port used by Akka Cluster in key tests.  Timeout should not be needed anymore.

fix(coordinator): Use random Akka port in some tests to reduce failures

---

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala

…InputRecord preserves old hash calculation
The recent end-to-end Histogram change changed the calculation of the hash inside a PartitionKey.  Namely, for map columns, instead of separately computing hashes for keys and values in a complex API, it greatly simplifies the API by calculating the hash just one time for maps.  This hash is used for comparing new incoming records against existing ones and other purposes.
Creates an option for endMap() to disable the one-time hash calculation if users want to use the old method of computing hashes.  The old method is preserved in the …

fix(core): option to disable new endMap() bulk hash calculation; preserve old PromInputRecord calc

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb.coordinator/queryengine/Utils.scala
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala
prometheus/src/main/scala/filodb/prometheus/ast/Base.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/HistogramQuantileMapper.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/RowKeyRange.scala
query/src/main/scala/filodb/query/exec/StitchConcatExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/StitchConcatExecSpec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
stress/src/main/scala/filodb.stress/MemStoreStress.scala

If spread for a namespace/application changes over time, and query spans the time when the spread changed, we get two range vectors with same key that could possibility overlap in time depending on how ingestion is done. This can cause incorrect query results, affects join functionality and aggregation, time window result calculation etc.
**New Expectations from Gateway**
1. Require that spread changes be scheduled by the gateway for a specific time in the future to prevent overlap of the same time series on two shards.
2. Require that gateway ingest NaN into old shard to prevent staleness feature that "holds" a value for five minutes and can produce wrong aggregations.
1. spreadFunc in QueryOptions now receives all …

 feat(query): Handling spread changes over time in Query Engine - Iteration 1

---

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala

Value present at time: timestamp - staleSampleAfterMs is not returned
Increase window by 1 to include value present at at time: timestamp - staleSampleAfterMs

bug(query): fix bug in PeriodicSamplesMapper to include value present at time, timestamp - staleSampleAfterMs

---

coordinator/src/main/scala/filodb.coordinator/client/FiloKryoSerializers.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala

Only shard number is included in result range vector
if "verbose" option is enabled as query parameter 
* partId is included in range vector result
* partId and shardNum is included

feat(query): Include partId in query result on verbose option

---

prometheus/src/main/scala/filodb/prometheus/ast/Operators.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/binaryOp/BinaryOperatorFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/BinaryOperatorSpec.scala

Support for comparison operators. 
It allows comparisons between 
1. Two vectors
[sum(sum_over_time(my_gauge{_ns=\"AppName\"}[5m]))   > sum(count_over_time(my_gauge{_ns=\"AppName\"}[5m]))]
2. Scalar and Vector 
[sum(sum_over_time(my_gauge{_ns=\"AppName\"}[5m])) > 10))
Also support for the bool modifier 
[sum(sum_over_time(my_gauge{_ns=\"AppName\"}[5m]))  > bool 10

feat(query):Support for comparison operators

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala

Count does not return value when all values on a shard are NaN
In reduce add input value to CountHolder only when it is not NaN

bug(query): fix bug in Count to add input value in reduce only when it is not NaN

---

README.md
core/src/main/scala/filodb.core/metadata/Column.scala
core/src/main/scala/filodb.core/metadata/ComputedColumn.scala
core/src/main/scala/filodb.core/metadata/Dataset.scala
core/src/main/scala/filodb.core/query/KeyFilter.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/metadata/ColumnSpec.scala
core/src/test/scala/filodb.core/metadata/DatasetSpec.scala
spark/src/main/scala/filodb.spark/TypeConverters.scala

Currently, the only way to distinguish different columns besides the name is the columnType attribute.  There is no way to annotate, for example, if a DoubleColumn is a counter or a gauge.
This PR adds the capability to add one or more key=value attributes to a Column definition.  They can be added at definition time like this:
value:double:counter=true
timestamp:ts:interval=10
The attributes are made available as a new params field in the Column trait and properly serialized in the column and dataset definitions.  Old column definitions are still backwards compatible and parse to empty …

feat(core): Add key=value optional parameters to each Column definition

---

conf/logback-dev.xml
conf/timeseries-dev-source.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
project/FiloBuild.scala
query/src/main/scala/filodb/query/exec/HistogramQuantileMapper.scala

We were assigning duplicate partId when an evicted partKey starts re-ingesting. When this partKey is queried, ODP causes corruption of the shard data structures since partSet cannot hold duplicate TimeSeriesPartition objects for same partKey.
Prior to creating a new partition in the ingestion pipeline, the idea here is to convert the partKey from ingestion record to a Seq[ColumnFilter], essentially a Lucene query and look up matching partIds (typically just zero or one). If one is found, use the partId. If more than one is found, then it means that there is another PK that includes the …

feat(core): Correct support for intermittently publishing time series

---

core/src/main/scala/filodb.core/zipkin/Zipkin.scala

Zipkin message batch size is 5mb today. This sends more spans in a single request, adding load on zipkin collectors.
Reduce the zipkin message batch size to 128kb. I do not think it should be part of a config at the moment. We will add it to config later if required.

misc(core): Reduce zipkin message batchsize

---

coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
coordinator/src/test/scala/filodb.coordinator/ShardManagerSpec.scala

There is a missing broadcast of snapshot after updateFromExternalShardEvent. Added missing step.
Acknowledgement to @broneill for discovering this missing step.

bug(coord): Send missing snapshot message on updateFromExternalShardEvent

---

README.md
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

Adds the ability to do sum() over HistogramColumn range vectors.
Monotonicity correction and ability to sum histograms of different schemas is also added for proper histogram summing functionality.

feat(query): Histogram sum() over RangeVectors

---

core/src/main/scala/filodb.core/zipkin/Zipkin.scala

Added following two configs:
```
kamon.zipkin.max.requests
kamon.zipkin.message.max.bytes
```
Also, updated default values for those 2 configs as follows:
```
kamon.zipkin.max.requests=128
kamon.zipkin.message.max.bytes=256kb/s
```

misc(core): Make zipkin message maxBytesOut configurable

---

cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

If earliestTime in memory for a partition is more than queryStart time, we decide to page from cassandra.
We page from cassandra only if Lucene index indicates that partition's startTime is earlier than the earliest time in memory, and the query is for earlier than the earliest time in memory.
The code organization for ODP imo has been less than ideal because there is a lot of things happening and leak in abstraction with non-functional side effects. I do understand everything has been done to reduce object allocation and double iteration of objects. I haven't really changed all of that, …

bug(core): ODP from Cassandra only if Lucene index indicates that there is data

---

query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

- Reset function returns 0 instead of NaN for no-data windows
- fix is to return NaN when there are no samples for a time window

bug(query): resets function returns zero instead of NaN for empty window

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/resources/filodb-defaults.conf
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

The setup of each query, including `scanPartitions`, Lucene partId lookup, and setting up RangeVectorTransformers, happens single-threaded in the Actor receive loop's threadpool.   The overhead of this setup being run in serial can be significant.
1.  The `ExecPlan.execute` method is run entirely inside of a Monix Task, including all setup, `scanPartitions`, etc.  This means these tasks can now be parallelized and execute outside of the Actor loop.
2. All of the QueryEngine tasks and Observables are now run in a separate, configurable threadpool, named query-<dataset>.  This will make it …

 feat(query): Parallelize scanPartitions and all QE work in query threadpool

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala

SplittableRandom isn't thread-safe.
ThreadLocalRandom is thread-safe and uses the same algorithm as SplittableRandom.

bug(coordinator): Use a thread-safe random number generator for dispatcher selection.

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala

We attempt to create a TimeSeriesPartition for every partKey in cass index time buckets.
With this reverse lookup of partKey to partId could also be done using partSet.
This was ok for 3 day retention given most partitions are ingesting, but does not scale for long term retention where majority of partitions are not ingesting. If left as is, it would lead to eviction of nodes from the beginning. 
* We now have a new partKey->partId on heap map which is used for reverse lookup.
* we create a TimeSeriesPartition object only for currently ingesting partitions.
* We load time buckets in reverse order since we know that last record wins. This way lucene documents do not need to be updated.
The goal of the PR is to
* Reduce …

feat(core): Optimize index recovery for long term retention

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala

A recent bug fix to send snapshots for missing shard events resulted in publish of too many snapshots especially for RecoveryInProgress events.
This caused flooding of events on NodeClusterActor, and non responsive HTTP cluster status calls.
This also brought to surface some bugs where we were accessing actor context from async thread.
* Dont send snapshot on RecoveryInProgress events
* Save context.parent on IngestionActor startup and use that instead of context.parent from future thread.

bug(coord): Remove publish snapshot for RecoveryInProgress

---

README.md
cli/src/main/scala/filodb.cli/CliMain.scala

--limit is supposed to be a user-specified cap on the amount of output.  Right now, `--limit` is very low and acts as a cap on the number of output samples.  If this is not high enough, the query fails with an exception, which is counter intuitive.
Now the `--limit` only limits the amount of output returned, namely the number of RangeVectors.   Changing the limit does not affect whether the query succeeds or not.
A much higher `sampleLimit` is passed in so that queries will succeed by default, but users can use --limit to limit the CLI output.

fix(cli): Make --limit actually behave like a user specified output limit

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/TransientRow.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

They were caused by some type misalignment.  Now everything in aggregations is a HistogramWithBuckets.
Exceptions seen such as 
```
error='java.lang.ClassCastException: filodb.memory.format.vectors.Histogram$$anon$1 cannot be cast to filodb.memory.format.vectors.HistogramWithBuckets
at filodb.query.exec.HistSumRowAggregator$.reduceAggregate(AggrOverRangeVectors.scala:339)
at filodb.query.exec.HistSumRowAggregator$.reduceAggregate(AggrOverRangeVectors.scala:322)
at filodb.query.exec.RowAggregator$class.reduceMappedRow(AggrOverRangeVectors.scala:237)
at …
```

fix(memory, query): Fix exceptions in Histogram summing

---

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala

The QueryEngine has access to NodeCoordinatorActor.shardMaps via a callback function. Different threads can be accessing this map concurrently.
Use a thread-safe hash map.

bug(coordinator): Fix thread safety issue with sharing of ShardMapper instances.

---

prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

**Summary**
* Now allow metric name to be provided as a tag in promQL. Queries such as `{__name__="foo", baz="boo" }` are supported.
* Allow special characters in tag values. This allows possibility of special characters in metric names too.

feat(query): Allow metric name as tag in promQL; Allow escape chars in tag values

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
core/src/main/scala/filodb.core/store/package.scala

While researching how to implement time bucket based chunk persistence I noticed that we have some unused code which was confusing me. I'm removing it.

misc(core): Remove code for old chunk id encoding format.

---

coordinator/src/multi-jvm/scala/filodb.coordinator/NodeClusterSpec.scala
coordinator/src/test/scala/filodb.coordinator/FilodbClusterNodeSpec.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala

Map was used instead of foreach on an iterator. Hence the iterator was not being consumed at all yielding no results.
Fix was confirmed by running MemstoreCassandraSinkSpec which was failing prior to this fix.

bug(core): fix startTimeFromPartIds regression

---

core/src/main/resources/filodb-defaults.conf

Better default buckets for Kamon-prometheus.  Larger range for time tracing and more buckets for other histograms.

feat(config): Better default buckets for Kamon-Prometheus

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala

Output has RangeVector with metric even when there are no rows present
```
{
"metric": {
"job": "Test-data-1554428389670",
"instance": "inst-8",
"service": "service-9",
"_ns": "Test-data-1554428389670",
"code": "566",
"version": "3.1.86",
"__name__": "my_counter",
"mode": "user"
},
"values": [
]
}
```
Remove range vectors which don't have any values
```
{
"status": "success",
"data": {
"resultType": "matrix",
"result": [
]
}
}
```

bug(query) : comparison operator returns metric even when no values are present

---

memory/src/main/scala/filodb.memory/format/NibblePack.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/NibblePackTest.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala

Adds support for a new BinaryRecord `BinaryHistogram` type with custom bucket definitions, needed to support Prometheus style histograms.   The custom bucket definitions are compressed using NibblePack XOR-based double compression.

 feat(memory): CustomBuckets: ingest/serialize histograms with custom bucket def

---

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeGuardian.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
http/src/test/scala/filodb/http/ClusterApiRouteSpec.scala

On a "spare node", no QueryActor is set up thus users get UnknownDataset errors.
If there is no QueryActor set up, then the query is forwarded to a random shard using the ShardMapper in the NodeGuardian.

 fix(coordinator): Forward query messages to random shard coordinator

---

README.md
conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
kafka/src/main/scala/filodb/kafka/TestConsumer.scala

- Filter for `TestConsumer` to dump out raw Kafka ingestion records when a string partition key field matches a given value
- A new dataset/store config that when enabled allows detailed logging of each sample ingested when the partition key has fields matching the config

feat(core,kafka): Detailed ingestion logging for matching subset of records

---

conf/logback-dev.xml
coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala
core/src/main/resources/filodb-defaults.conf

Profiling shows a lot of time spent in String.intern (15%), and this is due to reflection lookups. The reflection lookups are caused by Kryo, which is generating tracing and debug messages. Even though they're filtered out from the log, the only way to prevent generation of these messages is to modify a special minlog field.
I couldn't find a config setting that can change the minlog field, so I set it to WARN in the customize method. I also updated some config settings which might have an effect, but by themselves they don't appear to do much.

misc(conf,coordinator,core): Reduce overhead of Kryo debug/trace logging.

---

memory/src/main/scala/filodb.memory/format/vectors/DeltaDeltaVector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala

An edge case in Delta-Delta encoding causes the following value sequence (a, b, b, b...... b) to be encoded incorrectly as a ConstDeltaDelta.  Basically the min and max delta is only sought for the second and subsequent values.
However, even if the first value was included the const delta delta might not have been correct either.
Only if the min and max delta == 0, that is all values are exactly on the sloped line, is Const encoding used.

fix(memory): Fix edge case for DDV encoding where first value != the rest

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala

Recovery of one bucket was missed due to use of `until` instead of `to` when iterating buckets.
I wish we had some unit tests which could catch this kind of an error. However, the indexing population and recovery is too coupled with flushing/ingestion logic that unit testing becomes very difficult. I am very open to suggestions and if there are any ideas, I will take unit testing up in a separate PR.

bug(core): Including missed time bucket during index recovery

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

If value exists at timestamp t1 and topk query is fired for time (t1-500) to (t1+500), value at t1 continues till t1+500.  Value at t1 should be there only till t1 + staleSampleAfterMs which is 300 by default. This happens because row is not reset and previous value is carried over.
Reset remaining values of row to overwrite previous row value

bug(query): topk and bottomk has trailing value 

---

coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala

Shard status tags did not have dataset tags. Shard stats were not being reported for clusters with multiple datasets.

bug(core): Shard status metrics did not have dataset tags

---

coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala

Second part of the fix to move dataset from metric name to tag.

bug(core): Shard metrics has dataset in metric name instead of tag

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

We saw during testing that an intermittently ingesting partition which didnt ingest for retentionPeriod and then ingests could be purged prior to data being flushed because we dont check if unflushed data. 
Check if there are unflushed chunks prior to deleting the partition
Also using TermInSetQuery instead of batching - it is more efficient and uses less memory.

bug(core): Not purging partition if it has unflushed data

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

Non-Ingesting partitions are not added to evictedPartKeys BloomFilter during index recovery.
Hence if partition re-ingests, it is not found in bloom filter and we never do index lookup thereby creating another partId for same partKey. This state results in duplicate time series in results.
Add non-ingesting partKey into bloom filter at index recovery time

bug(core): Add non-ingesting partKeys to evictedPks BloomFilter during index recovery

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala

By default partition should not have ingesting = true.
Reason: ODPed partitions will have ingesting = false.
ingesting = true should be set only in the ingestion pipeline when data is seen.

bug(core): By default partition should not be ingesting

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala

When starting the recovery task, any exception (like failing to read from Cassandra) is uncaught. This means that the shard state can be stuck in an assigned state for a long time.
Catch the exception and handle it like any other shard error. This then reports an error to the status actor.

bug(coordinator): Exceptions when starting ingestion, but before the recovery task begins, should be caught and handled.

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/WriteBufferPool.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

The `WriteBufferPool` allocates more WriteBuffers from native memory upon request.  When a surge of TSPartitions dies down however, and the WriteBuffers are released and returned to the pool, the memory is never released.  The pool retains a very large number of unused WriteBuffers. After a while, we run out of WriteBuffer memory, and this condition does not change.
There is a new `max-buffer-pool-size` setting.  When the `WriteBufferPool` is at this size, any buffers that are returned are released back to native memory instead of being retained in the pool.  This allows the native …

feat(core): Return extra WriteBuffer memory back for reuse

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

SEGVs have been observed from the bloom filter, and one possible cause is concurrent shutdown. Only the ingestion thread is expected to access it, but shutdown can run from another one.
Guard all access with a synchronized block. This won't affect performance because the bloom filter isn't accessed that often, and it's almost always from the ingestion thread. There's no contention.

bug(core): Guard access to the evicted partition keys bloom filter, to prevent it from being freed concurrently.

---

core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
memory/src/main/scala/filodb.memory/data/ChunkMap.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

Add execPlan as debug information to concurrent hash map when obtaining lock, and clear it along with release of lock.
If there are remnant locks and we aren't able to acquire write lock for long time, we dump the execPlans which stay for long to the log and, most importantly, shutdown the node so that ingestion on shard is not stuck.
**The debugging should be removed in a subsequent PR, hopefully, before we push to integration branch.**

feat(core,query): Debug queries that dont release lock; shut down node with stuck shard

---

cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionIndexTable.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala

Two bug fixes:
* partitionGroups is modified by ingestion thread and read at same time in flush thread. Fix with copy-on-read for other thread.
* PartitionIndex records are being read with default fetch size of 5000. This may cause read timeouts because each row is 1MB in size.

bug(core,cass): partGroups bitmap concurrency; fetchSize for partIndex

---

coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala
coordinator/src/test/scala/filodb.coordinator/ShardMapperSpec.scala

Logs are event-based, after each member is removed or added.  This makes it especially difficult to figure out what the current state is at the startup of a new Singleton.
A easy-to-read ShardMapper snapshot for each dataset is logged at multiple points of NCA startup: right after recovery of the map, and after the current Akka Cluster state is received and stale coordinators removed.   It looks like this:
```
Status legend: U=Unassigned N=Assigned A=Active E=Error R=Recovery S=Stopped D=Down
----- Status Map-----
0-  15   ..AAR...  ........
16-  31   ........  ........
----- …
```

debug(coordinator): Log easy-to-read snapshot of entire ShardMapper at NCA startup

---

core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

* Use part.ingesting flag instead of earlier condition to check if partition is eligible for purge
* Return Exception with better error message than NPE when shard is not present on node

bug(core): Use ingesting flag to identify partitions to not purge

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

Some corruption has been observed with the the group bitmap data structures. This is one possible cause.
The flush done tasks are run from the ingestion thread, which is safe and correct.

bug(core): The flush done tasks must be run from the ingestion thread.

---

README.md
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/scala/filodb.core/TestData.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
query/src/main/scala/filodb/query/exec/TransientRow.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/InstantFunction.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala

The `histogram_quantile` function follows the one from Prometheus - quantiles are estimated by linear interpolation between buckets, except for the last bucket where the top bucket is +Inf, so values are clipped at the 2nd-to-last bucket "le".
With a supplementary "max" value, which is the maximum value recorded in the client for a histogram, we introduce an innovative `histogram_max_quantile` function which is able to deliver higher accuracy quantiles.
- When the max value is beyond the 2nd-to-last (before +Inf) bucket, instead of just clipping the quantile, we are able to interpolate …

feat(memory, query): histogram_max_quantile - more accurate top quantiles

---

core/src/main/resources/filodb-defaults.conf

Without providing an empty default spread-assignment in filodb-defaults.conf, QueryActor is failing.

fix(core): Add an empty spread-assignment in filodb-defaults.conf

---

http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala

Travis fails sometimes when number of shards are 8 in PrometheusApiRouteSpec
Reduce no of shards to 4

fix(query) : Reduce no of shards in unit test case

---

core/src/main/resources/filodb-defaults.conf
http/src/main/scala/filodb/http/HttpSettings.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala

Actor Asks originating from HTTP API are using 30s timeout. 
Actor Asks originating from HTTP API use query timeout in configuration.
Default ask time out increased to 2 minutes

bug(http): Fix ask timeout values in http promql api

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala

All aggregations happen at one level, no matter how many shards the query touches.
If the metric touches more than a threshold number of shards, we do aggregations at multiple levels.

feat(query): Multi-Level aggregation for queries touching many shards

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala

- x] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
Lock bugs logger should be higher than current debug level. Using error.

bug(memory): ChunkMap lock logger should be at higher level

---

README.md
cassandra/src/main/scala/filodb.cassandra/metastore/CassandraMetaStore.scala
conf/timeseries-128shards-source.conf
conf/timeseries-dev-source.conf
conf/timeseries-standalonetest-source.conf
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/TestData.scala
doc/ingestion.md
filodb-dev-start.sh
memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala

Counter drop detection is not enabled; thus any drops will not be detected properly.
CLI --init command does not work from clean C* setup
`counter=true` added to dataset config everywhere so counter drop detection is enabled.
Bug fixed so that MetaStore for C* will initialize missing key spaces correctly.
Also, the obsolete -s option to `filodb-dev-start` was removed.

fix(conf,cassandra): Enable counter drop detection by default; fix C* metastore init

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/test/scala/filodb.core/memstore/DemandPagedChunkStoreSpec.scala

Looks like executeOn causes subsequent map/foreach lambdas to run on the specified executor than the default one assigned for the whole pipeline. Call to `asyncBoundary` is needed to fix this.

bug(core): Queries have been executing in ingestSched

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/test/scala/filodb.core/memstore/DemandPagedChunkStoreSpec.scala

Revert previous change to run populateRawChunks in query thread.
This caused problems since BlockManager was not thread safe.

bug(core): Revert synchronous run of populateRawChunks

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala

Looking at a heap dump I noticed way too many logger instances, referenced by TimeSeriesPartition instances.
ChunkMap relies only on a global logger instance again.

regression(memory): Rely on global logger instance again.

---

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala

`histogram_max_quantile` errors out with a NotImplementedError due to mismatched output schema
The output schema now matches that returned by `histogram_quantile` from histogram columns.

fix(query): Fix output schema of histogram_max_quantile function

---

coordinator/src/main/scala/filodb.coordinator/GlobalConfig.scala
kafka/src/main/scala/filodb/kafka/KafkaIngestionStream.scala

Ingestion operations were happening on monix-io scheduler
Remove monix-io scheduler

bug(coord): Monix-io threadpool used in ingestion

---

doc/compression.md
jmh/src/main/scala/filodb.jmh/HistogramIngestBenchmark.scala
memory/src/main/scala/filodb.memory/format/NibblePack.scala
memory/src/main/scala/filodb.memory/format/Ptr.scala
memory/src/main/scala/filodb.memory/format/Section.scala
memory/src/main/scala/filodb.memory/format/UnsafeUtils.scala
memory/src/main/scala/filodb.memory/format/WireFormat.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramCompressor.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/NibblePackTest.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala
project/FiloBuild.scala

Two new encoding schemes for Prom-style increasing counter based fixed bucket histograms:
- "2DDelta", using delta compression along both axes
- "SectDelta", a delta scheme relative to start of each section, much faster for reading
Some explanation of scheme in README as well, plus tests, benchmarks, and compression utilities.

feat(memory): delta encoding for increasing/Prom histograms

---

core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

System does not log or meter events when kafka offset to recover from is not available.
Log and meter events when kafka offset to recover from is not available. Indicates potential data loss.

feat(core): Log and meter events when kafka recovery drops data

---

core/src/test/resources/application_test.conf
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

`histogram_max_quantile(...., sum(....))` would return no results for certain time ranges.
This was due to a bug in aggregation where NaN was not compared correctly, leading to NaN results which would get filtered out.
Comparison is fixed and new tests added.

fix(query): histogram_max_quantile: fix NaN bug for proper aggregations

---

memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
query/src/main/scala/filodb/query/exec/TransientRow.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

Fixes a bug where histogram_max_quantile on raw data was not reporting correct max.
the max column value was not being passed onto the TransientRow properly because the LastSample function ignored it.  Created a new histogram-with-max based last sample function.

fix(query): Correctly extract max column for LastSample + histogram_max_quantile

---

conf/timeseries-dev-source.conf
coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeGuardian.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
coordinator/src/test/scala/filodb.coordinator/SupervisorSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/test/scala/filodb.core/TestData.scala
http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala

* Most multi-JVM tests and a few coordinator tests are disabled as they are deemed "flaky".
* A race condition exists where during NCA setup, the subscription to the ClusterActor for shard map updates happens after shard assignment, so the QueryActor does not get a good initial shard map and is not able to process queries for a while
* Tests use a flaky method of having to send a special message to NCA to set up a dataset, instead of initializing like the app actually does
* NCA constructor code is fed the wrong "Config" from the Guardian so that often during initialization no datasets are set up
**New …

feat(coord): Fix tests and some dataset config/initialization bugs/races

---

cassandra/src/main/scala/filodb.cassandra/CassandraTSStoreFactory.scala
conf/timeseries-filodb-server.conf
coordinator/src/main/scala/filodb.coordinator/FilodbCluster.scala
coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeClusterActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeConfiguration.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/StoreFactory.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/FiloSchedulers.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
kafka/src/main/scala/filodb/kafka/KafkaSettings.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
standalone/src/multi-jvm/scala/filodb/standalone/ClusterSingletonFailoverSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/IngestionAndRecoverySpec.scala

Currently there is a lot of confusion and un-clarity and risk of bugs because what operation executed on which thread pool does not stand out so much so that it is almost impossible for a new developer to confidently change code without risking introducing new issues with concurrency.
This is an interim solution for introducing cleanliness, clarity and maintainability by clearly conveying to reader/developer which thread pool code is executed in.
Using this assertion, also fixed a bug where index recovery was being executed on akka actor thread instead of ingestion thread.
Also bringing …

feat(various): Assert Thread Name of various operations

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

monix uses TrampolineExecutionContext causing the iterator to be consumed synchronously in some cases. It doesn't seem to be consistent environment to environment.
Disable the assertion temporarily

bug(core): Temporarily disable chunk consumption thread assertion 

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala

Stopping ingestion didn't actually run the handler. Define an explicit cancel task which is passed to the Observable, and complete the stop request via actor messages only.
When ingestion is stopped, no handler is invoked, and no resources are cleaned up. This gives the appearance than ingestion is still active, when in fact it isn't. In some cases this leads to stuck shards.
An explicit cancel handler is used now, which actually gets invoked when the ingestion Observable is canceled. I verified that it's invoked by the test suite by deliberately breaking it, exiting the process.
Also, the remove and release of resources is invoked via an actor message, preventing any odd thread-safety or ordering issues.

bug(coordinator) Stopping ingestion didn't actually run the handler.

---

core/src/main/scala/filodb.core/memstore/PartitionSet.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/PartitionSetSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

The current PartitionSet only supports one schema/Dataset as the ingestion schema and comparator are passed in as constructor params.
Remove the ingestionSchema and comparator from the constructor.  Instead pass in Dataset where needed.  This allows PartitionSet to be used with any number of potential schemas.

feat(core): MultiSchema prep: Allow PartitionSet to be used with multiple schema/Dataset definitions

---

coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

QueryResult uses SerializableRangeVectors only.
Since QueryResult can be a result of an ExecPlan that is executed within the current JVM, we should not be forced into converting results into a SerializableRangeVector.
Hence the interface changes

feat(query, core): QueryResult need not always be serializable

---

cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/DemandPagedChunkStoreSpec.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/SelectRawPartitionsExecSpec.scala

After each `acquire` of searcher, we need to call `release` so that searcher releases the segments and they are deleted after merge. Prior to this change, release calls were not being made.
Currently, we are seeing a constant growth of disk space because old segments are never deleted. Expecting that this change will fix it.
Also renamed commit operation to refresh. Those two are technically different in Lucene. We are actually not doing commit at the bottom of the call stack.

bug(core): Release searchers after each acquire

---

project/FiloBuild.scala

Though the prometheus module has a direct dependency on org.scala-lang.modules:scala-parser-combinators_2.11:1.1.1 , corresponding jar is getting pulled in via kamon-akka-remote.
Prometheus module will have direct dependency on org.scala-lang.modules:scala-parser-combinators_2.11:1.1.1

misc(prometheus): Add scala-parser-combinators dependencies directly to prometheus module

---

query/src/main/scala/filodb/query/exec/PromQlExec.scala

When there are multiple remote queries RecordBuilder throws IllegalArgumentException in checkFieldNo as the same builder is getting used in generating QueryResponse
Every PromQlExec has its own builder

bug(query): RecordBuilder should be part of PromQlExec

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala

Route instant queries to remote if all failures are local, else execute query locally.

feat(coordinator) : routing for instant queries

---

prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/PromQlExec.scala
query/src/test/scala/filodb/query/exec/PromQlExecSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/StandaloneMultiJvmSpec.scala

- [x ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
- [] Docs have been added / updated (for bug fixes / features) ?
A instant query can return different schema for Result case class. This is not handled by PromQlExec json decoder. When there are failure records present for such instant queries, it can result in decoding failure.
Example: Result with single value sample.
```curl "http://localhost:31007/prometheus/api/v1/query?query=sum_over_time(heap_usage%7B_ns%3D%22App-1%22,instance%3D%22Instance-11%22%7D%5B30m%5D)&time=1565405456"
{
"status" : "success",
"data" : {
"resultType" : "scalar",
"result" : [ {
"metric" : {
"__name__" : "heap_usage",
"partition" : "partition-1",
"instance" : "Instance-11", …
```

bug(query) Fix for handling different schemas for instant query responses

---

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
memory/src/main/scala/filodb.memory/Block.scala

Block reclamation is logged at debug, but logging at info will actually help debug the MatchError.
Block reclamation is logged at info, and also catch the MatchError. Log the corruption and move on.

misc(memory, core): Log block reclaim as info; log corrupt vector address and skip.

---

query/src/main/scala/filodb/query/ResultTypes.scala
query/src/test/scala/filodb/query/ResultTypesSpec.scala

- Range queries result has result type "vector" when the result has no range vectors. 
- Query result with single sample have resultType as Scalar.
- Range queries should have result type "matrix" when the result has no range vectors. 
- Query result with single sample should have resultType as Vector.

bug(query) : incorrect result type for QueryResult

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala
project/FiloBuild.scala
query/src/main/scala/filodb/query/PromQlInvocationParams.scala
query/src/main/scala/filodb/query/exec/PromQlExec.scala
query/src/test/scala/filodb/query/exec/PromQlExecSpec.scala

**Current behavior :
AkkaHttpBackend internally creates a new actor system which binds to a random port. On compute, we will need to manage a new port in this case otherwise it can fail with `address already in use` error.
Replacing akka backend with async-client backend. Also adding a read timeout to http request.

bug(query) : replace AkkaHttpBackend with AsyncHttpClientFutureBackend

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
core/src/main/scala/filodb.core/store/package.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
core/src/test/scala/filodb.core/store/ChunkSetInfoSpec.scala
jmh/src/main/scala/filodb.jmh/IntSumReadBenchmark.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

ChunkID is defined as a 43 bit user time (millis from 1970) combined with a 21 bit nano time disambiguator.
ChunkID is now defined as a 42 bit user time combined with a 22 bit ingestion time (seconds from 1970) modulo 48 days.
This change in the chunkID definition might create collisions, although it's unlikely.

feat(core): Redefine chunk id to incorporate ingestion time.

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/memstore/PartitionSetSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
memory/src/main/scala/filodb.memory/Block.scala
memory/src/main/scala/filodb.memory/BlockDetective.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/BlockMemFactoryPool.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala
memory/src/test/scala/filodb.memory/format/vectors/IntBinaryVectorTest.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

When a `MatchError` details in-memory vector corruption, all we get is a pointer.
When a `MatchError` occurs during queries, a very detailed report is logged, showing the current owning block(s), which `BlockMemFactory`s own them and the context (type, dataset, other info), and the reclaim history (previous BlockMemFactories that owned before).  This should allow us to figure out how the conflict happened.
The plumbing added (context info for each BlockMemFactory, owner for each Block, analysis tools) can be used to analyze any future corruption issues.

feat(memory, core): BlockDetective: detailed block corruption ownership/reclaim analysis

---

core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
memory/src/main/scala/filodb.memory/BlockMemFactoryPool.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala

fix(memory): Don't bother tracking blocks which are marked reclaimable. Otherwise a slow memory leak develops. Also remove atomic reference, which isn't necessary because the enclosing class isn't designed to be thread safe.
When markFullBlocksAsReclaimable is enabled (which it is everywhere), the block is marked as reclaimable and still kept in a list.
Full blocks which are reclaimed aren't added to the list to be reclaimed later. Also eliminate atomic reference, since it wasn't necessary. Allocation of new blocks is performed before making any other state changes, in case allocation fails.

fix(memory): Don't bother tracking blocks which are marked reclaimable.

---

README.md
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/gateway/conversion/InfluxProtocolParser.scala
gateway/src/main/scala/filodb/gateway/conversion/InfluxRecord.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala
gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala
jmh/src/main/scala/filodb.jmh/GatewayBenchmark.scala

* The default partition key was simply the tags
* schemaID only calculated from data columns names and types
* Default partition key changed to metric name + tags
* schemaID calculated from partition key also; the column type params are now also included.  This makes schemaID more sensitive to changes in the above.
* The default prometheus schema is now accessible in the code
* Gateway module updated for partition key changes.  The changes include removing the dataset as a param.... it was lame because really the output depended on a specific dataset, passing in other datasets was …

feat(core): Add metric to default partkey; include partkey in schemaID 

---

http/src/main/scala/filodb/http/FiloHttpServer.scala

Exceptions are not being printed in logs while accessing prometheus http api endpoints.
As per https://doc.akka.io/docs/akka-http/current/routing-dsl/exception-handling.html, added an exception handler. Hence, during any exception, the corresponding stackTrace is being logged.

misc(http): Add exceptionhandler in http route

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
memory/src/main/scala/filodb.memory/Block.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/MemFactory.scala

A background task can call BlockManager.markBucketedBlocksReclaimable, which can then steal blocks which are owned by BlockMemFactory instances. Because the BlockMemFactory isn't notified, it thinks it can still access the current block and mark it reclaimable again later. This makes it possible for the block to be shared, leading to corruption.
If there is a block owner assigned, it's consulted first. It can reject the attempt to mark its current block as reclaimable, if it's still being written to. If the attempt is accepted, then all blocks tracked by mem factory are marked as reclaimable, and all references to them are discarded.

fix(memory): Protect blocks from being marked as reclaimable multiple times.

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/test/scala/filodb.coordinator/queryengine2/QueryEngineSpec.scala
query/src/main/scala/filodb/query/QueryOptions.scala

Only one shard key is accepted as an input for QueryOptions.simpleMapSpreadFunc.
Multiple shard keys can be provided as part of input field for QueryOptions.simpleMapSpreadFunc.

feat(query):Support multiple shard keys in QueryOptions.simpleMapSpreadFunc

---

README.md
conf/timeseries-filodb-server.conf
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/TestData.scala
doc/downsampling.md
doc/sharding.md
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala
gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala
http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala
jmh/src/main/scala/filodb.jmh/GatewayBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
standalone/src/multi-jvm/scala/filodb/standalone/IngestionAndRecoverySpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/StandaloneMultiJvmSpec.scala

We have `_ns, __name__` as shard key.
1. All internal reserved label names to start and end with single underscore(`_`). Hence, the shard key `_ns` will be updated to `_ns_`. 
2. Also, adding workspace `_ws_` to the shard key.
Users will not be able to query Timeseries with old shard key. Hence, the idea is to setup and run a new cluster with new shard key changes in parallel to the existing cluster until the TTL is met.

misc(core): Add new shard key _ws_ and rename _ns to _ns_

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Dataset.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala

Currently, we do not honor order in which tags are represented in DatasetOptions `copyTags`. Because of which gateway is not consistent w.r.t adding new tags.
Gateway will consistently add the new tag in the order in which it is added in `copytTags`

feat(core): Honor order in copyTags

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb.downsampler/PerThreadOffHeapMemory.scala

When there are multiple executors per box, each thread needs its own memory constructs. Earlier, downsampler job was sharing memory constructs among all executors on a worker. 
Tested locally by spawning 3 node cass cluster causing multiple spark partitions and executors to be spun off.

bug(downsampler): Thread local memory constructs for multi-threaded spark executors

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala

takeWhile on an observable with mapAsync can potentially cause premature completion of future when runAsync is invoked. Applying this fix to fix the race condition caused between off-heap memory free and the completion of write operation during downsampling.

bug(cass): takeWhile can cause premature completion of future

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala

* Worked around a possible monix/cass driver issue where futures were being terminated prematurely causing race conditions between freeing of offheap memory and the persistence operation.
* Added more configuration to be able to tune spark job in multiple ways

feat(downsampler): Successful run of downsampler functional testing

---

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Doesn't calculate quantile across multiple chunks in the same window
Correctly calculates the quantile across multiple chunks

bug(query): store the array across multiple chunks

---

core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala

**Current behavior :** Metadata query results do not include evicted partitions. 
**New behavior :** When a matching partition is not found in In-Memory map, lookup the PartitionKey using PartitionId from PartKeyLuceneIndex and include in the query results

misc(query): add logic to return partkeys for metadata queries that match evicted partitions

---

core/src/main/scala/filodb.core/legacy/binaryrecord/RecordBuilder.scala
core/src/main/scala/filodb.core/legacy/binaryrecord/RecordComparator.scala
core/src/main/scala/filodb.core/legacy/binaryrecord/RecordContainer.scala
core/src/main/scala/filodb.core/legacy/binaryrecord/RecordSchema.scala
gateway/src/main/scala/filodb/gateway/legacy/conversion/InputRecord.scala

Need to keep old RecordContainer around for sometime to support backward compatibility stories. Hence, copied the RecordContainer and related classes from master branch to a new `legacy` package.
Changes are manually tested in a local gateway and filodb is able to consume the same.

misc(core,gateway):Add old binaryRecord for backward compatibility

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/TestData.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

Sometimes a call to endMetaSpan causes an OutOfOffheapMemoryException to be thrown.
Add metadata span checks and don't add the first block until it's requested. This ensures that it has enough room for metadata.

Add metadata span checks and don't add the first block until it's requested.

---

core/src/main/scala/filodb.core/store/package.scala
core/src/test/scala/filodb.core/store/ChunkSetInfoSpec.scala
memory/src/main/scala/filodb.memory/MemFactory.scala

Chunk IDs don't follow expected ordering when stored in Cassandra, because the underlying type is signed.
Flip the upper bit for signed comparisons to work.

Signed chunkid

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

Metric column is always` __name__` in Binary Join
Metric column of dataset options is used

misc(query):  add metric column as parameter to Binary Join Execs

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala

BinaryJoins after multi schema query change often fail.
- Add debugging to joinKeys when cardinality is expected to be 1-1, but somehow is not.
- Disable check that responses equal LHS + RHS.  This is no longer true with multi schema as filters may return no QueryResult (unknown schema)
- The serialized format for Dataset and Column (see .toString …

debug(query): Add debugging for binary join failures; don't require equal response size

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala

The index of the child plans in `NonLeafExecPlan` was not preserved.  It gets added with `zipWithIndex` after collecting responses, by which the order could be completely different.
This could be an explanation of why joins are failing with the same key being seen twice.
The index is added back the way it used to be before multi schema PR, and preserves the index number no matter what order the tasks complete.

fix(query): Preserve child task index in NonLeafExecPlan (fix joins)

---

coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala
coordinator/src/main/scala/filodb.coordinator/client/Serializer.scala

Serialization of `PartKeysExec` would fail if `FilodbSettings.initialize()` was not called.
If initialize is not called, just get the settings from the default config.

fix(coordinator): Use default settings if initialized() not called

---

prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

:  was not allowed at the beginning of the metric name in a promQL statement.
Added ":" to be included into the metric name.
Also cleaned up the identifier variable names to avoid confusion
No breaking changes.

fix(query): Small fixes to the parser

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala

Metric column is not part of Binary Join result. Prometheus has it when the operator is non-arithmetic.
Add metric column for non-arithmatic operator

misc(query) : add metric column for Binary Join with Non Arithmetic operators

---

coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

When doing binary joins of a gauge and a counter, the query returns with SchemaMismatch error.
The above is caused by two ResultSchemas which are slightly different: LHS one has "count" and RHS one has "value".   The change causes ResultSchemas of DoubleColumns in position 1 (the normal value or result column) to always be named "value" so that anything going through PSM will be named consistently, regardless of the source schema.

fix(query): Rename all DoubleColumns in output ResultSchema pos 1 to "value"

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
conf/timeseries-dev-source.conf
conf/timeseries-filodb-server.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/main/scala/filodb.core/store/package.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala

There is no limit on user time length of a chunk. Because of this, it is not simple to issue one cassandra query and get only the relevant chunks for a given user time range in query. Currently, ODP logic currently load ALL chunkInfos for a partition into memory and then decide which chunk time ranges to page in. This involves two cassandra reads per partition and is expensive (or not even viable) especially when serving long term retained (downsampled) data which is almost always not going to be in memory.
This PR 
* limits the time-length of a chunk during ingestion
* issues just one …

feat(cass): Faster Cassandra reads for raw partition data

---

coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala

filodb_chunkmeta_all throws _BadQueryException Invalid logical plan
For RawChunkMeta LogicalPlan generate local exec plan without routing

bug(query): generate local exec plan without routing for RawChunkMeta logical plan

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala

TSDB regex label filters with `&` in value are ignored.
Optional regex in Lucene are disabled.

Disabling optional regex in Lucene since RE2 does not support it.

---

README.md
doc/downsampling.md
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
http/src/test/scala/filodb/prom/downsample/GaugeDownsampleValidator.scala
jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala
prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

To select the non-default column in a query, one uses a label: `__col__="min"` for example.
This is a magic filter which does not work like normal label filters.
This change switches the syntax to select a column to a `::col` suffix in either the metric name or the `__name__` label filter value.   
The thought is that this makes the transition easier for some histogram use cases, ie
`rate(my_histogram_count{....}[5m])` => `rate(my_histogram::count{...}[5m])`
Existing queries that specify `__col__` filter would need to be rewritten.

feat(prometheus): Use ::col for column selection in PromQL

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/HistogramQuantileMapper.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
query/src/main/scala/filodb/query/exec/ScalarTimeBasedExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/HistogramQuantileMapperSpec.scala
query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/LabelReplaceSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/LableJoinSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/ScalarFunctionSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/SortFunctionSpec.scala

IllegalArgumentException is thrown for HoltWinters as it has 2 funcParams and ExecPlan has  ```require(transf.funcParams.size == 1, "Only one funcParams exists")```
Change paramResponse to Seq[Observable[ScalarRangeVector]] to handle multiple scalar params.

bug(query) : IllegalArgumentException thrown for queries having more than one funcParams 

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

We use EWAH bitmap in queries. When matching partitions are very high, constructing the bitmap is VERY cpu intensive since the set is O(n) complexity on a bitmap. 
Replace bitmap with debox buffers.
Also limiting the maximum number of partition matches per shard in queries to be defensive. Extremely large queries can hog memory and destabilize the server.

bug(core): EWAH bitmap in query is very CPU intensive

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cli/src/main/scala/filodb.cli/CliMain.scala
conf/timeseries-dev-source.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/ChunkDownsampler.scala
core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Dataset.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/store/ChunkSetInfoReader.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala
doc/query-engine.md
memory/src/main/scala/filodb.memory/format/BinaryVector.scala
memory/src/main/scala/filodb.memory/format/MemoryReader.scala
memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala
scripts/schema-create.sh
scripts/schema-truncate.sh
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerMain.scala
spark-jobs/src/test/scala/filodb.downsampler/DownsamplerMainSpec.scala

Capability to downsample Prometheus Counters and Histograms.
Simple strategy:
* Last value of counter or histogram used for every downsample period
* If there is a drop, then the last value before drop and the first value after drop are also included.
* Case of gauges and counters in same schema is handled using downsampler-period-marker which is an abstraction which identifies the row numbers at which downsampling should be done by looking at timestamps of rows or counter values. The period marker is configurable for schemas.

feat(core): Prometheus Counter and Histogram downsampling

---

README.md
conf/telegraf.conf
gateway/src/main/scala/filodb/gateway/conversion/InfluxProtocolParser.scala
gateway/src/main/scala/filodb/gateway/conversion/InfluxRecord.scala
gateway/src/test/scala/filodb/gateway/conversion/InfluxRecordSpec.scala

In the gateway, Influx Line Protocol input was being converted to all "promCounter" schema, and histograms were being written using old Prom-style individual time series per bucket.
Influx Line Protocol inputs are now converted to gauge, counter, and histogram schemas.
summaries are not supported yet.
Existing Prom-style histogram queries will need to be changed.

feat(gateway): Convert ILP lines to new gauge, counter, histogram schemas

---

core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala

debox.Set.toSortedBuffer and debox.Buffer.sort result in `spire` library conflicts when executed in spark. Hence resorting to the approach of removing spire runtime dependency.

bug(sparkJobs): Workaround spire linbrary conflict with spark

---

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala

add `last` function for supporting last sample in a time window. This implementation ensures that timestamp of last sample is after start-time and before end-time of the window.

add function "last" for supporting last sample in a time window

---

README.md
coordinator/src/main/scala/filodb.coordinator/queryengine2/QueryEngine.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

The only way to discover the schema of time series is by using the `filo-cli` querying capability.
There is no way to filter time series by specific schema.  This becomes an issue if a user changes the type of a metric.
Metadata queries using `PartKeysExec` (ie /api/v1/series) will return `_type_` labels for all matching time series.
The `_type_` filter can be added to queries to restrict queries to only a specific schema.

feat(query, coord): _type_ schema filter and metadata results label

---

README.md
cassandra/src/main/scala/filodb.cassandra/CassandraTSStoreFactory.scala
cassandra/src/main/scala/filodb.cassandra/FiloCassandraConnector.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/BaseDatasetTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
conf/timeseries-filodb-server-ds.conf
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
filodb-dev-start.sh
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
scripts/schema-create.sh
scripts/schema-truncate.sh
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb.downsampler/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb.downsampler/DownsamplerMainSpec.scala

Downsampled data and raw data are in same keyspaces (but different tables)
1. Downsampled data is moved to another keyspace. Reasons:
* We may want different replication settings for downsampled data
* PartKey tables per shard may result in too many tables in one keyspace
2. manual testing of Downsample Filo Cluster is done with this PR. Fixed all issues so we can serve downsampled data queries.
3. Downsampling White/Black Listing

feat(core): Place downsampled data in its own keyspace

---

core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala
core/src/main/scala/filodb.core/store/ChunkSetInfoReader.scala
memory/src/main/scala/filodb.memory/format/BinaryVector.scala
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala

Downsample period markers are purely calculated based on vector length.
However it is possible for some vectors to be longer due to ingestion buffer limits.
* Incorporate chunk length in marker calculations.
* Also add copious debugging information when vector processing goes astray during downsampling

bug(sparkJobs): Ensure downsample marker rows are within chunk length

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala

When chunks are read from cassandra for downsampling, the read is broader to ensure all chunks are read (reference: maxChunkTime). In that process, extraneous chunks outside downsample time range may be read. These chunks are ignored with this PR since they were downsampled in the previous run. 
If left unchecked, they were causing issues with math because endRow < startRow when downsampling these chunks.
NOTE: making this change directly in integration branch for faster testing at scale.

bug(sparkJobs): Ensure chunks read from Cass are in downsample time range

---

core/src/main/scala/filodb.core/downsample/DownsamplePeriodMarker.scala
core/src/main/scala/filodb.core/store/ChunkSetInfoReader.scala
spark-jobs/src/main/scala/filodb.downsampler/BatchDownsampler.scala

There seems to be more cases where startRow still is less than endRow. Add debug information

debug(sparkJobs): Skip/Debug startRow > endRow during downsampling

---

README.md
core/src/main/resources/filodb-defaults.conf
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

If users send time series data with a tag labeled "metric", it clashes with the built-in "metric" column used in the partition key.  Users are not able to properly query those time series.
The internal metric column is renamed `_metric_`, since underscores are internal labels, so it no longer conflicts.
Data on disk does not change and does not need to be wiped.  
However, any queries which explicitly used `metric` would need to be rewritten to use `_metric_`.

config: Change metric partition column to _metric_ to avoid clashes with "metric" labels

---

core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala

When `RecordBuilder` adds map key values to a BinaryRecord, it makes an assumption that keys are at least 4 bytes long in the `makeKeyKey` hashing code, reading an Int from a byte array.  If the keys are less than 4 bytes long this can result in undefined behavior.
The algorithm is changed to the following:
* If the key is <= 8 bytes long, the entire key is converted to a Long and used as a hash.
* If the key is > 8 bytes long, then XXHash 64-bit hash generator is used.

bug(core): Fix/change predefined keys hashing algorithm for keys < 4 bytes

---

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
gateway/src/main/scala/filodb/gateway/conversion/InfluxRecord.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/test/scala/filodb/gateway/conversion/InputRecordBuilderSpec.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

Empty histograms cannot be ingested and queried properly as they don't have a schema.
When an empty histogram is pushed into the gateway, it corrupts the state of the RecordBuilder, as empty histograms cannot really be encoded.  
Empty histograms are checked in `InputRecord` and skipped, thus encoding is not attempted.

fix(gateway): Skip empty histogram records in gateway

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
standalone/src/main/scala/filodb.standalone/FiloServer.scala

* Logging config on startup to debug downsample server load
* `Duration.toSeconds` not available in java-8

debug(standalone): Logging server config on start; toSeconds not Java-8 compat

---

akka-bootstrapper/src/main/scala/filodb/akkabootstrapper/ClusterSeedDiscovery.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/metastore/CassandraMetaStore.scala
conf/timeseries-filodb-server.conf
core/src/main/resources/filodb-defaults.conf
core/src/test/resources/application_test.conf
standalone/src/main/scala/filodb.standalone/FiloServer.scala

New tables get auto-created when server comes up. Multiple tables attempt creating same table and schema disagreement ensues on Cassandra.
Disable creation of tables. Enable auto-create only for local dev environment, and unit tests.

bug(cassandra): Dont auto-create Cassandra tables in prod

---

cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala

Expects partitionkeys_by_update_time table.
Table name is renamed to pkeys_by_update_time.
Need to pre-create the new table pkeys_by_update_time before restarting the cluster with this change.

misc(cassandra): Reduce PartitionKeysByUpdateTime table name length

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/FailureProviderSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

Remove isPeriodicSeriesPlan and put the logic in isRoutable

misc(query): consolidate isPeriodicSeriesPlan and isRoutable

---

spark-jobs/src/main/scala/filodb/downsampler/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/DownsamplerSettings.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala

- Register Kamon plugged-in metric reporters for Downsampled spark jobs
- Remove spark-context stop statement from the Driver

misc(Downsampler): register metric reporters for downsampler spark jobs

---

core/src/main/scala/filodb.core/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/BatchDownsampler.scala

Got exception when stitching raw/downsampled data:
```filodb.core.memstore.SchemaMismatch: Multiple schemas found, please filter. Expected schema ResultSchema(List(ColumnInfo(timestamp,TimestampColumn), ColumnInfo(value,DoubleColumn)),1,Map(),Some(430),List(0, 1)), found schema ResultSchema(List(ColumnInfo(timestamp,TimestampColumn), ColumnInfo(value,DoubleColumn)),1,Map(),Some(147),List(0, 1))```
Notice that the only attribute different in schema is fixedVectorLen
Override reduceSchema method for StitchRvsExec and omit vector length comparison

Downsample stitch fix

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

- changes to Index migration job
- to make look-back time configurable. Index updates are applied incrementally/sequantially fro m earliest hour.
- add a config flag to enable complete index refresh from raw cluster to data sampler clusters. This is needed for initial migration when downsampler is enabled as well as to fix corrupt downsampler index.

misc(downsampler): make index-migration batch job lookback time configurable

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/scala/filodb.core/Perftools.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala

This is the first step for supporting a spark job which can copy chunks (and the ingestion time index) to another C* cluster or keyspace. This will make it possible to perform disaster recovery and backfilling.

feat(cassandra): Add method to copy chunks to a different C* column store.

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

- add more context to the RepackError exception log to debug histogram ingestion issue
- remove unwanted code from generic exception block - `disableAddPartitions`

misc(debug): add more context to the RepackError exception log & remove disableAddPartitions statement

---

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ScalarQueriesSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala

Raw cluster/dataset can serve data beyond its retention period if it is in memory. However, this is unreliable because lucene index entries and cassandra backed chunks are not guaranteed. Results may be inaccurate. 
Bound Raw data queries strictly to retention period. For queries outside retention period, defer to downsample cluster
Also use the correct maxChunkTime in downsample queries

feat(query): Bound raw cluster queries strictly to its retention period

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/CompositePlanner.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

Composite Planner needs to accept `earliestDownsampleTimestampFn` in addition to `earliestRawTimestampFn` to make sure downsample instants are bound properly as well.

bug(query): Composite Planner needs to accept downsample retention

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/CompositePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala

Retention of downsample dataset was being wrongly configured with retention of raw dataset. Fixed by choosing right retention when downsample/non-downsample mode.
Also removed default param value for earliestRetainedTimestamp to make consumers
more conscious of the retention arg.

bug(query): Wrong retention was configured in QueryActor for downsample cluster

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

Bug manifests itself when vectors are returned to writeBufferPools and loaned out to a different time series
with a different histogram schema, and the sink is not reset, causing bucket changes to throw an exception.
1. Appending*HistogramVector uses this logic to determine if it should initialize a new sink: `if (repackSink == BinaryHistogram.emptySectSink)`
2. Above should happen at beginning of each new chunk/writebuffer.
3. TS1 finishes encoding a chunk, calls switchBuffers . Subsequently the chunk is encoded and returned to the writeBufferPool.
4. When writeBufferPool gets the appender back, it calls …

fix(memory): Clear sinks at reset() to fix histogram multiple bucket schema ingestion bug

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

Cherry-pick: cherry-pick 5ebcb83ff86d55d800e2e3d8dd5f74082172ce7c - fix(memory): Clear sinks at reset() to fix histogram multiple bucket schema ingestion bug (#645)

cherry-pick(5ebcb8): Clear sinks at reset() to fix histogram multiple bucket schema ingestion bug (#645)

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

LongTimeRangePlanner calls getRawSeriesStartTime always. GetRawSeriestIme throws Invalid logical plan exception when logical is not routable like for scalar time functions
Make lookbackMs lazy and not call rawClusterPlanner.materialize when logicalPlan is not routable

bug(query): getRawSeriesStartTimeshould not be called if logicalPlan is not routable

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

add data-dropped metric when there is a generic exception. There is already a data-dropped metric captured inside `disableAddPartitions` whenever `OutOfOffheapMemoryException` occurs. This change covers the generic exception case.

misc(debug): add metrics-dropped metric in ingestion exception block

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Config is milliseconds from 1970.
Config is ISO datetime format, which is easier to read and review.

feat(spark-jobs): Use ISO time format in config.

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala

add `Kamon.init` as the first statement inside `foreach`

fix(spark-jobs): downsample index migration, initialize kamon in foreachRDD

---

prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

Result schema for AvgOverTime on downsample data was wrong because of a
check that was not fixed during introduction of multi-schema queries.
Because of this we saw:
```
java.lang.IllegalArgumentException: Invalid col 2 
at filodb.core.query.TransientRow.getDouble(TransientRow.scala:47) 
at filodb.core.binaryrecord2.RecordSchema$$anonfun$11$$anonfun$apply$3.apply(RecordSchema.scala:77) 
at filodb.core.binaryrecord2.RecordSchema$$anonfun$11$$anonfun$apply$3.apply(RecordSchema.scala:77) 
at filodb.core.binaryrecord2.RecordBuilder.addFromReader(RecordBuilder.scala:287) 
at filodb.core.query.SerializedRangeVector$.apply(RangeVector.scala:316) 
at filodb.query.exec.ExecPlan$$anonfun$step2$1$2$$anonfun$7.apply(ExecPlan.scala:151) 
at …
```

bug(query): AvgOverTime on downsample data fails

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

This commit addresses below mentioned issues:
1.) sum_over_time()
If the sequence contains all NaNs, current implementation is giving 0 as result. Instead, it should give NaN as result.
2.) avg_over_time()
If the sequence contains all NaNs, current implementation is giving 0 as result. Instead, it should give NaN as result.
3.) stddev_over_time()
On debugging above functions 1 & 2:
sum_over_time() function will calculate the sum of only non-NaN values and ignore all the NaN values which is CORRECT.
Similarly, avg_over_time() function is also computing the average as  sum of non-NaN values / count of non-NaN values in the sequence which is CORRECT
For stddev_over_time() computation, we need sum, squared sum, avg and count of the non-NaN values in the sequence.
Current code CORRECTLY …

BUG fix for (sum/avg/stddev)_over_time & zscore promql functions

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/PromQlExec.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/ResultTypesSpec.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala
query/src/test/scala/filodb/query/exec/HistToPromSeriesMapperSpec.scala
query/src/test/scala/filodb/query/exec/HistogramQuantileMapperSpec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

- In `reduceSchemas`, ResultSchema comparison is made less restrictive for SetOps and Binary-Joins. fixedVectorLen & colIDs are excluded in the check.
- In order make it consistent, ResultSchema timestamp column type is changed from `LongColumn` to `TimestampColumn`.
- RangeParams fields are renamed to indicate time unit is Seconds

fix(query): Set Ops/binary joins fail when a range vector joined with timestamp

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala

We were not using prepared statements everywhere paying cost of inefficient queries.
Read consistency of ONE was not used everywhere.
* Organize CQL statements by preparing
* Set consistency of ONE for reads, and the configured writeConsistency for writes.

bug(cassandra): Prepared stmts everywhere, fix stmt consistency

---

spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala

Exception handler isn't being called.
The compiled code generated a way to bypass the handler, but the way App works is a mystery to me. Moved the exception handler such that it cannot be bypassed.

fix(spark-jobs): Move exception handler such that there's no backdoor way around it.

---

core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala

Housekeeping index refresh task was still using original schema when adding entries into downsample cluster's lucene index.
Convert part key to downsample schema during index refresh

bug(core): Downsample cluster real time index updates should use downsample schema

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
query/src/main/scala/filodb/query/exec/EmptyResultExec.scala

If query is fully outside retention period it is possible to get a start > end error. This PR addresses this use case by returning empty result without execution. Earlier PRs address the cases where query is partially outside retention period.

bug(query): Handle queries fully outside retention period in SingleClusterPlanner

---

spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala

All exceptions are wrapped to capture the trace in the message, because it seemed necessary.
Revert the wrapping, because it has no useful effect.

fix(spark-jobs): Revert exception wrapping, since it didn't help.

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

* Index migration job should calculate migration hours not based on current hour, but current downsample period
* Migration hours should be overridable
* Added unit test to verify part key persistence in cassandra

feat(sparkJobs): More tunability in index migration; unit tests

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala

When downsample shard comes up, first index refresh needs to happen at least 
from currentHour-6 - otherwise mutations that happened between last index migration job and "now" will be missed.

bug(core): Index Refresh in DownsampleShard should start with currentHour - 6

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

We should not downsample untyped schema. Earlier, untyped schema was being downsampled as gauge.

feat(core, sparkJobs): Stop downsampling untyped schema

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

All ScalarVaryingDoublePlan  queries are routed. LongTimeRangePlanner throws `filodb.query.BadQueryException: Invalid logical plan` when it tries to get lookBackTime from LogicalPlan for queries which should not be routed.
Override isRoutable in ScalarVaryingDoublePlan so that queries like scalar(vector(1)) are not routed

bug(query): override isRoutable in ScalarVaryingDoublePlan 

---

prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Parsing of queries with aggregate function in name  throws exception : java.lang.IllegalArgumentException: Aggregate functions have at least 1 parameter and utmost 2 parameters\n\tat 
Example: `sum:some_metric:dataset:1m{_ws_="some-workspace", _ns_="some-namespace"}`
Make first functionParams mandatory in aggregateExpression. Also added another aggregateExpression so that queries with aggregateGrouping before and after metric name are supported. 
Example: sum without (foo) (some_metric) and sum (some_metric) without (foo).

fix(query): fix parsing of queries having aggregate function in metric name

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala

Chunk copier supports 0 TTL, which is effectively like a delete.
Use 0 TTL to indicate that an explicit delete must be performed on the target, which can be the same as the source.

feat(spark-jobs): Chunk copier supports explicit deletion.

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala
spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Bad data will be ingested - it is a certainty. If the bad data is extreme high cardinality (like ip addresses and uuids assigned to tags), it will affect performance of the downsample index.  This spark job helps with deleting bad entries from the PartitionKeys table based on a filter passed as job config. It deletes from downsample tables by default. But can can configured to delete from raw tables as well.
Use with care since it deletes data from the tables!

feat(sparkJobs): Cardinality Buster to handle ingestion of bad data

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala

Metadata queries include partition keys along with start/end times. Slightly more expensive query when reqested.
TODO
* There is a bug in printing the part key key-value pairs when tested from CLI
* Test from HTTP

feat(query, core): TimeSeries Metadata query can include start/end times

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala

HistMax transformers are being applied to the queries irrespective of what column is being selected.
HistMax transformers will applied to the queries only if the selected columns has max and histogram.

bug(query): Apply newXFormersForHistMax only on selected columns

---

core/src/test/scala/filodb.core/TestData.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
query/src/main/scala/filodb/query/exec/rangefn/InstantFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala

Extracting the `+Inf` bucket out of a histogram vector via `_bucket_="+Inf"` or `histogram_bucket(+Inf` was not working due to a bug in the `HistogramBucketImpl`.  The problem was that we were using code to compare the bucket value using double epsilon, ie (expected - actual) < (epsilon), but subtraction of infinity from infinity yields NaN in JVM.  
We add code to specialize the +Inf case so we wouldn't need to do an epsilon comparison.

fix(query): Fix extraction of +Inf bucket from histogram RV

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
query/src/main/scala/filodb/query/exec/aggregator/CountRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

`count(my_histogram_metric)` fails with exceptions.  The Count RV aggregation logic assumes the values are doubles.
This adds support of count() of histogram RVs.   `CountRowAggregator` is abstracted to support both double and histogram data.

feat(query): be able to count Histogram RVs

---

prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Column name is extracted by splitting metric name at the first occurrence of `::`. This may cause 
incorrect column name extraction if metric name has `::`.
Fix is to split at the last occurrence of `::`

fix(query): modify extract column name logic to take after the last occurence of "::" pattern

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
memory/src/main/scala/filodb.memory/data/ChunkMap.scala
memory/src/test/scala/filodb.memory/data/ChunkMapTest.scala

When a block is reclaimed, chunks can be removed from partitions leaving "gaps" or "holes" in the time range. ODP isn't able to detect these holes, and so data remains missing until after a restart. 
Removing a chunk forces all lower chunks in the partition to be removed as well. ODP can detect the missing data properly and fill in the gap. Although more chunks are effectively reclaimed with this new logic, it's compatible with the original model of time-ordered reclamation. In such a model, gaps aren't expected anyhow.

fix(core): When removing a chunk, remove all lower ones too.

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala

Before:
Paged chunk from Cassandra was copied to off-heap ODP block without checking if it exists in chunkMap. If it already existed, allocated memory is wasted. This with concurrent queries from dashboards caused too many chunks to be paged in and allocated but not added to chunkMap.
After:
We first do the contains check in the single threaded populateOdpChunks method and only then allocate in off-heap.

bug(core): Check if paged chunk exists in chunkMap before copying to block

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/binaryOp/BinaryOperatorFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/BinaryOperatorSpec.scala

Comparison operators with Bool return 0 if lhs or rhs is NaN
Comparison operators with Bool should return NaN if lhs or rhs is NaN

bug(query): comparison operators with bool should return NaN when lhs or rhs is NaN

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/CompositePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala

Since raw data retention is finite (say 3 days), long lookback queries ( > 3d) cannot be handled by raw cluster. They end up being delegated to downsample cluster.
However, there is a delay in population of downsample data. Most recent data would not be available immediately. Hence results of latest instants may not be complete.
This PR omits instants with incomplete window aggregations from query results. We will consider feature of performant window aggregations across raw/downsample clusters for the future.

bug(queryPlanning): Long Lookback cases in downsample queries

---

conf/timeseries-dev-source.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala

We only limit the number of time series a query touches. This is less restrictive than we want.
We estimate data size based on schema, sample size, time range and block queries that go beyond limit. The guidance is to reduce time range, or number of time series queried.

feat(core): Query sizing based limits

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala

feat(sparkJobs): If tracing downsampler, log chunks read from cassandra

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
memory/src/main/scala/filodb.memory/BlockManager.scala

Ingestion can reclaim blocks needed by concurrent queries.
Ingestion waits (up to 16 seconds) for queries to finish.

fix(core): Avoid reclamation when queries are running.

---

core/src/main/scala/filodb.core/store/IngestionConfig.scala
memory/src/main/scala/filodb.memory/BlockDetective.scala
memory/src/main/scala/filodb.memory/BlockManager.scala

Block size is 4MB, which means that some memory is wasted due to chunkmap hole expansion.
Block size is 400KB, which increases the number of blocks, and so it should reduce the wastage.
Also replaced use of LinkedList with ArrayDeque reduce object allocation (old gen stuff) now that more Blocks exist.

feat(core): Reduce block size to 400KB.

---

README.md
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ScalarQueriesSpec.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PagedReadablePartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Downsample server pages all columns of schema since there is no way to fetch specific schema FiloDB columns from cassandra table. 
This contributes to on-heap usage since RawPartData holds on to the vectors until the query/scan is fully done.  This PR releases the unwanted vectors early.
Other fixes:
* Also fixing DownsampleMainSpec to use synthetic timestamps to bypass Query Planner restriction on data TTL.
* Fixed timeout check to return QueryError instead of failing actor

bug(core): Release unwanted vectors eagerly when serving queries from downsampled data

---

core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala

For full-odp, PK bytes is looked up using Lucene. However, BytesRef length was not being taken into consideration when formulating Part Key on-heap byte array. This fix does a copy of the array taking length into consideration.

bug(core): Wrong PartKey Bytes was being used for Full ODP

---

coordinator/src/main/scala/filodb.coordinator/KamonLogger.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala
standalone/src/main/scala/filodb.standalone/FiloServer.scala

It is possible to miss metrics from FiloDB since any shutdown may miss metrics from the last time interval. This commit adds shutdown hook to drain kamon metrics to reporters.
Added to both server and spark jobs.

bug(core): Kamon needs a shutdown hook to drain metrics

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala

- Metadata queries will go to multiple clusters. Even if one cluster is unhealthy SingleClusterPlanner throws null pointer exception as shardMapper is null
- Return execPlan.head when only one planner/execPlan is present

fix(query): throw exception when shardMapper is null and return execPlan head  in materialize when only one execPlan is present

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

1. Removed additional task due to querySession.close and folded it into QueryActor inline.
2. Kamon instrumentation of query scheduler for metrics
Before:
```
QueryInMemoryBenchmark.someOverlapQueries      thrpt   42  1017.285 ± 46.556  ops/s
```
After: 
```
QueryInMemoryBenchmark.someOverlapQueries      thrpt   42  1129.631 ± 33.969  ops/s
```
Relevant new metrics added:
```
executor_tasks_submitted_total{type="ThreadPoolExecutor",name="query-sched-prometheus"}
executor_tasks_completed_total{type="ThreadPoolExecutor",name="query-sched-prometheus"}
executor_threads_active{type="ThreadPoolExecutor",name="query-sched-prometheus"} 
executor_queue_size_count{type="ThreadPoolExecutor",name="query-sched-prometheus"}
```

feat(query): Instrument query scheduler to get metrics

---

memory/src/main/scala/filodb.memory/BlockManager.scala

Headroom latch timeout is always the same, regardless of how much free memory there is.
Timeout is now higher as the amount of free memory goes down. This makes the timeout less aggressive when plenty of headroom exists, preventing unnecessary query and ingestion stalls.

feat(memory): Make the headroom latch timeout proportional to free memory

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala

When locks aren't released properly, an error is logged, but this state is never recoverable. The process must be restarted.
Restart the process after the lock error state has been logged the first time.

fix(memory): Halt the process when locks aren't released properly.

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala

`forAll` use on underlying iterator list was not invoking `hasNext` on all of them thereby not closing some of them. This can cause leak of locks.
Explicitly call `hasNext` and add a require to confirm that all iterators end together.
Acknowledgements: Thanks to @broneill for getting to the bottom of this issue.

bug(query): Aggregation was short-circuiting iteration

---

jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
standalone/src/main/java/filodb/standalone/SimpleProfiler.java

- Ensures all benchmarks are updating the query time in the LogicalPlan before submitting
- Ensures spread is uniform everywhere
- Corrects OperationsPerInvocation
- Starts Kamon

fix(jmh): A few more fixes to QueryInMemoryBenchmark

---

cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/PagedReadablePartition.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala

OPDed chunks are populated oldest first. This can potentially cause another query to assume that chunks are already there in memory because it checks the oldest chunk time in the chunk-map.
Populate chunks in newest first order. This way concurrent queries will take the ODP path. Not efficient since ODP will be done twice but, acceptable for now. At least it will yield right query results.

bug(core): Populate ODPed chunks in reverse order

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala

If there is a lot of churn in time series, downsample shard limits queries more aggressively due to assumption that every matching time series is ingesting for entire time range.
Downsample shard can do more accurate sizing estimate by paying cost of index lookup.
This is what this PR does. It looks up start/end times of all matching partitions and then decides to continue the query.

feat(core): More accurate data sizing for queries on downsample shard

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

Assertion in onReclaim handler can fail with no debug info
Add debug info and proactively halt process.  This causes a restart automatically to clean up state.

debug(core): Log details if onReclaim blockMetaSize assertion fails, and halt process proactively

---

memory/src/main/scala/filodb.memory/Block.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/test/scala/filodb.memory/BlockSpec.scala

No block information is logged when `allocMetadata` throws an OutOfMemoryException
Very detailed statistics on block metadata and BlockMemFactory (the "owner") is printed when `allocMetadata` runs out of room.

debug(memory): Add additional debug logging when allocMetadata() call fails

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala

Reduce downsample batch size from 10k to 500 to reduce cass query size - more queries instead of few very big queries.
Changed spark job to use Sync cass calls since they are single threaded anyway - I was encountering unit test bugs in the observable.toIterator conversion.

perf(sparkJobs): Reducing cass batch size to make c* queries smaller

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/resources/filodb-defaults.conf

Scan on ingestion index table results in duplicates since there is a row per matching chunk.
Remove duplicates from the query result before batching.

bug(cassandra): Read from ingestion index table had duplicates

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala

When there are multiple partitions to query and if one of the partition is local to the queryEngine partition that received the request, it will use one localPartitionPlanner and remoteExec for rest of the planners. This results in schema related issues.
Use local partition planner only when there is one partition to query.

bug(coord): Use localpartitioner only if required

---

core/src/main/scala/filodb.core/query/RangeVector.scala
memory/src/main/scala/filodb.memory/data/ChunkMap.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

For debugging lock release issues, the queries that are acquiring the locks are tracked. This tracking adds some overhead.
The original issues haven't been observed in a very long time, and closeable cursors are now used to ensure that locks get released.

fix(memory,core) Remove some lock state validation, now that closeable cursors are being used.

---

memory/src/main/scala/filodb.memory/Block.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/test/scala/filodb.memory/BlockSpec.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerConcurrentSpec.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala

Lots of AtomicReferences, AtomicBooleans, and Loggers found in a heap dump. Most were from the Block class.
Removed all of these useless objects. Note that block ownership feature was never truly used. The call to "own" a block and to check ownership was always performed in the same thread, in the BlockMemFactory.allocateOffheap method.

misc(memory): Remove unnecessary objects.

---

prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala

We are seeing jobs with long tails where one executor runs for a very long time indicating that original cassandra split based spark partitions were skewed. This PR will shuffle part keys amongst executors and even out data.

perf(sparkJobs): Repartition in downsampler to address jobs with skewed cass partitions

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala

Currently, when ExecPlans come into the QueryActor mailbox, they are processed immediately, and Tasks for actual query plan execution are then added onto a Scheduler.   This results in some issues when a flood of ExecPlans comes to a QueryActor:
1) As the scheduler is used as a queue, and Tasks and associated state use up significant memory, this results in `OutOfMemoryError`s and significant GC pressure, leading to host restarts or much longer latencies
2) A very large number of concurrent tasks from different queries leads to high overhead and thread switching / Monix task management overhead costs, …

feat(coordinator): Query concurrency limiter + single thread per query

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/MemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

Currently if there are checkpoints for a dataset and there is no data at InputSource, recovery process waits indefinitely for data to arrive, and in turn Shard status gets stuck at `StatusRecovery(0)`.
This PR is to 
- timeout when there is no data to read `.timeoutOnSlowUpstreamTo(timeout, Observable.now(endOffset))`
- return endOffset to complete recovery
- mark the status as active
- enable normal ingestion

fix(core): move status from recovery to active if there is no data to read from ingestion source

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala

In Logical plan to query conversion Rawseries column like sum, count is not added. Also params in aggregation function like topk is not added.
- Add Rawseries column like sum, count to query to support queries like `http_requests_total::count{job="app"}`
- Add params in aggregation function like `topk(2.0,http_requests_total{job="app"})`

bug(query): add column in Rawseries and params in aggregation operator

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala

java.lang.NumberFormatException is thrown when bucket  value is +Inf
When bucket value is +Inf use Double.PositiveInfinity instead of converting string using toDouble

bug(query): NumberFormatException for +Inf bucket value

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

Shard key regex logic is applied even for queries that do not have shard key regex. For queries like `histogram_quantile(0.2, sum(http_requests))` PromQlRemoteExec is created which has InstantVectorFunctionMapper.
PromQlRemoteExec just gets results by making HTTP call for ` sum(http_requests)` to the remote endpoint. It does not apply rangevectorTransformers
When shard key filters do not have regex simply return localPlanner.materialize without executing shard key regex logic. This way PromQLRemoteExec is created for the entire query `histogram_quantile(0.2, sum(http_requests))`

bug(query): use localPlanner when shard key filters does not have regex

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala

Logical plan parser generates query with window 0s for timestamp function
Don't append window when the PeriodicSeriesWithWindowing.window is 0

bug(query): logical plan parser for timestamp generates query with window 0s

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
project/Dependencies.scala
project/FiloSettings.scala

This reverts commit 8e7b14c59ec60ca0f9cead014ee189242af030f6.
PR #830 (commit 8e7b14c59ec60ca0f9cead014ee189242af030f6)  Caused a regression when running stress tests. In particular, it causes small queries to get stuck behind slow ones in the queue. One workaround is to increase the number of concurrent queries allowed, but then this effectively defeats the queue.
Revert the change and rely on original scheduler for now.

feat(coordinator): Revert "Query concurrency limiter + single thread per query (#830)"

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala

1. Make cassandra fetchSize configurable so it can be tweaked without new build
2. Increase number of token splits 
Both of these config params address the read timeout during data scans in downsampler.

bug(sparkJobs): Make fetchSize configurable; increase splits

---

conf/timeseries-filodb-server.conf
coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/aggregator/AvgRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/StddevRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/StdvarRowAggregator.scala

- Stddev, stdvar for shard key regex failing with requirement failed: columnTypes cannot be empty
- Avg for query with shard key regex failing with IndexOutOfBoundsException
- Absent for multipartition queries throwing Logical plan not supported for copy  error
- Scalar binary operation between time() and scalar function on regex does not get converted to child plan without shard key regex
- Add copyWithUpdatedTimeRange for all ApplyAbsentFunction  and other logical plans
- Append leaf logical plan of scalar argument for ScalarVectorBinaryOperation for queries like `scalar(http_requests_total)`
- Change skipMapPhase to false for MultiPartitionReduceAggregateExec as reduce for sttdev, stddvar need “mean” and “ count” …

bug(query, coordinator):  bug fixes for shard key regex and multipartition queries

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala

Current behavior is to set child query execution parallelism to `availableProcessors`. This is throttling metadata queries where there will be more child execution-plans, since query is dispatched/executed on all the shards. With this change, parallelism is set to number of child plans, so that child query execution will not be throttled.

misc(query): match nonleaf child query parallelism to number of children

---

query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

Binary join with AND adds all LHS range vectors which have matching keys in RHS. When RHS has empty range vectors, keys are present with all values as NaN. AND  operator picks value from LHS  which can be non NaN. So final result has range vectors from LHS even if RHS is empty
Don't add Range vector if matching RHS range vector is empty

bug(query): binary join with AND has LHS range vectors when corresponding RHS range vector is empty   

---

cli/src/main/scala/filodb.cli/CliMain.scala
project/Dependencies.scala

Part of #457 
`quantifind.sumac` is not being ported to Scala 2.12. Instead, I migrate `CliMain` to use scallop
that has already been used in `gateway`.
Scallop uses different way of parsing lists and maps.
Specifically, uses space (` `) for list delimiter and equals (`=`) for value definition in map.
This applies to following parameters of `CliMain`:
1.  `labelNames`: instead of `--labelNames a,b,c` program expects `--labelNames a b c`.
2. `shards`: instead of `--shards a,b,c` program expects `--shards a b c`.
3. `labelFilter`: instead of `--labelFilter key1:value1,key2:value2` it expects `--labelFilter key1=value1 key2=value2`.

misc(cli): use scallop instead of sumac

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala

Remote Exec for LHS and RHS of binary join have original query
Generate LHS/RHS query by converting LHS/RHS logical plan to query and use it to create QueryContext

bug(query):  binary join remote query children have original query

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
core/src/main/resources/filodb-defaults.conf
core/src/test/resources/application_test.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala

Now all token scan queries will use the splits configuration defined for the cassandra cluster.
Earlier, splits were being applied only for the downsample scan queries.
This is being done, after discovering that index bootstrap scan CQL queries are also latent if cassandra cluster is overloaded.

perf(cass): Increase splits for all token scans

---

query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

AND returns LHS row values if corresponding RHS row value is not present which is represented by NaN
Add LHS row to result only when corresponding RHS row is not NaN

bug(query): AND returns LHS row values if corresponding RHS row value is NaN

---

core/src/main/resources/filodb-defaults.conf
gateway/src/test/scala/filodb/gateway/conversion/PrometheusInputRecordSpec.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala

`_step_` tag was earlier introduced as predefined tag. As a result new partKeys are created which aren't equivalent to old ones. In addition, binary joins have issues since the one-side in OneToOne or OneToMany joins now have duplicate join keys.
* Rename `_step_` tag with unused `_pi_` (stands for publish interval). Test case included to ensure name update works fine.
* Include tags like `_step_` and `_pi_` in the `on` specifier of joins

bug(core): Revert _step_ predefined key since we already use it; fix binary joins

---

core/src/main/scala/filodb.core/query/RangeVector.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala

Step2 latency measured includes monix task wait time in queue
We need to measure scan latency separately. This is the non-asynchronous part of the query processing which should ideally remain the same (per sample scanned) irrespective of spread changes.

measure(query): Measure latency of scans separately

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala
query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala

Queries like absent(sum(http_requests_total{job="myjob"})) throw a class cast exception.
Use an empty column filter when passing an aggregate result into the absent function.

fix(query): Fix class cast exception when using absent function over an aggregate

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

Added support in Parser to parse LabelValues queries. Also, fixed an issue in `SingleClusterPlanner` where the label value filter materialize did not use `renameMetricFilter`.
Thank you @TanviBhavsar for the help in Parser.

feat(parser): Add support to parse LabelValues query filters

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Incorrect prev value returned by DoubleLongWrapDataReader.changes
Return correct value

bug(query): changes return non zero result when input has constant value

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ExtraOnByKeysUtilSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/test/resources/application_test.conf
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala

* Extra join-on or group-by keys are added during planning time and not during runtime.
* Keys are added only if query overlaps with configured time ranges
* Keeps code clean, and improves unit testability

bug(coord): Add extra by and on keys in QueryPlanner

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ExtraOnByKeysUtilSpec.scala
version.sbt

Query Planner changes to add join key were not done equivalently.
Now adding extra on-keys only if `on` specifier is non-empty already

bug(coord): Extra on-keys should be added only if on is nonEmpty

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ExtraOnByKeysUtilSpec.scala
version.sbt

Head is called on empty list 
Check whether list is empty before calling head

bug(query):  head call on empty list in LogicalPlanUtils

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
memory/src/main/scala/filodb.memory/MemFactory.scala

When ODP fails to allocate, it leaves the metadata span open, and the blocks it contains aren't marked as reclaimable. The next time a span is started, the existing blocks within the span are lost.
When ODP fails, an explicit discard method is called to mark the blocks as reclaimable.

fix(core,memory): Allow blocks to be reclaimed when ODP fails.

---

query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/test/scala/filodb/query/exec/SplitLocalPartitionDistConcatExecSpec.scala

As splits can be of different lengths, Ignore fixed vector length during reduce phase in SplitDistConcatExec plan

misc(query): ignore fixed vector length during reduce phase in SplitDistConcatExec plan

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/main/scala/filodb.memory/data/ChunkMap.scala
memory/src/main/scala/filodb.memory/data/Shutdown.scala

* Blocks are not marked reclaimable if there is a cassandra error, but they are released back to pool where they will never be marked as reclaimable.
* When we run out of memory in ingestion pipeline, we continue without cleanup
* Mark blocks as reclaimable even though the chunks are not completely flushed. 
* Shutdown process if we run out of ingestion memory.

bug(core): Mark ingestion blocks reclaimable on cassandra failure

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/BlockMemFactoryPool.scala
memory/src/main/scala/filodb.memory/MemFactory.scala
memory/src/test/scala/filodb.memory/BlockMemFactorySpec.scala

Address cases where blocks were not being marked as reclaimable in ingestion pipeline causing blocks to leak.
Pulling some of the fixes from https://github.com/filodb/FiloDB/pull/918 so non-contentious bug fixes can go in quickly.
Unit tests will come in that PR.

bug(memory): Blocks need to be marked reclaimable correctly

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala

Filter value is not enclosed in quotes for Label values v2 endpoint in MultipartitionPlanner and HighAvailabilityPlanner
Enclose filter value in quotes

bug(query): add quotes to filter value

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

Metadata queries are not handled in shard key regex planner
Return multipartitionPlanner.materialize for shard key regex metadata queries

bug(query): use multipartitionPlanner for shard key regex metadata queries

---

conf/timeseries-filodb-server.conf
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
scripts/schema-truncate.sh

* Removed scan span which was per result RV. It created too many spans - was not intended earlier.
* Added spans and markers to track scans, and child result retrieval.

bug(query): Remove span per result RV; add spans/markers to track child plans

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala

debug(query): Marking spans when dispatch of child plan is done

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/query/RangeVectorSpec.scala
memory/src/main/scala/filodb.memory/data/ChunkMap.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AbsentFunctionSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Restore the chunk map lock state debugging code removed by PR https://github.com/filodb/FiloDB/pull/822
Tests indicate some queries have unreleased locks.
Also adding TimeSeriesParition.toString so debug line has full signature of time series.

debug(core): Restore chunk-map-lock debugging since we have a case of unreleased lock

---

cli/src/main/scala/filodb.cli/CliMain.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala

Without a user-agent in query header, it is difficult to identify and track who is sending the requests.

misc(query): add user-agent to remote query headers

---

.travis.yml
cli/src/main/scala/filodb.cli/CliMain.scala
conf/timeseries-dev-source.conf
conf/timeseries-filodb-server.conf
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryOps.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityStore.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/memstore/ratelimit/QuotaExceededProtocol.scala
core/src/main/scala/filodb.core/memstore/ratelimit/QuotaSource.scala
core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala
core/src/test/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStoreMemoryCapSpec.scala
project/Dependencies.scala
project/FiloBuild.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala

* Use RocksDB to store cardinality information on disk at the shard level. Can add caching configuration to make it faster.
* RocksDB can be replaced with anything else. We are not married to it in any way.
* Cardinality Tracker can enforce quotas. Quotas are read from static configuration file for starters
* When Quotas are breached, actions can be taken. For this PR, no action is taken except that the data is dropped.
* Cardinality tracked and quotas are enforced per shard. Currently, not possible at the global level.
* Filo CLI can query current cardinality at any shard level.
Quotas are configured for Shard Key Prefixes, and limits number of immediate children.
For example, the following static quota configuration limits number of time series under …

feat(core): Rate Limiting Number of Time Series Ingested into TSDB

---

cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/downsample/ShardDownsamplerSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

switch buffers and create an encoded chunk when current sample's timestamp crosses flush boundary.  e.g. for a flush-interval of 1hour, if new sample falls in different hour than last sample, then switch buffers and create chunk. This helps in aligning chunks across Active/Active HA clusters and facilitates chunk migration between the clusters during disaster recovery.
Note: Enabling this feature might result into creation of smaller suboptimal chunks.

feat(core): add addititional condition to create chunks at flush interval boundary, only when enabled

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSplitSpec.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/aggregator/AvgRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/CountRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/HistMaxSumAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/HistSumRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/MaxRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/MinRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/QuantileRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/StddevRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/StdvarRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/SumRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

If we execute topK query with k as 1 from t1 to t5 we just get max value for every timestamp from all range vectors. So if for a times series only t1 has top value, t2, t3 etc won't be present in final result. When sum is applied on such a query `next on empty iterator` error is thrown as some timestamps are missing.
Add NaN for timestamps which do not have any value in topk result

bug(query): "next on empty iterator" when using sum over topk result

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

Queries like `topk(2,test{_ws_ = "demo", _ns_ =~ "App"})` has just one matching value for regex. We don't need to skip aggregate present step as this query will result in only one sub query.
Make skipAggregatePresent false when there is single matching value for shard key regex

feat(query): make skipAggregatePresent false when there is single matching value for shard key regex

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/QueryPlanner.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/ShardDownsampler.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
query/src/main/scala/filodb/query/exec/ScalarBinaryOperationExec.scala
query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala

We are creating too many spans adding to GC as well as tracing backend pressure.
Use existing spans and create markers instead.
Replace the metrics spans emit with histograms.
**NOTE: Metric names have changed quite a bit in this PR. Dashboards and alerts need to be updated**

maint(all): Using too many spans; replace with histograms

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala

Range vector locks were released in a different thread than the one where it was acquired. This leads to lock state corruption. Closing immediately in same lambda.

bug(query): Fast Reduce closed RV in a different thread

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala

We use printTree that logs plan on errors.
Now that we have original promQL query, we dont need to log full plan - we can log the query.
This reduces logging pressure. We found that in some nodes that are backed on the scheduler, a lot of time is spent logging timeout errors

perf(query): Remove logging of plans to reduce Logging I/O

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala

Invalid warning seen because the lock loop may be observing a write lock.
Mask the high bit of lockState to get shared lock count.

bug(memory): Mask out high bit of lockState to get shared lock count

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala

Counter correction in write buffer vectors was encountering ArrayIndexOutOfBoundsException

bug(memory): Faster-Rate bugfix mutating counter correction vectors

---

query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala

Parse remote query error response and return RemoteQueryError object having status code, error type, and error message

feat(query): return error response and status code for remote query

---

query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

- fix the bug in `resets` function to set the counter to NaN once all rows from window are removed. This fixes an issue where even if there is no data to emit, `resets` function still returns `0`

fix(query): fix resets function to set the counter to NaN outside window

---

cassandra/src/main/scala/filodb.cassandra/Util.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala

Token scan from ingestion index table during downsample use paged iterator, and this sometimes times out causing entire task to repeat causing more writes, more compaction on cassandra, and more read timeouts.
Putting in place retry with exponential backoff.

bug(cass): Retry with exponential backoff when scanning

---

coordinator/src/main/scala/filodb.coordinator/client/FiloKryoSerializers.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/HistogramQuantileMapper.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala
query/src/main/scala/filodb/query/exec/rangefn/MiscellaneousFunction.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
run_benchmarks.sh

We currently make a copy of partKey from offheap into heap via PartitionRangeVectorKey. This can be done lazily.
The effect is especially significant when aggregating high cardinality metrics where part key labels are not inspected for grouping at all.

perf(query): Reduce RV key heap memory for high-card queries

---

query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala

Shard key regex query returns partial  results when remote query throws an exception
Create QueryError with RemoteQueryFailureException when remote query throws an exception. The parent plan will throw exception even when one of the child plans returns QueryError

bug(query):  shard key regex query returns partial  results when remote query throws an exception

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSplitSpec.scala
core/src/main/scala/filodb.core/query/QueryContext.scala

Move time-split query planning config to `PlanParameters`, so that it can be controlled/tuned during `materialze`.

misc(query): Move time-split query planning config to QueryContext

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
conf/timeseries-dev-buddy.conf
conf/timeseries-filodb-server.conf
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala

**Modifications**
- Added a Spark job that can be triggered on demand to copy partitionKey records.  
- Time interval can be configured as specified below. Spark job would copy all the records falling in this interval.
```
conf.set("spark.filodb.partitionkeys.copier.ingestionTimeStart", "2020-10-13T00:00:00Z")
conf.set("spark.filodb.partitionkeys.copier.ingestionTimeEnd", "2020-10-13T05:00:00Z")
```
- This job would be useful in cases of disaster recovery or back fills.
- NA
- data repair feature is new. This job would be useful in cases of disaster recovery or back fills.
- NA

feat(repair): spark job to migrate partitionKeys in case of disaster recovery

---

spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala
spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

With this PR, `delete-pk-filters` filter values can be regex.

feat(sparkJobs): Regex filter support for Cardinality Buster

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala

make `assumedResolution` configurable, as datasets can have different resolution data.

misc(query): make assumedResolution configurable

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

Range Vectors need to be stitched and made distinct before joins because duplicates can exist due to spread changes. Duplicates cause errors in join matching.

bug(query): Stitch and uniqify LHS and RHS before binary join

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

This reverts commit 76b822675099c3a5bceef5eeb032553f6f6bc404.
Cost of stitching before Binary Join is too much and not feasible. We need alternative solution.

Revert "bug(query): Stitch and uniqify LHS and RHS before binary join

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala

Optimally stitching same RVs from multiple shards while performing Binary Join.
This is better than previous attempt since it uses less memory and also less steps to finish the job.

bug(query): Optimally stitch vectors in LHS and RHS during binary join

---

query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

Optimally stitching same RVs from multiple shards while performing Binary Join for LAND, OR and LUNLESS

bug(query): stitch vectors in LHS and RHS during binary join with set operator

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
conf/timeseries-filodb-server.conf
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/test/resources/timeseries-filodb-buddy-server.conf
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala

Follow up to #993. Add index repair for downsampled data via `spark.filodb.partitionkeys.copier.copyDownsample`

feat(repair): Add downsample index repair

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala

During ingestion, drop duplicate and out-of-order samples

misc(core): drop duplicate & out-of-order samples

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala

For queries like `sum(foo) - sum(foo offset 3d)` LongTimeRangePlanner, HighAvailabilityPlanner and MultiPartitionPlanner use offset of head which in this case has value 0
Use max offset for above queries

bug(query): binary join with offset queries uses LHS offset for planning

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
memory/src/main/scala/filodb.memory/BlockMemFactoryPool.scala

Overflow BlockMemFactory in TimeSeriesShard today depends on ODP blocks and hence is not correctly reclaimed after flush of chunks placed in it.
This PR removes overflow BMF in the shard and makes the BlockMemFactory pool track the flush group for which the
BMF is used. Subsequent use in overflow chunks will retrieve same BMF, until the BMF is checked out for flush in the FlushEvent for the group. At that point, it is removed from the map and future calls for overflow BMF will yield a new BMF.
Once the BMF checked out for flush is released after flush to Cassandra, the BMF is put back into free pool.

bug(core): Overflow BlockMemFactory is not reclaimed correctly after flush

---

core/src/main/scala/filodb.core/memstore/PagedReadablePartition.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Downsample shard does not provide an impl for ChunkInfoIterator's `nextInfo` method since data is offheap.
Earlier, we used FilteredChunkInfoIterator to add the counting which invokes `nextInfo` in its logic and causes this error.
```
Caused by: scala.NotImplementedError: an implementation is missing
at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
at filodb.core.memstore.PagedReadablePartition$$anon$1.nextInfo(PagedReadablePartition.scala:75)
at filodb.core.memstore.PagedReadablePartition$$anon$1.nextInfo(PagedReadablePartition.scala:71)
at filodb.core.store.FilteredChunkInfoIterator.hasNext(ChunkSetInfo.scala:341)
at filodb.core.store.WindowedChunkIterator.nextWindow(ChunkSetInfo.scala:421)
at filodb.query.exec.ChunkedWindowIterator.doNext(PeriodicSamplesM …
```

bug(core): Error due to missing impl while counting queried chunks

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

When MultiSchemaPartitionsExec is serialized due to nested ExecPlanFuncArgs plan dispatch, finalPlan field should not be sent
over the wire

bug(query): Dont serialize finalPlan field in MultiSchemaPartitionsExec

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala

An exception is thrown when PartitionLocationProvider returns no partitions
Generate exec plan using localPlanner when no partitions are returned

bug(query): generate local exec plan when partition list is empty

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

Currently there is a bug where we do not remove/purge partitions in index that do not have a TSP on heap.
This PR fixes the bug.

bug(core): Also purge index-only partitions not in heap

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala

Time is not converted to seconds while updating time for ScalarTimeBasedPlan, ScalarFixedDoublePlan and ScalarBinaryOperation
Convert time to seconds

bug(query): incorrect time in copyWithUpdatedTimeRange function

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala

Currently, stitching returns NaN if both RVs have a sample for same instant, irrespective of whether
only one RV has NaN for that instant.
This PR fixes it to pick the non-NaN value for those instants.
This fixes Binary Join stitching issues seen when querying across spread change boundaries.

bug(query): Stitch must accept NaN on only one RV and not return NaN for that

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala

NaN in counter value is compared, and counter correction fails to detect drop
1. Read NaN counter value as 0
2. Mark counter drop correctly in chunks
Open Issue: Existing chunks with missed drop detection may not work when faster-rate is enabled.
Acknowledgement @TanviBhavsar for jointly working on this PR and reproducing the issue in dev environment.

bug(query): NaN causes failure in counter correction and negative rate

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ScalarQueriesSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSplitSpec.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

`topk` throws next on empty iterator when query start time is less than raw retention time. It happens because time of PeriodicSamplesMapper is changed according to raw retention time. However, AggregatePresenter uses query start time
- Retrieve PeriodicSeries/PeriodicSeriesWithWindowing plan from Logical plan. 
- Calculate new start time according to the raw retention time
- Update time for all plans in LogicalPlan

bug(query): topk next on empty iterator

---

memory/src/main/scala/filodb.memory/data/ChunkMap.scala

Query timeout should kick in first. We dont want exclusive lock shutdowns to kick in before query timeout.

bug(core): Exclusive lock timeout should be more than query timeout

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala

Since we don't stop readers when write buffers are mutated, readers can sometimes read partial data leading to intermittent query errors. This PR adds acquisition of write lock during ingestion and mutation of write buffers.

bug(core): Acquire write lock when mutating write buffers

---

core/src/main/resources/filodb-defaults.conf

Change default parallel index scans to 2

perf(core): Reduce index parallel scans to 2 by default

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

- add executeOn to `bootstrapIndex` to make sure task is executed on ingestion thread

misc(fix): fix to make sure bootstrapIndex always runs on ingestion thread

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
conf/histogram-dev-source.conf
conf/timeseries-128shards-source.conf
conf/timeseries-dev-buddy.conf
conf/timeseries-dev-source.conf
conf/timeseries-standalonetest-source.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
doc/ingestion.md
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala

* Consolidate ` demand-paged-chunk-retention-period` and `disk-time-to-live` configs in IngestionConfig
* Rename `pk-by-updated-time-table-ttl` to `write-time-index-ttl`. Change its default to 7 days.
* Fixed IngestionTimeIndex table writes to use `write-time-index-ttl` instead of `disk-time-to-live`

bug(core): IngestionTimeIndex Table write was using wrong TTL

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala

AbsentFunctionMapper does not get executed for metrics that are not present 
- Remove AgggregatePresent from sum aggregator which is added for absent and absent_over_time. AbsentFunctionMapper is not executed if the schema is empty and the ExecPlan has rangeVectorTransformers that can't handle empty schema
- Return empty result in ReduceAggregateExec when input schema is empty

bug(query):  absent/absent_over_time return empty result for nonexistent metric

---

core/src/main/scala/filodb.core/downsample/OffHeapMemory.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/PartitionSetSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/EvictionLock.scala
memory/src/test/scala/filodb.memory/BlockMemFactorySpec.scala
memory/src/test/scala/filodb.memory/BlockSpec.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerConcurrentSpec.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala
memory/src/test/scala/filodb.memory/format/vectors/IntBinaryVectorTest.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Simple refactor. No logic changes.
Move reclaimLock acquisition into TimeSeriesShard so that TimeSeriesPartition eviction can also be 
done regularly in the headroom task while the shard eviction lock is being held.

refactor(core): Refactor headroom task and prepare for locking during TSP eviction

---

cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ScalarQueriesSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala
query/src/main/scala/filodb/query/exec/EmptyResultExec.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/ScalarBinaryOperationExec.scala
query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

InprocessPlanDispatcher currently uses empty config.  Some queries need queryConfig.fastReduceMaxWindows in AggregateMapReduce and they are failing when InprocessPlanDispatcher is used
Assign query planner config to InprocessPlanDispatcher

bug(query):  add config to InProcessPlanDispatcher

---

query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala

feat(query): Handle partial result response in RemoteExec

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartitionEvictionPolicy.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/main/scala/filodb.core/store/package.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/EvictionLock.scala
memory/src/test/scala/filodb.memory/PageAlignedBlockManagerSpec.scala
query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala

Currently, we use lucene index to identify partIds eligible for eviction. This is not proving to be reliable. Getting top-k partitions with oldest endTime from lucene is complex and is complex possibly has bugs. Even if fixed, it yields to complex eviction logic. There are cases when ODP may cause the partition to never be evicted at all because of existing watermark logic.
Hence:
* Explicitly maintain a queue of partIds eligible for eviction. When partition stops ingesting or is ODPed, the partId is added to this list
* Eviction happens very quickly from this queue. Lucene queries will not be an issue. ODPed partitions get evicted first to be consistent with block eviction.
Another issue is we still have ODP cannibalism where ODP queries can silently evict …

bug(core): Fix Partition Eviction Issues

---

query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala

bug(query): Handle isPartial message response in remoteExec

---

cassandra/src/main/scala/filodb.cassandra/FiloCassandraConnector.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala
spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala

We are running async Cassandra calls in spark jobs causing indeterministic wait times
Change cass calls to synchronous calls along with more parallelism at spark level.

bug(sparkJobs): Cardinality buster scale bugs

---

spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/test/scala/filodb/repair/ChunkCopierSpec.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala

**Current behavior :** Repair jobs can only retrieve configuration from a file.
**New behavior :** Building up on #1060, repair jobs will now be able to load configuration from a running FiloDB cluster by hitting an api endpoint.

feat(repair): Support getting filodb configuration at runtime.

---

cli/src/main/scala/filodb.cli/CliMain.scala
memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/main/scala/filodb.memory/format/vectors/IntBinaryVector.scala
memory/src/main/scala/filodb.memory/format/vectors/LongBinaryVector.scala
memory/src/main/scala/filodb.memory/format/vectors/UTF8Vector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

- Current Behavior: Whenever `NaN` is encountered, counter drop is not marked. But counter drop is marked when the subsequent value is lower than the previous non NaN value. But this breaks if NaN occurs at the chunk boundary.
- Changes: As NaN represents end of time-series, A counter drop is marked Whenever an NaN is ingested. For value comparison purposes NaN is considered as `0`. This fixes chunk boundary case as well.
thanks @vishramachandran for contributing to the PR

misc(core): add drop marker whenever NaN is encountered during ingestion

---

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala

Maximum time to consistency is 1m for lucene changes. So two `purgePartitions` calls from flush pipeline that are spaced 1m or less can cause double delete of partitions, and double decrement of time series count.
1. Reducing lucene consistency to 55 seconds.
2. Catching exceptions in Card Tracker.

bug(core): Reduce possibility of double purge

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerMaterializer.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ScalarQueriesSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSplitSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala
jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryHiCardInMemoryBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryInMemoryBenchmark.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/PlanDispatcher.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
query/src/test/scala/filodb/query/exec/SplitLocalPartitionDistConcatExecSpec.scala

Currently Binary join is not done across downsample and raw cluster. If query time is greater than raw retention, the entire query will be sent to downsample cluster and raw cluster both and then the results will be stitched.
If LHS/RHS query start time is less than raw retention we will send only LHS/RHS to downsample cluster, RHS/LHS would be evaluated on raw cluster and then Binary join will be computed using InprocessDispatcher
Example:  `some_metric offset 8d - some_metric`
If raw retention is 7 days, LHS will be sent o downsample cluster and RHS will be evaluated on raw cluster and then Binary Join will be applied

feat(query): binary join across downsample and raw cluster

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/PartitionEvictionPolicy.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

While deciding if eviction is needed, currentPartitionCount was used instead of availableRoom. Fixed that.
Also using freeNativeMemory to decide lock timeout.

bug(core): Free partition count was wrong during eviction

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
project/Dependencies.scala

Logical plan column filters do not have escape characters. While converting to query column filter value is used directly
Add escape character to column filter value

bug(query): add escape characters in column filters when converting logical plan to query

---

query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala

Fast reduce is called with skipMapPhase as false in map-reduce phase. When skipMapPhase is false empty period gets assigned to outputrange in IteratorBackRangeVector which is input to the reduce phase. So final outputrange is empty
Assign outputrange from input range vector

bug(query): empty outputrange in fastreduce

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala

Exception is thrown for the entire query when histogram schema is not same even for a single instant 
Return NaN for timestamps where schema does not match and return aggregation result for other timestamps

feat(query): don't error histogram aggregation with heterogenous bucket scheme

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PagedReadablePartition.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

If user provides a query with lookback < dataResolution, we silently return NaN for rate/increase queries when the window for rate contains only one sample. This happens often with downsample dataset and this is misleading for users.
This PR helps throw an error back to the user indicating to them that the lookback is small for the query range.

feat(query): Throw error if lookback smaller than data resolution for  counters

---

conf/timeseries-filodb-server.conf
core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

**Current behavior :** Repair jobs rely on `dataset-config` which needs to be parsed separately.
**New behavior :** Repair jobs will rely on `inline-dataset-config` which is part of source config. No separate file need to be parsed.

feat(repair): Use inline dataset config for repair jobs

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala

Absent function mapper is not executed when there are multiple rangeVectorTransformers on the same ExecPlan 
Run rangeVectorTransformers which can handle empty schema when schema is empty

bug(query): handle multiple rangevector transformers with absent function

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala

During bootstrap, all partkeys fetched from persistent store will be added to lucene index. After this fix, the entries which have endDate older than longest retention will be filtered, so that those partkeys are not indexed anymore.

misc(downsample): filter PartKeys with endDate older than ttl during bootstrap

---

core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala

trace-info is added to querycontext. When a query execution is proxied to remote server, trace-info is added to the http headers.

misc(query): add trace-info to RemoteExec plans

---

scripts/schema-create.sh

fixing create_partkey_tables syntax in schema_create.sh

---

query/src/main/scala/filodb/query/LogicalPlan.scala

fix(query): Syntactic fix of a scaladoc comment

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Reuse lucene fields to reduce allocation during Index bootstrapping.
For dynamic fields, using a weak hash map to cache the fields.
Also fix test compile issue that existed.

perf(core) Lucene field reuse

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

Evictable Part Ids can have duplicates for intermittent time series and it can possibly get out of hand.
Hence using a LinkedHashSet to maintain the evictable Part Ids list.
TODO:
We need to reduce memory usage and use unboxed data structures. As an observation, LinkedHashSet is using roughly 70MB for 1mil Ints. For 8 shards, one can expect 560mb or so. Compare this with simple array of 8 * 1mil ints: 32MB.

bug(core): Handle possible dupes in evictable partIds list

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
spark-jobs/src/main/scala/filodb/repair/ChunkCopierValidator.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopierValidator.scala
spark-jobs/src/test/scala/filodb/repair/ChunkCopierSpec.scala
spark-jobs/src/test/scala/filodb/repair/ChunkCopierValidatorSpec.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierValidatorSpec.scala

1. Given dataset `x` passed in repair config, downsample index repair tries to repair dataset `x`.
2. Index downsample repair tries to write to `part_key_by_update_time` table which doesn't exist.
1. Given dataset `x` passed in repair config, downsample index repair will repair dataset `x_ds_${highestDSResolution.toMinutes}`
2. Index downsample will not write to `part_key_by_update_time` table.

Downsample repair

---

spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala

**Current behavior :** Chunk repair for downsample writes data with the highest resolution ttl.
**New behavior :** Chunk repair for downsample writes data with the resolution specific ttl.

bug(repair): Use resolution specific ttl for downsample dataset in chunks repair

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

Logical plan to query function converts queries with brackets like `foo / (bar + baz)` to '`foo / bar + baz` as the function/logical plan does not know that  original query had brackets 
Enclose all binary join queries in brackets

bug(query): logical plan to query function does mot preserve brackets

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

We bootstrap the index and flush at one go. This consumes too much resources since too much data is accumulated without compression.
Start the flush thread before starting to bootstrap the index.

perf(core): Improve performance of index bootstrap by refreshing regularly

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

For Prometheus histogram sum & count queries like `histogram_sum` and `histogram_count` we need columns sum and count in Exec plan. Currently, original column list which is empty is getting used
Use newColName to generate ColID's

bug(query) : use updated col name to generate columnl ID's

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
memory/src/main/scala/filodb.memory/BlockManager.scala
memory/src/main/scala/filodb.memory/EvictionLock.scala

Currently we shutdown too prematurely even if memory is slightly lower than threshold, and we didn't get the lock 5 eviction iterations. This is too aggressive, considering that timeout calculated (due to just below threshold) will be very small.
New algorithm:
1. Don't shutdown if not able to reclaim for multiple attempts as done today. Rely on ingestion failure to trigger forced shutdown.
2. If really close to threshold, increase timeout much more steeply than being done today. Given that query timeout is 60s, the maximum timeout should be at least that.
3. Also track queries that are holding the shared eviction locks for debugging purposes. This involves some small cost in memory and latency.

bug(core): Make shutdown on eviction lock timeout less aggressive

---

cassandra/src/main/scala/filodb.cassandra/Util.scala

Working around these errors when older version of guava is loaded into classpath/fatJar by using GuavaCompatibility class in cassandra driver:
```
Caused by: java.lang.IncompatibleClassChangeError: null
at filodb.com.google.common.util.concurrent.Futures.addCallback(Futures.java:1014)
at filodb.cassandra.Util$CassandraFutureOps.toScalaFuture(Util.scala:61)
at filodb.cassandra.Util$ResultSetFutureOps.toIterator(Util.scala:70)
```

bug(cass): Backward compatibility with older versions of Guava

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala

- Longer disk-ttl is causing integer overflows. This is causing inadvertent purging of partitionKeys.

fix(core): change disk-ttl configuration type to Long

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
memory/src/main/scala/filodb.memory/EvictionLock.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala

We acquire shared lock in `lookupPartitions` which is a deadly side-effect not known to callers. For a recent feature a new call was added to invoke `lookupPartitions`. Since the query path includes that call elsewhere, the shared lock for shard got acquired twice. However we release it only once causing problems. Load testing brought the shared to stand-still.
In addition, we do not have a timeout during shared lock acquisition.
* Refactor out shared lock into separate method, and call it from specific plans that need them.
* While at it, I have also refactored the duplicate code to check if shard is ready after bootstrapping.

bug(query, core): Shared lock was being acquired twice in one query

---

project/FiloSettings.scala

Reverting #1212 since it is safe to leave it around.

revert: misc(build): do not relocate google.common package

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala

Safety check to ensure that eviction lock is not set multiple times on session.
Acquiring shared lock multiple times, but releasing only once will lead to system errors.

maint(core): Catch coding errors due to setting lock multiple times on session

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala

1. Include QueryStat in errors too. 
2. Calculate dataBytesScanned instead of chunksScanned in QueryStats
Important Limitation to Know:
QueryStatistics for all errors are not aggregated up since we do not wait for all child results to arrive before propagating error upstream.

feat(core): Query Statistics included in Query Errors

---

query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala

bug(query): Don't issue 0s for changes function over a subquery when no data

---

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala

Currently we are having traceInfo map but the userAgent is being explicitly set still from queryParams. Fixing the same.

feat(query): utilize traceinfo map for remote-exec

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala

… for subqueries in MultiPartitionPlanner

bug(query) Fix invalid start/end parameters for PeriodicSamplesMapper for subqueries in MultiPartitionPlanner

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerHelper.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

**Review only PR**
Multi partition queries behave incorrectly . Consider the following multi-partition query 
``count(sum by(metric_ws_tag)(foo{_ws_ = "demo", _ns_ =~ "App-.*"}))``
The inner aggregation ``sum by(metric_ws_tag)(foo{_ws_ = "demo", _ns_ =~ "App-.*"})`` may have same`` metric_ws_tag``  and the sum operation will reduce them to 1 row with the corresponding sums added up. The ``count`` of this result should return the same number as the number of rows returned by the ``sum1` aggregation operation.  Current behavior pushes the high level ``count(sum by(metric_ws_tag)(foo{...}))`` aggregation to all partitions and sums the counts which double counts results giving an incorrect count than expected
The new …

bug(query) Fix issues with multi-partition aggregation operation

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

**Review only PR**
After PR #1232, the in process aggregation needs to be added using addAggregator to ensure both Mapper and Reducer are added correctly. The fix changes this code to include ``addAggregator``
New query plan should correctly have both mapper and reducer, consider the following query
``sum(count by(foo)(test1{_ws_ = "demo", _ns_ =~ "App-.*"}))``
With regex resolving to two namespaces, the query plan generated with a ``SingleClusterPlanner`` as the underlying planner  is as follows
```
T~AggregatePresenter(aggrOp=Sum, aggrParams=List(), rangeParams=RangeParams(1000,1000,1000))
-E~LocalPartitionReduceAggregateExec(aggrOp=Sum, aggrParams=List()) on …
```

fix(query) Fix issues with multi-partition aggregation's in process aggregation

---

core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

`lookupPartitions` initializes query stats object with the metric name for subsequent use. Histogram backward compat feature changes the metric name but does not clear the stats object. This commit helps with that.

bug(core): Reset metric name in stats during histogram backward compat

---

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala

Switch to http POST in RemoteExec to support bigger payload in query params.

misc(query) use http post in RemoteExec client

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryOps.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityStore.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala
core/src/test/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStoreMemoryCapSpec.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala

RocksDB cardinality tracker is now able to track actively ingesting time series broken down by shard key in addition to total time series 
Removed kamon metrics based active/total cardinality reporting since it generates high cardinality time series.

feat(core): Cardinality Tracker tracks active timeseries by shard key

---

query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

As `TopkCardReduceExec` merges `ItemsSketch`es, the serialized sketches are interpreted as `String` instances before their bytes are read. The cast succeeds, but the sketch was originally serialized as a `ZeroCopyUTF8String`. When a query result's cardinality is sufficiently large, the string's size is incorrectly read during deserialization, and a `SketchesArgumentException` is thrown.
The sketches are now interpreted as `ZeroCopyUTF8String`s before their bytes are read. The string's size is correctly read.

fix(query): topkcard incorrect string cast

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala

In some metrics publishers, final job metrics do not get published despite Kamon shutdown hook.
This is a quick "sleep" hack to ensure that metrics get published before driver and worker shutdown.

bug(sparkJobs): Sleep for 1m to ensure completion metrics publish

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala

In MultiPartitionPlanner, we are not converting logicalplan back to promql query string. This is creating issues where the logical plan is modified to add new filters for authentication requirements.
Convert logicalplan back to promql query string instead of using promql direclty in MultiPartitionPlanner.

fix(query): MultiPartitionPlanner: Create series match query from logicalplan

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryOps.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityStore.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala
memory/src/main/scala/filodb.memory/format/ZeroCopyBinary.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

This infrastructure supports hierarchical cardinality queries of the abstract form:
```
Find (active, total) cardinality pairs for all time series with <shard-key-prefix>,
then group them by { key[:1], key[:2], key[:3], ... }.
```
Initialized with a `shardKeyPrefix` and an integer `groupDepth`, which specifies the "hierarchical depth" at which to aggregate the cardinalities.
Examples:
```
{ prefix=[], groupDepth=1 } -> {
prefix=["ws_a", "ns_a"] -> (4, 6),
prefix=["ws_a", "ns_b"] -> (2, 4),
prefix=["ws_b", "ns_c"] -> (3, 5) }
{ prefix=["ws_a", "ns_a"], groupDepth=2 } -> {
prefix=["ws_a", "ns_a", "met_a"] -> (4, 6),
prefix=["ws_a", "ns_a", "met_b"] -> (3, 5) }
{ prefix=["ws_a"], groupDepth=0 } -> {
prefix=["ws_a"] -> (3, 5) }
```
Note that …

feat(query):  add hierarchical cardinality query infrastructure

---

query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

- Metadata queries LabelValues/LabelNames have result type as String where as `Series` has Map type. This is causing MetadataRemoteExec to break as it is assumed that all metadata queries return map type result. The changes in PR make sure that depending on result type, appropriate result schema is set at the ExecPlan level. In MetadataRemoteExec, appropriate response is generated based on the query/result schema,

fix(query): Label values/names query to use String column type in ResultSchema

---

prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

The key is an empty map
```
/shard:/Map()
Map(_ns_ -> 1, host -> 1, _type_ -> 1, version -> 1, _metric_ -> 1, app -> 1, _ws_ -> 1)
```
Key contains the ws, ns and metric name
```
/shard:/Map(_ns_ -> filodb, _metric_ -> go_info, _ws_ -> local_test)
Map(_ns_ -> 1, host -> 1, _type_ -> 1, version -> 1, _metric_ -> 1, app -> 1, _ws_ -> 1)
```

feat(query) Enhance LabelCardinality query response to provide keys allowing multiple groups to be returned 

---

query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/test/scala/filodb/query/LogicalPlanSpec.scala

Fixes bug where:
```
TsCardinalities(Seq("a", "b", "c"), 2)
```
throws an `IllegalArgumentException` because `TsCardinalities` construction `require`d :
```
shardKeyPrefix.size > 2
```
instead of:
```
shardKeyPrefix.size >=2
```
Tests are now added to ensure `TsCardinalities` constructs/throws when appropriate.

fix(query): TsCardinalities requirement bug

---

prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Upon very long regular expression filters, lucene returns a StackOverflowError on every shard, and this has the potential to degrade performance of the cluster severely. The shard lock is not released and subsequent queries fail. The StackOverflowError has also been seen on ElasticSearch.
The stack overflow error we saw was for a regex filter of length 17k characters, and it was an unintentional regex which was not per intent. It used comma instead of pipe character to delimit list of possibilities. 
Since it is very hard to dive into the regex to explicitly allow and disallow certain …

bug(prometheus): Enforce maximum regex length

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala

Multi partition calls not supported
Label cardinality calls to support Multi partition calls, following two are the plans when the query is pushed down to local partition vs routed to remote partition
Call routed to remote partition
```
E~MetadataRemoteExec(PromQlQueryParams(go_info{_ws_=\"filodb-demo\",_ns_=\"App-0\"},1639513266,1,1639513566,Some(/api/v1/metering/cardinality/label),false), PlannerParams(filodb-query-service-local,None,None,None,10000,50000,12000,25000,false,0,0,false,false,false,true), queryEndpoint=http://localhost:9900/singlepartition/prometheus/api/v1/metering/cardinality/label, requestTimeoutMs=90000) on InProcessPlanDispatcher(filodb.core.query.QueryConfig@60992e88
```
Call pushed down to local …

feat(query) Allow supporting MultiPartition planning for LabelCardinality API

---

http/src/main/scala/filodb/http/PrometheusApiRoute.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

- add circe decoder to labelvalues and series-matcher query results to support multi-partition queries
- bug fix to return an array of tag values, instead of map, when the metadata query is only for single column

fix(query): add circe decoder to labelvalues and series-matcher query results

---

prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

See #1314 for the alternative fix.
Adds the method `Parser.queryToLabelMap(query: String): Map[String, String]` which parses an instant selector into a map of (label, value) pairs (including `__name__`).

feat(query): add Parser.queryToEqualLabelMap

---

query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

When only one label is provided to a label-values query with filters, the label itself is returned as the result.
A single tuple getter `._1` has been changed to `._2`, so values are now returned.

fix(query): label value metadata typo fix

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/PlannerHelper.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/DistConcatExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinExecSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/SplitLocalPartitionDistConcatExecSpec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala

Stitch creates an ``RvRange`` using a union of the children's ``RvRange``. This causes issues when Stitch is not the the top level operation and is under a ``BinaryJoinExec`` The lhs and rhs of Binary joins will not match causing inconsistent query results. 
``StitchRVSExec`` has been updated to now accept a ``RvRange`` that the user query expects. The union of ``RvRange`` therefore is not needed.

fix(query) StitchRVS to accept RVRange for the entire user provided start/step/end

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/ExecPlanSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

Adds a single filter that removes empty `SerializedRangeVectors` before they're sent over-the-wire.

fix(query): prevent serialization of empty RangeVectors

---

memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala

**Issue** 
Downsample job while applying sum based aggregate function on Histogram chunks (of type non-increasing bucket values), `formatCode` is being set to `HistFormat_Geometric_XOR`. To be precise in MutableHistogram.serialize. Later during ingestion these histogram chunks are marked as `InvalidHistogram`, because HistFormat_Geometric_XOR is not in valid format list (`isValidFormatCode`). and these chunks are ignored and never persisted. causing failures during query time.
**Fix**
for non-increasing geometric buckets, format code is set to `HistFormat_Geometric1_Delta` in BinaryHistogram.writeDoubles method.

fix(misc): fix formatCode for non increasing histogram buckets

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
project/Dependencies.scala

For metadata searches that need to enumerate values of fields, we end up iterating through matching documents and build a hash set of field values. This is inefficient. It eats up CPU creating bottlenecks in query execution, especially in high cardinality clusters and reduces overall query throughput.
This PR uses Lucene faceting which tremendously improves performance (by 300x) of label-value queries which is a major CPU consumer in the system today.
* Faceting is enabled in raw cluster and disabled in downsample cluster
* Faceting can be disabled in raw cluster via configuration
* If faceting is enabled, label-value queries automatically choose the efficient execution path. Otherwise, they fall back to existing …

feat(core): Lucene faceting for 300x more efficient label-value queries

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

**Current behavior :** Queries without `_ws_` key fails while creating exec plan
`foo{_ns_="foo"}` fails with bad request
**New behavior :** Enable ShardKeyRegexPlanner to utilize shardKeyMatcher columnFilters to derive the missing `_ws_` key
`foo{_ns_="foo"}` passes if `_ws_` info is available in shardKeyMatcher.

feat(query): support implicit workspace

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

Some `LogicalPlan`s left `ColumnFilter`s un-updated after `replaceFilters` was called. This fix correctly propagates `ColumnFilter` updates to all `LogicalPlan`s in a tree.

fix(query): update more filters from LogicalPlan::replaceFilters

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
project/Dependencies.scala

* DefaultSortedSetDocValuesReaderState is expensive to build. Using caffeine cache to keep it on the heap
* Add metrics for label-values latency and cache hit rate
* ability to enable faceting only for shard-key-labels

feat(core): Cache lucene DocValuesReaderState since expensive to build

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

MutableHistogram serialize method is using xor encoding (writeDoubles) for Geometric1_Delta. This results in faulty encoding during downsampling of Geometric histograms. With this change, serialize method will use delta encoding (writeDelta) for Geometric histograms.

fix(core): during serialization use delta encoding for Geometric1_Delta histograms

---

cassandra/src/main/scala/filodb.cassandra/metastore/CheckpointTable.scala

Following is supposed to be taken care after this [commit](https://github.com/filodb/FiloDB/commit/ac016af1220403401f095b9fda81e7fcf1df0f46):
`* Currently retaining default QUORUM consistency for ingestion writes, but will change to ONE in subsequent PR.`
Fixing the same now.

feat(cassandra): Use consistenly level ONE in ingestion pipeline

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

Recent updates redirected the flow of `TsCardinalities` logic in `ShardKeyRegexPlanner` to a matcher it should have never reached. This caused an exception whenever the timeseries cardinalities endpoint was used.
`TsCardinalities` is now classified as a metadata query by `ShardKeyRegexPlanner`. Now, it's sent directly to the child planner, and no exception is thrown.

fix(query): send TsCardinalities directly to child planner from ShardKeyRegexPlanner

---

query/src/main/scala/filodb/query/exec/SelectChunkInfosExec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

Fixes the broken _filodb_chunkmeta_all cli command
_filodb_chunkmeta_all command is broken. It generates the following output when running locally on a 2 node 4 shard setup
when `_type_` is not explicitly defined in the query.
```
./filo-cli --host 127.0.0.1 --dataset prometheus --promql '_filodb_chunkmeta_all(heap_usage{_ws_="demo",_ns_="App-0"})' --start 1646523084 
QueryError: NoSuchElementException None.get
QueryStats: TrieMap(List(local, raw, demo, App-0, heap_usage) -> (timeSeriesScanned=0, dataBytesScanned=0, resultBytes=0))
```
Test output of the newly added test without the fix:
```
class filodb.query.QueryError cannot be cast to class filodb.query.QueryResult (filodb.query.QueryError and filodb.query.QueryResult are in unnamed …
```

fix(query): handle empty first schema ID in SelectChunkInfosExec

---

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala
core/src/main/resources/filodb-defaults.conf

Changes TS cardinality names from:
```
active_timeseries_by_tenant
total_timeseries_by_tenant
```
to:
```
tsdb_metering_active_timeseries
tsdb_metering_total_timeseries
```

maint(coord): update TS cardinality metric names

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala

Currently we see this faceting exception when encountering long label values:
```
java.lang.IllegalArgumentException: category path exceeds maximum allowed path length: max=8191 len=20098 path=[hosts, xxxxxxxxxxx...
at org.apache.lucene.facet.taxonomy.FacetLabel.checkComponents(FacetLabel.java:96)
at org.apache.lucene.facet.taxonomy.FacetLabel.<init>(FacetLabel.java:72)
at org.apache.lucene.facet.FacetsConfig.processSSDVFacetFields(FacetsConfig.java:383)
at org.apache.lucene.facet.FacetsConfig.build(FacetsConfig.java:301)
at org.apache.lucene.facet.FacetsConfig.build(FacetsConfig.java:204)
at filodb.core.memstore.PartKeyLuceneIndex.addPartKey(PartKeyLuceneIndex.scala:432)
at filodb.core.memstore.IndexBootstrapper.$anonfun$bootstrapIndexRaw$1(IndexBootstrapper.sca …
```

bug(core): Skip facet for long label values

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

If time series partitions in shared are purged before they are evicted, then partIdsToEvict list can grow uncontrollably big. We need to prune this list regularly.
Thinking how to unit test this. Will add if I have an approach to do this.

bug(core): If purgeRate > evictRate, partIdsToEvict list can grow without size cap

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala

Looks like there are more error messages seen when label is not indexed such as 'dimension "foo_label" was not indexed'
So we are now catching all IllegalArgumentExceptions to not fail query.
And logging unexpected exceptions so they are not fully swallowed.

bug(core): Address more cases when label is not indexed

---

coordinator/src/main/scala/filodb.coordinator/FilodbCluster.scala
coordinator/src/main/scala/filodb.coordinator/ShardAssignmentStrategy.scala
coordinator/src/test/scala/filodb.coordinator/ShardAssignmentStrategySpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

Shard assignment is random, when deployed on Kubernetes  Deployment, when a pod(s) go down, the reassignment to shards to pods is random. This prevents using any state.
To use Kubernetes StatefulSets where we need state to be retained across pod restarts, we need a deterministic way to assign shards to pods. In stateful sets, the pod name has an ordinal at the end which can be used to assign shards to pods.

feat(coord) Stateful shard assignment

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
core/src/main/scala/filodb.core/query/QueryConfig.scala
query/src/main/scala/filodb/query/exec/ScalarBinaryOperationExec.scala
query/src/main/scala/filodb/query/exec/ScalarFixedDoubleExec.scala
query/src/main/scala/filodb/query/exec/TimeScalarGeneratorExec.scala
query/src/test/scala/filodb/query/exec/rangefn/ScalarFunctionSpec.scala

Scalar operations uses dispatcher with empty query config. This causes ``SingleClusterPlanner`` to use same ``InProcessDispatcher`` even for other operations like binary joins yielding undesired failures on query execution. 
EmptyConfig should not be used for anything apart from testing and all ``*Exec`` will explicitly be passed with a dispatcher with right config.

fix(query) InprocessDispatcher to use non empty query config

---

spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala
spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala

* Dont create new schedulers for each cardinality buster task that is serialized and sent to worker.
* Also include ability to do parallel cassandra writes
* Track cassandra write latency

bug(sparkJobs): Dont create new schedulers for each card buster task

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

```
% curl -i --location -g --request GET 'http://localhost:9900/ws-bar/api/v1/query_range?query=absent(sum_over_time(foo{_ns_="ns-bar"}[5m]))&start=1651815600&end=1651816200&step=60'
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
Content-Type: application/json
content-length: 515
Access-Control-Allow-Methods: GET
{
"status" : "success",
"data" : {
"resultType" : "matrix",
"result" : [ {
"metric" : {
"_ns_" : "ns-bar",
"_ws_" : "ws-bar"
},
"values" : [ [ 1651815600, "1.0" ], [ 1651815660, "1.0" ], [ 1651815720, "1.0" ], [ 1651815780, "1.0" ], [ 1651815840, "1.0" ], [ 1651815900, "1.0" ], [ 1651815960, "1.0" ], [ 1651816020, "1.0" ], [ 1651816080, "1.0" ], [ 1651816140, "1.0" ], [ 1651816200, "1.0" ] ]
} ]
},
"errorType" : …
```

fix(query): absent with sum_over_time result should be consistent

---

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

All `TsCardExec`-related operations should manipulate a single, empty-key `RangeVector` with rows of the form `[group, active, total]`. But `MetadataRemoteExec::mapTsCardinalitiesResponse` packaged rows of a remote response into individual, single-group `RangeVectors` of the form `key:group -> [active, total]`.
This fix instead packages these remote responses into the expected `[group, active, total]` format.

fix(query): TS card RemoteExec execute() now returns correct RV

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

The `ApplyInstantFunction` implementation of `replacePeriodicSeriesFilters` did not propagate filters to its `FunctionArgsPlan` children. Now, it recurses for these children, too.

fix(query): propagate ApplyInstantFunction column filters to FunctionArgsPlans

---

query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/test/scala/filodb/query/exec/ExecPlanSpec.scala

Previously, histograms were not handled by `ScalarOperationMapper`. Histogram-handler code has now been added.
Example: if `hist_metric` is a histogram, then
```
hist_metric{label="foo"} + 5
```
would throw an exception because `ScalarOperationMapper` would call `getDouble` on a `TransientHistRow`.

fix(query): add histogram case to ScalarOperationMapper

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/metadata/Dataset.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

Add support for multi-field facets to partition-key columns. This will optimize the metadata query lookups, If the dataset is hierarchical and there are heavy volume of multi-label value lookups.
- configured/enabled per dataset
- supports only partition-key string type columns

misc(core): add support for multi-field facets to partition-key columns

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Dataset.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala

earlier changes to DatasetOptions did not have code to set `multiColumnFacets` from config file. This PR fixes this bug.

fix(core): Dataset multiColumnFacets configuration to load from config file

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SinglePartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala

Currently the high level ``LogicalPlan``  is used to decide on whether to perform the Inprocess operation of delegate to one of the underlying planner instances. This causes operations like 
``sum(foo{} + bar:1m{})`` to be wrongly pushed to raw planner. Instead the data needs to be joined in process by pulling data from both raw and RR cluster
The plan is walked and only at appropriate level, the underlying planner is used to materialize the ``LogicalPlan``
Places where ``SinglePartitionPlanner`` is instantiated needs to change. We will need to pass ``DataSet`` instead of the metrics name.

fix(query) Pushdown in SinglePartitionPlanner

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
memory/src/main/scala/filodb.memory/data/Shutdown.scala

Halts the JVM if the QueryActor thread pool catches an InternalError left uncaught by the execution pipeline.

feat(coord): add JVM shutdown on QueryActor uncaught InternalError

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

Adding facet to identify label names associated with time series quickly.
Earlier we were identifying label names by querying just one time series and extracting label names from them. This does not work well for time series that have dynamic / inconsistent label names. This is not a great design pattern, but Kube State Metrics uses them to add dynamic metadata to time series.
With the facet, we find the label names quickly across all time series.
This is subsequently used by LabelCardinality query.

bug(core): Adding facet to find quickly find ALL label names for LabelCardinalityExec

---

core/src/main/scala/filodb.core/memstore/DemandPagedChunkStore.scala
memory/src/main/scala/filodb.memory/MemFactory.scala

If something is thrown during `DemandPagedChunkStore::copyToOffHeap` before anything was copied, then `endMetaSpan` will fail its requirement that metadata is written at least once. Since `endMetaSpan` exists in a `finally` clause, the requirement's `IllegalArgumentException` will "override" whatever was initially thrown.
This PR just logs the original `Throwable` and shuts down the JVM.

misc(core): populateRawChunks log/shutdown on caught throwable

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/query/QueryContext.scala
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinGroupingSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/SortFunctionSpec.scala

This PR adds query timeout checks so it happens more frequently in aggregations.
This is in response to very delayed timeouts especially for very-high-cardinality aggregations where we dont check for timeouts as often.

feat(query): Check for timeout between aggregations and joins

---

http/src/main/scala/filodb/http/PrometheusApiRoute.scala
query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala

InprocessPlanDispatcher throws AskTimeoutException always
Return empty result when AskTimeoutException is thrown and partial result is enabled. 
Also changed `partialResults` query parameter to `allowPartialResults`

bug(query): handle AskTimeoutException in InprocessPlanDispatcher

---

query/src/main/scala/filodb/query/exec/InProcessPlanDispatcher.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala

Partial results not getting generated for InProcessPlanDispatcher
Call timeout on `Task[QueryResponse]` with `clientParams.deadline`. Generate partial results when a timeout occurs and partial result is enabled

bug(query): partial results not getting generated for InProcessPlanDispatcher

---

memory/src/main/scala/filodb.memory/format/BinaryVector.scala
memory/src/test/scala/filodb.memory/BlockMemFactorySpec.scala
memory/src/test/scala/filodb.memory/BlockSpec.scala

**Issue**
On Mac M1, ``incNumBytes`` has a quirk. The operation fails with SIGBUS when a ``getAndAddInt`` is invoked on an address offset that is one of the three preceding every multiple of 16. For e.g when addrs is 13, 14, 15, 29, 30, 31, 45, 46, 47 byte offset from the base address, the operation ``UnsafeUtils.unsafe.getAndAddInt(UnsafeUtils.ZeroPointer, addr, inc)`` fails.  However, when we do a get and put non atomically, it works.  The fix is done to currently unblock developers from using M1 Mac. However, the fix is far from ideal as the data written to the block of memory by FiloDB is application specific and the block of memory is opaque to the operating system, in other words, the OS should not be interpreting this data as long as the application is working on the block it is …

fix(memory) BinaryVector fixes for M1 Mac

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

**Current behavior :** Currently downsample index migration job reads records from raw cluster's `pks_by_update_time` table and updates PartKeys table in downsample cluster. This approach has limitation that we can not run index migration jobs concurrently for multiple time windows, as we may update the record with stale data depending on the order which jobs are run.
**New behavior :** After this change, we read PartitionKey (if already exists) before writing and merge start/endtimes. Starttime will be the older and Endtime will be the later of the records merged.
**Note** This approach is still susceptible consistency issues, as the read data can become stale due to other writes that can happen. But this is not a big concern since only downsample index …

misc(downsample): merge partkey starttime endtime during index migration

---

project/Dependencies.scala

kamon library version upgrade which brings new transative dependencies
such as opentracing and protobuf-java.

maint(core): Upgrade kamon 2.2.2 -> 2.5.6

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala

Split queries (i.e. those whose individual leaf plans span more than one partition) are sent to each involved partition, and their responses are merged together. Currently, the `MultiPartitionPlanner` concatenates these child results with a `MultiPartitionDistConcatExec`. But this gives results where multiple `RangeVector`s may share the same key.
This PR replaces the `MultiPartitionDistConcatExec` with `StitchRvsExec`.

fix(query): change MPP split-query plan concat to stitch

---

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala

``MetadataRemoteExec`` as part of optimization  PR https://github.com/filodb/FiloDB/pull/1362, if the data response size is a singleton map, the key name is skipped and the values are returned as a list of strings. However, when a column given is incorrect and does not exist in index, the response has to be a map. 
The change checks if the labels given are more than 1 and responds with a string of lists or a singleton map accordingly.

fix(query) Metadata queries with one valid and one invalid tag returns garbled content

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

This fix is to make sure that Partkey's start and endtimes are overridden with raw cluster persisted values during migration.

fix(downsample): always merge with persisted raw cluster partkey during migration

---

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJobMain.scala

Since we read (for staleness check) before updating index, we don't have to catch up to current time.
Job run is idempotent now.  With this change, job will be run in cadence with Chunk Downsampler job by default.

fix(spark-job): make index job run only for downsample chunk window

---

core/src/main/scala/filodb.core/query/RangeVector.scala
http/src/test/scala/filodb/http/PrometheusApiRouteSpec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

Time series with label/values exceeding the default 4K container limit fail. The PR introduces a configurable container size based on ``ExecPlan`` providing flexibility in changing the container size instead of globally bumping the limits up to a higher value.
Creating a ``SerializedRangeVector`` for a timeseries with label name value pair length exceeding 4K fails. 
Creating a ``SerializedRangeVector`` for a timeseries with label name value pair length exceeding 8K will fail.  But the size of the container now can be tweaked at ``ExecPlan`` level instead of a globally set value.

fix(query) Configurable record container size in Metadata and PartKeysExec plans

---

coordinator/src/main/scala/filodb.coordinator/FilodbCluster.scala
coordinator/src/main/scala/filodb.coordinator/ShardAssignmentStrategy.scala
core/src/main/resources/filodb-defaults.conf

``K8sStatefulSetShardAssignmentStrategy`` currently falls back to default strategy if the host name resolution does not work. 
The current default strategy is not correct and silently will reassign shards to random pods defeating the purpose of having prebuilt index. We need to retry with backoff and see if we can assign shards meant for that pod and fail if its not possible to do so. 
Previously working  ``K8sStatefulSetShardAssignmentStrategy`` configured with deployment (which isn't the right configuration) will now fail instead of silently falling back to default strategy.

fix(coord) Stateful shard assignment strategy should fail if expected hostname resolution fails

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/query/QueryContext.scala

`targetSchemaMapper` utility is modified to accept list of `TargetSchemaChange`. This is needed as query planning can fall back to spread-to-all-shards strategy if there is a change in targetSchema config in the query-window.

misc(query): modify target-schema-mapper to accept list of schema changes over time

---

core/src/main/resources/filodb-defaults.conf
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
spark-jobs/src/main/scala/filodb/downsampler/Utils.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Adds an "export" step to the chunk downsampler Spark job.
A time-series is exported to a configured bucket address only if all of the following conditions are met:
- labels match (by equality; without a regex) at least one export rule key
- labels don't match any set of the rule's `exclude` filters
- the `include` filters are empty, or labels match at least one set of the rule's `include` filters
The export path is also configurable:
```
path-spec = [
"ws", "{{_ws_}}-foobar",
"year", "hello-<<YYYY>>",
"api", "v1",
"weird-ns-label", "{{_ns_}}"
]
```
This PR is a simpler alternative to: https://github.com/filodb/FiloDB/pull/1454

feat(downsample): add data export

---

conf/timeseries-durable-downsample-index-dev-source.conf
conf/timeseries-filodb-server-ds.conf
core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/memstore/IndexMetadataStore.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/FileSystemBasedIndexMetadataStoreSpec.scala

Currently on each restart, downsample index is rebuilt from source. This is an issue especially with large downsample stores where index rebuilds can take tens several minutes if not hours. Index is not something we should rebuild from scratch and we can possibly look at updating just the delta from the last sync time. 
We introduce a new implementation of ``IndexMetadataStore`` which uses file system for storing the metadata about index sync. Additionally we introduce the concept of ``INDEX_GENERATION`` which is environment variable used to trigger rebuild of index. It is designed to ensure the index is rebuilt only when a new, higher ``INDEX_GENERATION`` is seen and not otherwise.

feat(core) Persistent index checkpointing

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala

**Current behavior :** IllegalArgumentException when InProcessPlanDispatcher is being used for ExecPlans like EmptyResultExec. Following is an example query and its result.
**Example Query:** http://localhost:8080/promql/prometheus/api/v1/query_range?query=rate(my_counter{_ws_=”aci-telemetry”,_ns_=“Test-data-1667329278_p1”}[2d])&start=1667328078&end=1667329578&step=15
**Result:**
{
“errorType”: “IllegalArgumentException”,
“error”: “requirement failed: Current thread expected to startWith query-sched but was filo-standalone-akka.actor.default-dispatcher-3”,
“status”: “error”,
“queryStats”: []
}
**New behavior :** Avoiding this assert when InProcessPlanDispatcher is used.

fix(query): Avoiding the query scheduler thread assert when InProcessPlanDispatcher is used

---

conf/timeseries-filodb-server.conf
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala

**Current behavior :** Raw Queries doesn't track `dataBytesScanned` in QueryStats
**New behavior :** Updated the `RawDataRangeVector.rows()` to use CountingChunkInfoIterator to track dataBytesScanned

fix(QueryStats): Using CountingChunkInfoIterator in RawDataRangeVector.rows() to track dataBytesScanned

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala

Skips the DS export step if export is disabled in the config. `rdd.isEmpty()` is not performant when no rows are exported.

fix(spark): skip export step if disabled in settings

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/FindMyShards.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala

Currently, `SingleClusterPlanner::shardsFromFilters` always makes use of the final `TargetSchemaChange` from a sequence of changes. This PR adds logic to select the appropriate `TargetSchemaChange` given a query's range.

fix(query): select correct TargetSchemaChange over time

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/IndexMetadataStore.scala
core/src/test/scala/filodb.core/memstore/FileSystemBasedIndexMetadataStoreSpec.scala

``DownsampleTimeseriesShard`` was incorrectly reading the name of the environment variable instead of the value stored in that environment variable to find the generation of the index. The fix now reads the desired value.

fix(core) Correctly read env variable value for index generation

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Schemas.scala

- additional schema types to support ingestion/querying of pre-aggregated metrics - `preagg-gauge` and `preagg-delta-counter`. 
- no additional schema type is needed for `delta-histogram`, as it suffices for both raw and pre-aggregated metrics as they have same data-schema/columns.

feat(preagg): schema types to support ingestion pre-aggregated metrics

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Adds a configurable `drop-labels` sequence to export rules. If an export rule is applied to a row, any labels specified in `drop-labels` will be excluded from the exported data.
This PR also changes how rules are defined. Keys now apply to groups of rules; the group is iterated until an applicable rule is found. The benefit of this setup is that rule "modifiers" (i.e. `drop-labels`) can be specified for different sets of time-series.
```
groups = [
{
key = ["ws-foo"]
rules = [
{
allow-filters = [
["_ns_=\"my_ns\"", "bar!=\"baz\""],
["_ns_=\"my_other_ns\""]
]
block-filters = [
["_metric_=~\".*bad_suffix\""]
]
drop-labels = ["label1", "other_label"]
}
]
}
]
```
- Configurable output file format.
- JSON label-value pairs in the output.
- Various performance …

feat(downsample): exclude labels from export

---

.travis.yml
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/resources/filodb-defaults.conf
gatling/src/test/scala/filodb/gatling/QueryRangeSimulation.scala
http/src/main/scala/filodb/http/PrometheusApiRoute.scala
project/FiloSettings.scala
scripts/schema-truncate.sh

Reject queries before they are accepted into the queue if the system is overloaded thereby reducing latencies for queries that come later, and increasing overall throughput and availability of system. Reduce query timeouts and improve client experience.
https://monix.io/docs/current/catnap/circuit-breaker.html
```
circuit-breaker {
enabled = false
open-when-num-failures = 5
reset-timeout = 30 seconds
exp-backoff-factor = 1.5
max-reset-timeout = 5 minutes
}
```
* 1 FiloDB node with 8 shards, 4GB Heap, on M1-Max dev machine
* Ingestion completed. Ingestion not running during query load.
* 5k cardinality 1-to-1 binary join + aggregate query for 3 hours with step of 1min. sum(foo+bar) type query.
* 20 queries per second
* 3 minutes long
* Queries hit FiloDB …

feat(coord): Circuit Breaker to protect query engine from overload

---

query/src/main/scala/filodb/query/LogicalPlan.scala

``HighAvailabilityPlanner`` routes the query to its buddy cluster if the local cluster is unavailable. The field ``isRoutable`` of the ``LogicalPlan`` is used to determine if the query needs to be routed to the buddy cluster or executed locally. Operations like ``vector(0)``, ``1 + 2`` need not be router and does not need local FiloDB shards to be up and running as the query layer can run these operations without FiloDB. If however, we need to run the operation on FiloDB and FiloDB is not available, the query execution will fail with message ``Shard: x is not available``.  
For ``BinaryJoins`` the plan's routablity should be determined by the routablity of lhs or  rhs. That is, if either lhs or rhs needs to FiloDB for execution, it should be routed. The the check should use ``||`` instead …

fix(query) routing binary joins in HAPlanner

---

coordinator/src/multi-jvm/scala/filodb.coordinator/ClusterRecoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
jmh/src/main/scala/filodb.jmh/QueryAndIngestBenchmark.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeInstantFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RateFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala

This PR adds support for calculating the rate of change of Otel delta metrics using the rate function.
Previously, the rate function could only be used with counter metrics. With this change, users can now apply the rate function to any Otel delta metric, which will allow them to more easily identify trends.
To use the rate function with Otel delta metrics, simply pass the metric and a time interval to the function as you would with any other time series. The function will return a new time series containing the per-second average rate of change for each time step in the original time series.
Examples:
`rate(otel_delta_metric_name[5m])`
This PR also includes tests to ensure the correct behavior of the rate function with Otel delta metrics.
**CHANGES**
An …

feat(query): support rate/increase functions over OTel-style delta metrics

---

core/src/main/scala/filodb.core/query/ResultTypes.scala
query/src/test/scala/filodb/query/ResultTypesSpec.scala

When comparing ResultSchemas, `isCumulative` field will be ignored. This field is used only at the leaf node to pick the right `rate` function depending on whether the ColumnType is cumulative type or not.

fix(query): ignore isCumulative field when comparing ResultSchemas

---

query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala

`idelta` function is applicable only to gauge types. This PR reverts the changes made to `idelta` function as part of #1498

fix(query): iDelta is applicable only to gauge types

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala

Right now shardKey labels need to be explicitly defined in target-schema config.
With this change, target-schema config implicitly includes shardKey labels. Missing shardKey labels will be included in targetSchema while calculating ingestion/query shards. This simplifies queries to not include shardKey labels in join/group-by queries.

fix(misc): make shardKey labels in targetSchema config implicit

---

query/src/main/scala/filodb/query/exec/SetOperatorExec.scala
query/src/test/scala/filodb/query/exec/BinaryJoinSetOperatorSpec.scala

Currently, a join such as
```
sum(foo{}) AND bar{}
```
will erroneously return `sum(foo{})` if `bar{}` returns no data.
The logic in `setOpAnd` can be described as two sequential parts:
1. Create a set of all join keys on the RHS.
2. Add a RangeVector from LHS to the result iff its join key appears in the RHS set.
The bug is two-fold:
- At the first step, the logic skips a join key if its vector contains no rows; the key is not added to the RHS set.
- At the second step, we check that the RHS contains each LHS join key. For each key it doesn't contain, the logic falls into an `else if` condition: the LHS vector is added to the result if its join key is empty.
Since the first step won't add the key to the RHS set, the second step will fall into the `else if` and …

fix(query): treat empty join key as any other during AND join

---

prometheus/src/main/scala/filodb/prometheus/parse/AntlrParser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Currently, queries with bracket-notation range durations such as:
```
foo{label1="value1"}[2d0h15m]
```
will fail to parse because
- `prometheus.ast.Duration` was used to find the millisecond-duration of each unit-value pair.
- `Duration`s cannot have zero value.
This PR adds logic to skip construction of a `Duration` when a unit's value is zero.

fix(parser): add support for zero-duration time range units

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

Lucene regex does not support anchor operator such as ^ and $. https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-unsupported-operators Remove those characters from users' regex so that Lucene can handle it.
- Over the wire formats for Akka …

fix(core) Conform to Lucene regex by removing leading ^ and ending $.

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala

The current logic incorrectly finds a partition hash when a target-schema is applied; it always includes the metric label in the hash computation. This PR removes the metric label as an implicit target-schema label.

fix(query): exclude metric from implicit target-schema labels

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordBuilder.scala
core/src/test/scala/filodb.core/binaryrecord2/BinaryRecordSpec.scala
version.sbt

cherry-pick: e589063cfb244fc6bb5659d628378024ca668349
fix(query): exclude metric from implicit target-schema labels (#1518)

cherry-pick from develop to main

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

A query like this ts{label=""} should return the data when the label is an empty string or label is not present. Fix this bug by translating Equals("") and EqualsRegex("") to NotEqualsRegex(".+")
- Changes to the HTTP …

fix(core) Fix query on empty labels.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala

**Current behavior :** Metadata requests with metric regEx in match filter are currently failing with parser error
```
Request: LabelNames with filter match[]={__name__=~".*up.*",foo="bar"}'
Response: 
{
"status" : "error",
"data" : null,
"errorType" : "invalid_query",
"error" : "Cannot parse [.*up.*{foo =\"bar\"}] because at 1:0 token recognition error at: '.*'"
}
```
Should return valid response
```
{
"status" : "success",
"data" : [ "__name__", "foo" ..],
"errorType" : null,
"error" : null
}
```

fix(query) support regEx for metric in metadata queries

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
gatling/src/test/scala/filodb/gatling/QueryRangeSimulation.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/rangefn/InstantFunction.scala

`foo or vector(0)` like queries are very common. Current plan materialization results in SetOperatorExec which is expensive since it transmits data over the network and uses more memory. 
A more optimal implementation would be to apply an InstantFunctionMapper to convert the NaNs to 0s. This plan is memory efficient and does not write results to the wire unnecessarily. This is what this PR delivers.
Unit tests cover query planning.
Local performance test shows 25% reduction in average latency. 
Gatling Test Results were run for query `heap_usage0{_ns_="App-0",_ws_="demo", host="H1"} or vector(0)`
1 FiloDB node, 8 shards
2G heap, M1 mac
10 queries per second
Cardinality of result 1250
Time range queried: 3h
Step: 60s
``` …
```

feat(query): Query Planning optimization for 'or vector(0)'

---

core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala

- [ x ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
With the support for rate/increase functions for Delta metrics, rate/increase functions' behavior for `untyped` metrics changed. 
This PR is to make sure we preserve the old behavior of rate/increase functions on `untyped`, apply as if they are cumulative.
Only `untyped` schema doesn't have `detectDrops` attribute, this code change uses it to determine if the column is of type `untyped` .

misc(query): treat untyped as counter for the purpose of rate/increase functions

---

coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardAssignmentStrategy.scala
coordinator/src/main/scala/filodb.coordinator/client/NodeCommands.scala

Current strategy of assigning shards to pods is to look at the ordinal of the host name when using stateful sets. The hostname is looked up using reverse IP lookup of the  coordinator Actor. 
The strategy will fail when reverse lookup from ip cannot be done reliably. To eliminate this reverse lookup, we add a way to query the coordinator actor to provide its hostname.

fix(coord) Alternative host lookup strategy to avoid reverse lookup of ip address

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Currently, label-values are exported with unescaped double-quotes, which will prevent them from parsing correctly. This PR makes the following changes:
- Escape all unescaped commas and unescaped single-quotes.
- Always wrap label-values in single-quotes.

update exported label-values

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/scala/filodb.core/metadata/ColumnSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala

Add param `delta=true` to delta-counter/delta-histogram to denote the columns are periodic/delta temporal metrics. While querying this param is used to determine whether to apply prom-rate/increase function or non-cumulative rate/increase variant.

misc(query): treat all double columns except delta as cumulative for rate func

---

query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala

max(histogram) is not supported histogram_quantile(1, histogram) may be what users want.

fix(core) message use histogram_quantile for max(histogram) queries.

---

query/src/main/scala/filodb/query/exec/aggregator/RowAggregator.scala

The column for count_values aggregator is StringColumn.

fix(core) fix count_values query.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala

Queries like `sum(rate(foo{}[long look back])) or vector(0)` fail to materialize. This is a `BinaryJoin` with `rhs`  having  a `ScalarFixedDoublePlan`. Long time range planner for long lookbacks exceeding raw cluster retention get pushed down to downsample cluster and changes the end time. Following code in LongTimeRangePlanner specifically did this update to end time
```
copyLogicalPlanWithUpdatedTimeRange(periodicSeriesPlan,
TimeRange(periodicSeriesPlan.startMs, latestDownsampleTimestampFn + offsetMillis.min))
```
The issue however comes from the fact that ``ScalarFixedDoublePlan`` uses seconds precision but `lhs` of the `BinaryJoin` stores the milliseconds for end time without truncation which causes the assertion in `BinaryJoin` to check the end date to fail.
Since …

fix(query) Long lookback queries with or vector() operations fail to materialize

---

prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Streaming aggregation creates new metric names of the format {metric_name}:::{rule_name}. The current `toLogicalPlan` method incorrectly splits the aggregated metric name into a metric name and column name. For example, for following aggregated metric, where no column name is specified, the regex breaks the metric name into following:
1. "http_requests_total:::aggregated_rule" --> metric_name: (http_requests_total:) column_name: (aggregated_rule)
**New behavior :** Fixed the regex used to accommodate this scenario

fix(query): Updating Regex to support preagg metric names with column selector

---

core/src/main/scala/filodb.core/query/QueryContext.scala
core/src/test/scala/filodb.core/query/QueryContextSpec.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala

Currently we throw an exception if group by cardinality is high.
Throw an exception for high group by cardinality but also add warning if we go beyond warning level of group by limit. We also properly record in the logs the query and where it comes from.

Adding limits enforcement for group by clause.

---

core/src/main/scala/filodb.core/query/QueryContext.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala

- [] Tests for the changes have been added (for bug fixes / features) ?
Current behavior :
Currently we throw an exception if binary join input cardinality is high.
New behavior :
Throw an exception for high binary join cardinality but also add warning if we go beyond warning level. We also properly record in the logs the query and where it comes from.

Check for the binary join input cardinality

---

core/src/main/resources/filodb-defaults.conf

Schema changes are needed in order to support rate over aggregated counters.

fix(misc): preagg-delta counter/gauge schema changes

---

core/src/main/resources/filodb-defaults.conf

fix default-value column from preagg-delta-counter to `sum` column.
This is not a breaking change, as schema-hash doesn't change.

fix(preagg): fix default-value column for preagg-delta-counter

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala

We check if number of data scanned and produced by exec plan is within the limits given properties and defaults in the codebase. 
We add explicit check on the number of time series and allow to WARN the users that he is breaching a soft limit. We get the quotas from outside of FiloDB runtime. 
Removal of property max-data-per-shard-query

adding warning and enforcement for ts scans/exec plan outputs

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/downsample/ChunkDownsampler.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Histogram Sum ChunkDownsampler function is using MutableHistogram (double type), causing serialization to fail. This code change is to convert the MutableHistogram back to LongHistogram type to use Delta encoding.

fix(ds-jobs): fix delta-histogram chunkdownsampler to use LongHistogram

---

core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

This PR adds support for "data-shape" metrics from downsample shards; these Kamon metrics expose data about downsampled time-series, namely:
- label key-length
- label value-length
- label count
- metric name length
- total label length (i.e. sum of all label key/value lengths)
- histogram bucket count
Importantly, these metrics are populated/published outside of any critical ingestion or query flow. The metrics are also enabled/disabled via a feature flag.

feat(downsample): support data-shape metrics from DS shards

---

core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala

Recently-added documentation breaks `sbt doc`. This PR fixes the documentation.

fix(downsample): scaladoc fix

---

core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Currently, data-shape-key labels are published if `enable-data-shape-key-labels=true`. For example, suppose data-shape stats are updated for the time-series:
```
my_metric{label1="foo", label2="bar"}
```
If `data-shape-keys=[label1, label2]` and `enable-data-shape-key-labels=true`, then the stats would be updated as e.g.:
```
data_shape{dimension="label-count", label1="foo", label2="bar"}
```
But if the `data_shape` metric is, by default, published with its own `label1` and `label2`, then these labels will not be updated to reflect those from `my_metric`.
This PR adds substitute labels `data-shape-key-publish-labels`. Now, if data-shape stats were updated for the same metric above,  and:
```
data-shape-key-publish-labels=[substitute1, substutute2]
```
then the …

feat(downsample): add substitute data-shape-key labels

---

core/src/main/scala/filodb.core/downsample/DownsampleConfig.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala

Currently index rebuild and housekeeping scheduler uses number of CPUs as a a factor for parallelism with no way to tune this. This PR introduces a multiplier that either allows is to increase or reduce the parallelism using a configuration. The default value is 1 which will use the existing parallelism, that is the value returned by ``Runtime.getRuntime.availableProcessors()``

feat(core) Allow tuning parallelism of index rebuild and housekeeping scheduler

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
cassandra/src/main/scala/filodb.cassandra/metastore/CassandraMetaStore.scala
cassandra/src/main/scala/filodb.cassandra/metastore/CheckpointTable.scala
core/src/main/resources/filodb-defaults.conf
core/src/test/resources/application_test.conf

Current level of read/write consistency levels for  tables (across all datasets)
| Table      | Read Consistency | Write Consistency     |
| :---        |    :----:   |          ---: |
| IngestionTimeIndexTable      | ONE       | ONE  |
| PartitionKeysByUpdateTimeTable   | ONE        | ONE      |
| PartitionKeysTable   | ONE        | ONE      |
| TimeSeriesChunksTable   | ONE        | ONE      |
| CheckpointTable   | LOCAL_QUORUM        | ONE      |
Refactored read/write consistency levels for  tables (across all datasets)
| Table      | Read Consistency | Write Consistency     |
| :---        |    :----:   |          ---: |
| IngestionTimeIndexTable      | LOCAL_ONE       | LOCAL_ONE  |
| PartitionKeysByUpdateTimeTable …

refactor(cassandra): Revisit config for read/write consistency levels

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Schemas.scala

add column `tscount` to preagg-histogram schema to capture underlying time series counts during aggregations

misc(core): add column to capture timeseries count to preagg histogram

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala

Disabling the orVectorDouble optimization
**New behavior :** Disabled the `or vector(double)` optimization until we fix the required corner cases

Disabling the orVectorDouble optimization

---

core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala

**Current behavior :** (link exiting issues here : In our `RocksDBCardinalityStore`, we store records of type `CardinalityValue`. This data structure stores a string which is the last value of the shardKey Seq. However, from the implementation, it doesn't seem to be used ( TODO:  check with Amol and Vish ). 
**New behavior :** Removing `name` from CardinalityValue data structure to optimize the storage

Removing `name` from CardinalityValue data structure to optimize the storage

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityStore.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala
core/src/test/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStoreSpec.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

*Motivation:* Updating CardinalityRecord class to use CardinalityValue, since all the member variables of CardinalityValue is also duplicated in CardinalityRecord. Updating the CardinalityRecord to use CardinalityValue to simplify the class definition, which also reduces the need to convert CardinalityTracker to CardinalityValue, when writing to RocksDB. This will also help in future changes when the storage format changes ( let's say new member variables or reducing variables ) 
*Current Behaviour*: `CardinalityRecord` class contains the super set of member variables present in `CardinalityValue`. 
*New Behaviour*: Updating `CardinalityRecord` to use `CardinalityValue` class instead.

Updating CardinalityRecord class to use CardinalityValue

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlannerSpec.scala

…bqueries with regular expressions.
In multipartition settings TopLevelSubquery logical plans are forwarded to the remote systems with invalid start/end time.
In multipartition settings when regex is used, SubqueryWithWindowing plans are forwarded to the remote systems with invalid start/end time.
Correct start/end times are used.
No breaking changes.

fix(query): TopLevelSubquery and SubqueryWithWindowing remote forwarding invalid start/end parameters fix

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysV2Table.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
scripts/schema-create.sh
scripts/schema-truncate.sh
spark-jobs/src/main/scala/filodb/cardbuster/CadinalityBusterMain.scala
spark-jobs/src/main/scala/filodb/cardbuster/PerShardCardinalityBuster.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopierValidator.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala

Today, we have one table per shard for storing part keys.
This (work-in-progress) PR explores storing all part keys in one table. 
This is to reduce Cassandra compaction cost incurred due to numerous tables.
All features hidden behind feature flag.
These are the read/write path considerations in the design of Cassandra schema
* should be able to load contents of shard efficiently for index bootstrap
* should be able to read/write single part key efficiently for regular ingestion operations
* Should be able to do cardinality busting
* Should be able to do index migration for downsampling
* Should be able to repair across DCs
TODOs for later:
* Performance Testing
* Data migration plan

feat(cass): Consolidate to one partkey table instead of table per shard

---

.github/workflows/runtests.sh

Fixing 404 issue while downloading cassandra for unit tests. Updating to use the archive.apache dist to avoid 404 errors.
**Current behavior :** unit tests *are not* successfully completing for pull requests
**New behavior :** unit tests *are* successfully completing for pull requests

Fixing 404 issue while downloading cassandra for unit tests

---

query/src/main/scala/filodb/query/ProtoConverters.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala

``AskTimeoutException`` is deserialized as ``Throwable``
Fixes the deserialization to deserialize the specific exception class.

fix(query) Handle Akka AskTimeoutException serialization explicitly

---

core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala

**Current behavior :**  CardinalityTracker support delta of cardinality counts in values of 0 or 1. All these updates is stored to RocksDB when the modifyCount is called. 
However, in downsample cluster, we have a burst write scenario, since we read all the partKeys from the index and update the cardinality count from scratch. With the existing `modifyCount` method, we are running into heavy disk write scenarios which increases the time needed to measure cardinality in downsample clusters.
**New behavior :** To mitigate the above scenario, I am adding additional data-structures in CardinalityTracker, which stores aggregates count in memory and flushes to RocksDB on a static threshold (to avoid storing all cardinality records in memory and to avoid the memory …

Changes in CardinalityTracker to store cardinality count in Downsample cluster

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/main/scala/filodb.core/query/ResultTypes.scala
core/src/test/resources/application_test.conf
grpc/src/main/scala/filodb/grpc/GrpcCommonUtils.scala
query/src/main/scala/filodb/query/ProtoConverters.scala
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/BinaryJoinExec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala

- No configuration available for gRPC max inbound message size
- Fixed 4k record container size
- Deserializing  ``QueryLimitException`` gives ``Throwable``
- Adds default max incoming message size allows configuration of this value
- Default 40k record container size for ``TopK``, ``BottomK`` and ``CountValues``. Allows overriding these values in config
- Exception type preserved in deserialization of  ``QueryLimitException``

fix(query) gRPC exception serialization and container size fixes

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/test/resources/application_test.conf
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/PromQlRemoteExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

We use a fixed 4k buffer for record containers 
We change the container size 40k or any other configurable value for ``Topk``, ``BottomK`` and ``CountValue`` aggregation

fix(query) Configurable record container sizes for topK, bottomK and countValues

---

coordinator/src/main/scala/filodb.coordinator/ActorPlanDispatcher.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/QueryScheduler.scala
coordinator/src/main/scala/filodb.coordinator/ResultActor.scala
coordinator/src/main/scala/filodb.coordinator/queryengine/Utils.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/test/resources/application_test.conf
http/src/main/scala/filodb/http/PromQLGrpcServer.scala
query/src/main/scala/filodb/query/ProtoConverters.scala
query/src/main/scala/filodb/query/ResultTypes.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/main/scala/filodb/query/exec/SelectRawPartitionsExec.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala
query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala

Improve performance of Query Result Streaming by 
1. Adding multiple (configurable number) RVs within one streaming StreamQueryResult  message. This was needed since performance tests with one RV per akka message created a bottleneck in Akka Remoting. `[2023-03-23 12:45:13,666] WARN  filo-standalone-akka.actor.default-dispatcher-34 akka.remote.EndpointWriter [akka.tcp://filo-standalone@127.0.0.1:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Ffilo-standalone%40127.0.0.1%3A63524-1/endpointWriter] - [79284] buffered messages in EndpointWriter for [akka.tcp://filo-standalone@127.0.0.1:63524]. You should probably implement flow control to avoid flooding the remote connection.`
2. Use one result actor to receive streaming query results from …

perf(coord): Improve performance of result streaming

---

coordinator/src/test/scala/filodb.coordinator/client/SerializationSpec.scala
core/src/main/scala/filodb.core/query/RangeVector.scala

While serializing range vectors the first ``SerializedRangeVector`` (SRVs) contains a reference to all the ``RecordContainers`` and when multiple SRVs are serialized the behavior causes two problems
-  The result bytes are double counted, once as part of the first SRV and another time as part of subsequent SRVs that contain just the required record containers
- When serializing using gRPC, the message may exceed the 4 MB limit and transmits twice the required bytes over the wire. 
The issue isn't seen as part of Kryo serializer as the serialization is smart enough to preserve the references and not serialize the container twice. Also on the receiving side the deserialized values reference the same Record container not creating duplicate …

perf(coord) ensure the first SRV does not contain all record containers

---

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityManager.scala
core/src/test/resources/test_dataset.conf
core/src/test/resources/test_dataset_not_prometheus.conf
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityManagerSpec.scala

Fixing exception when getting num-shards from config. 
*Behaviour Before:* wrongly interpreted the dataset-config to be an array of Config object. Instead it is an array of string, where each string is the file path to the dataset config. Because of this mis-interpretation, we were throwing an exception.
*Behaviour After:* Fixed this misinterpretation and parsing the dataset-configs from the file. Referenced the parsing behavior from FiloSettings.scala

fix(downsample): Fixing exception when getting num-shards from config

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
version.sbt

Currently, we prepare series for export by wrapping comma-containing label-values in single-quotes. This PR instead wraps them in double-quotes.

fix(export): re-add double-quotes around label-values with commas

---

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityManager.scala

Change semantic to not throw error to avoid query exceptions when metering is not enabled
**Current behavior :** We would throw query exceptions if metering is not enabled in Tsdb dowsample. This will lead to complication on the query planner side to make sure the config is followed for remote partition calls. Hence, to simplify it, we are returning empty responses if metering is not enabled with a log.
**New behavior :** Return empty response instead of throwing exception.

fix(downsample): Change semantic to not throw error to avoid query exceptions when metering is not enabled

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala

If rounding results in 0, the number of CPUs are 0 which is an error
We use the max of the CPU multiplied by the scaling factor of 1 ensuring we never get 0 CPUs

fix(downsample) Minimum CPU to use is 1

---

cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala
conf/timeseries-dev-source.conf
coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala
coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/Utils.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesStore.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesMemStore.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesStore.scala
core/src/main/scala/filodb.core/store/IngestionConfig.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/DemandPagedChunkStoreSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
jmh/src/main/scala/filodb.jmh/HistogramIngestBenchmark.scala
jmh/src/main/scala/filodb.jmh/HistogramQueryBenchmark.scala
jmh/src/main/scala/filodb.jmh/IngestionBenchmark.scala
query/src/test/scala/filodb/query/exec/InProcessPlanDispatcherSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/SplitLocalPartitionDistConcatExecSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Today scaling filoDB horizontally involves re-calculation of memory settings in a manual way involving tribal knowledge.
This PR aims to automate it and make it simple math. It is backward compatible and behind feature flag.
* Min-num-nodes moved from dataset into server config.
* New server config will drive automatic memory calculation
* Each dataset requires another configuration that determines what fraction of resources each dataset gets.
```
memory-alloc {
automatic-alloc-enabled = false
os-memory-needs = 500MB
lucene-memory-percent = 20
native-memory-manager-percent = 20
block-memory-manager-percent = 60
}
```

feat(core): Simplify configuration to scale Filodb horizontally

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

We don't produce logs when scan byte warnings are generated.
Produce logs when scan byte warnings are generated.
n/a

Adding logging statement when warning is produced.

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

Cherry pick [Adding logging statement when warning is produced](https://github.com/filodb/FiloDB/commit/96acbc7b7b4b2a404f572451cb525c5beaca0485)

Adding logging statement when warning is produced. (#1625)

---

core/src/main/scala/filodb.core/query/RangeVector.scala
memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/aggregator/SumRowAggregator.scala

Double.isNan involves conversion to boxed java Double
Local heap profiling showed that this is a significant allocation.
Conversion to the static java.lang.Double.isNan removes these.

perf(query): Remove boxed Double allocations from NaN checks during data scans

---

core/src/main/scala/filodb.core/query/PartitionTimeRangeReader.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

Some queries occasionally hit exceptions because of empty histogram. However, the same exception could not be reproduced later. The hunch is that the bug is caused by a race condition. So, adding additional debugging log to print out the chunk id chunk info and the memory dump.
- …

fix(core) add debugging info for empty histogram.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala

Currently, target-schema logic will throw an exception when a pushdown-candidate aggregation or join contains no column filters, e.g.:
```
sum(vector(123)) by(foo)
vector(123) + on(foo) vector(123)
```
This happens because a list of leaf column filters Is collected, and the head of that list is accessed without an `isEmpty` check.
This PR adds the missing check.

fix(query): prevent list.head on empty list

---

kafka/src/main/scala/filodb/kafka/KafkaIngestionStream.scala

Manually create a more-informative client ID for per-shard Kafka consumers.
Local tests log the following output (`INSTANCE_ID=1234` and `shard=0`):
```
[Consumer clientId=filo-db-timeseries-ingestion.1234.0, groupId=filo-db-timeseries-ingestion]
```

maint(kafka): update consumer client id

---

conf/promperf-filodb-server.conf
conf/timeseries-filodb-server.conf
coordinator/src/main/scala/filodb.coordinator/FilodbSettings.scala
coordinator/src/main/scala/filodb/coordinator/v2/FiloDbClusterDiscovery.scala
coordinator/src/test/scala/filodb.coordinator/FiloDbClusterDiscoverySpec.scala
core/src/main/resources/filodb-defaults.conf

There are two configs for num-nodes used by clustering-v2 and automatic memory alloc code.
Consolidating them.

fix(core): Consolidate num-nodes duplicate config

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

Queries like ``foo{dummy=~".*"}`` are expected to match all timeseries with metric name foo even without the label dummy, in short, the filter should have same behavior as not having the filter. However, currently the matches are only made for series with the label present
The above behavior is fixed and now the label is not considered in matching if it matches an empty string ``""``

fix(query) Regex equals .* must ignore the label and match series even without the label

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

Regression in behavior when ``.*`` is used as label filter
If ``.*`` is used in query label, just match all docs
Credit:
Thanks @vishramachandran for catching the regression.

fix(query) Fix regression with regex match

---

core/src/main/scala/filodb.core/binaryrecord2/RecordContainer.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
core/src/test/scala/filodb.core/query/SerializedRangeVectorSpec.scala
query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala

There was a bug in calculating size of SRV.
Earlier, for efficiency purposes, we were calculating the size of the containers associated with the SRV.
But actually, the container can home multiple SRVs. So the calculated size for several SRVs at a time can end up wrong with addition of cumulative counts.
The fix for now is to calculate the size by going through the records. It introduces a small inefficiency here, but submitting this PR for now since other ways to calculate this were more invasive and risk regression. We can have an optimization of this if really needed later. I have also reduced the number of calls to this method from two to one.
The unit tests didn't catch this since earlier since they played with one SRV only.
I have now added a unit test that …

fix(core): Bug in calculating size of SerializedRangeVector

---

core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
run_benchmarks.sh

Production profiling is showing that Lucene Regex automata is creating a hotspot in method and allocation profiling.
This PR optimizes two kinds of queries
1. Regex with enumerated values are converted to `TermInSetQuery`
2. Regex with prefix is converted to `PrefixQuery`
It also wraps Lucene queries in `ConstantScoreQuery` to prevent any scoring that may be happening.
Observed 
* 2.2x performance improvement in JMH benchmark for specific enum regex query
* 1.5x performance improvement in JMH benchmark for specific prefix regex query
Detailed Benchmark results
```
After
[info] Benchmark                                                   Mode  Cnt     Score    Error  Units
[info] PartKeyIndexBenchmark.partIdsLookupWithEnumRegexFilter     thrpt    5  7754.992 ± …
```

perf(core): ~Two times throughput improvement for Lucene queries with enum and prefix regex filters

---

core/src/main/scala/filodb.core/query/PartitionTimeRangeReader.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala

* filodb(core) add debugging info for empty histogram. Some queries occasionally hit exceptions because of empty histogram. However, the same exception could not be reproduced later. The hunch is that the bug is caused by a race condition. So, adding additional debugging log to print out the chunk id chunk info and the memory dump. ---------
Co-authored-by: Yu Zhang <yzhang999272@apple.com>
(cherry picked from commit 90303aaff71dd435091148871861bb84d719c9ae)
path for existing …

filodb(core) add debugging info for empty histogram. (#1613)

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/test/scala/filodb/query/LogicalPlanSpec.scala

**Current behavior :** For remote metadata exec calls, we are passing FiloDB datasets instead of user passed datasets.
**New behavior :** Updating the TsCardinalities logical plan to take userDatasets ( which is a csv string ) and using it for RemoteMetadataExec calls.

fix(query): Adding user datasets for Cardinality V2 RemoteMetadataExec calls

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

**Current behavior :** We have two issues regarding multi partition cardinality queries:
1. Multipartition cardinality queries for workspace and namespace are failing because of the url params were getting overwritten at a later stage in the code flow causing query to fail.
2. multi partition cardinality V1 query was throwing schema mis match errors.
**New behavior :** Fixes for the above scenarios were added.

fix(query): MultiPartition Cardinality Queries

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/LogicalPlanSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

**Current behavior :** Multipartition cardinality queries for v1 and v2 were not working as expected, because of - 
1. Schema mismatch for remote v1 cardinality queries
2. User datasets were not being passed
3. URL Params were getting overwritten for remote metadata exec calls.
**New behavior :** Fixes added for the above bugs.

fix(query): Cardinality multi partition queries

---

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

**New behavior :** Adding new cluster name to override the value in SingleClusterPlanner. This is necessary to provide the right cluster name value to SingleClusterPlanner.materializeTsCardinalities for FiloDB cardinality queries. 
Need an update to TsCardinalities LogicalPlan on the query planner side.

fix(metering): Overriding the cluster name .passed to SingleClusterPlanner for TenantIngestionMetering changes

---

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

Overriding the cluster name passed to SingleClusterPanner for TenantIngestionMetering changes.
New behavior : Adding new cluster name to override the value in SingleClusterPlanner. This is necessary to provide the right cluster name value to SingleClusterPlanner.materializeTsCardinalities for FiloDB cardinality queries.
BREAKING CHANGES
Need an update to TsCardinalities LogicalPlan on the query planner side.

fix(metering): Overriding the cluster name passed to SingleClusterPanner for TenantIngestionMetering changes

---

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
version.sbt

Overriding the cluster name passed to SingleClusterPanner for TenantIngestionMetering changes.
New behavior : Adding new cluster name to override the value in SingleClusterPlanner. This is necessary to provide the right cluster name value to SingleClusterPlanner.materializeTsCardinalities for FiloDB cardinality queries.
BREAKING CHANGES
Need an update to TsCardinalities LogicalPlan on the query planner side.

fix(metering): Overriding the cluster name passed to SingleClusterPlanner for TenantIngestionMetering changes

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala

Query result streaming execution used to allocate one RecordBuilder per result SerializedRangeVector.
This is too much allocation and waste of memory.
Instead buffer+group the results and then use one RecordBuilder for several SRVs.
This will result in much less memory use.
Tip: See diff by disabling whitespace changes

bug(query): Query result streaming execution allocated too much mem via RB

---

core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityManager.scala

**Current behavior :** We issue a RocksDB write for each each iteration of partKey while traversing through lucene index during DS cardinality store calculation. For large indexes (10-12 billions), this could take up to 2 hours.   
**New behavior :** Reducing the number of RocksDB write by in-memory aggregation up to a configured `flushCount` after which we issue bulk RocksDB writes.

perf(card): Adding config support for DS card flushCount and perf logs for cardinality calculation time

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Currently, the `BatchExporter` might serialize certain edge-case label-value pairs into invalid JSON. This PR replaces the custom serialization logic with `jackson`.

fix(downsample): use jackson to serialize exported labels

---

prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala

Currently, an `int`-type config is accessed as a `boolean`. This PR instead invokes the correct `Config` method.

fix(prometheus): incorrect config method

---

coordinator/src/main/scala/filodb.coordinator/ShardManager.scala
coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala

**Current behavior :** Clustering V2 starts tenant ingestion metering when filo server is started. This is different from clustering v1 where it only starts if the config is enabled.
**New behavior :** Tenant ingestion metering is started when the desired config is enabled.

fix(metering) Tenant metering in one region and removing unused data structures for cluster V2

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala

[LabelNames API](https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names) currently requires metric name to be present. With this change metric name is made optional.

misc(query):make metric name in labelnames API optional

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
prometheus/src/main/scala/filodb/prometheus/parse/Parser.scala

This change is make API compliant with prometheus [LabelNames API](https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names) as `match[]` is not mandatory.

misc(query): make match[] parameter optional for LabelNames queries

---

core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/RateFunctions.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala
query/src/test/scala/filodb/query/exec/WindowIteratorSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala

The result of a range vector function is based on the data in a range. Previous the first millisecond of data was excluded from the range, now it is included. Let's say, we have a  ts counter { [0s, 1.0], [5s, 6], [10s, 16].
```
Previously, rate(count)[10s] at timestamp 10 just has two data points [5s, 6] and [10s, 16] it may result in a result (16 - 6) /5 =2.
Now, the [0s, 1.0] is included so, the rate would be (16 - 1) / 10 = 1.5
```
After this change, Filodb will be compliant to Prometheus. …

filodb(core) include the start time for range functions such as rate.

---

core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

- Stop collecting results once limit is hit. This will avoid unnecessary cpu cycles and heap usage

misc(query): limit partKey/partId lookup results early

---

query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

PR fixes two issues:
1. Cardinality records with `_overflow_` prefix doesn't pass dataset as expected by the QueryService in V2 APIs. 
2. Correctness issue: Incorrect aggregation when the hashmap reaches the map size. As of today, we would skip the keys already present in the map and always aggregate the overflow bucket.
The fixes and unit tests are added for the above issues.

fix(cardinality): Records with overflow doesn't pass dataset + Aggregation issue in TsCardReduceExec

---

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala

during full index migration, reading from raw index table is not needed. This PR is to avoid this additional read from Raw Cassandra

fix(downsample): skip reading partkey from raw during full migration

---

coordinator/src/main/scala/filodb.coordinator/TenantIngestionMetering.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SinglePartitionPlannerSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/test/scala/filodb/query/LogicalPlanSpec.scala
query/src/test/scala/filodb/query/PromCirceSupportSpec.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

**New behavior :** simplifying the codebase by removing the v1 cardinality code. 
- Deprecating V1 TsCardinalities and removing its helper functions.

fix(cardinality): Deprecating CardinalityV1 and simplifying the cardinality logical and exec plans

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala

When we profile a FIloDB instance with a large index and which sees a lot of repeating queries, we see the following flame graph (as taken by async profiler)
We  see almost 80% stack traces are related to index searches and about 50% of them are related to caching.  Also [this](https://www.mail-archive.com/java-user@lucene.apache.org/msg51649.html) archive mentions disabling caching which may or may not work in our case   (also they mention disabling cache in a different way than what this PR does).  The idea is to have that knob to let us disable the caching and then profile again.
We now support flag based enable/disable caching. By default the caching is enabled (existing default)

perf(query) Option to disable Lucene caching

---

coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
coordinator/src/main/scala/filodb.coordinator/client/QueryCommands.scala
coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
coordinator/src/test/scala/filodb.coordinator/ProtoConvertersSpec.scala
grpc/src/main/protobuf/exec_plan.proto
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/ProtoConverters.scala

only two execution plans are tested now with the unit tests, in the future PR more unit tests should come
We send execution plans using Scala serialized objects.
We want to be able to send execution plans that are represtend by Protobufs.
no breaking changes

feat(query) Implement Protobuf definitions of all of the execution plans

---

cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysV2Table.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala

1. The cassandra writes for chunks and partKeys are idempotent, but they are marked as such and default value is false. Explicitly setting the idempotent = true for such writes.
2. Adding a log in `doRecovery` process to debug the shard recovery scenarios.

fix(cassandra): Setting cassandra writes to idempotent and adding debug log for shard recovery

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/ShardKeyRegexPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala

Plans are materialized directly by inner planners when they draw data from one partition. However, when the ShardKeyRegexPlanner fanout batch size is small enough, multiple plans may be produced for one partition. Currently, these plans are concatenated and returned; they will be missing any root-level e.g. aggregations/joins.
This PR ignores the "if one partition then materialize with inner planners" logic when the inner planners return more than one plan.
For example, plans prior to this PR may be produced as:
```
Concat
Agg
RawData(localShardKey1)
RawData(localShardKey1)
Agg
RawData(localShardKey2)
RawData(localShardKey2)
```
Now, root plans will be correct because materialization proceeds through the ShardKeyRegexPlanner's `walkLogicalPlanTree` when inner …

fix(query): ShardKeyRegexPlanner batching fix

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/HighAvailabilityPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSplitSpec.scala

**Current behavior :**  Histogram bucket queries with PeriodSeriesWithWindowing logical plan (queries such as sum(rate) etc. use this logical plan) don't apply the InstantVectorFunctionMapper transformer correctly for le label filter. 
**New behavior :** Adding the required transformer to correctly pick up the required bucket given in the query.

fix(query): histogram queries with PeriodSeriesWithWindowing logical plan don't apply le label filter

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/ExportConstants.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Adds support for export from the downsampler job to multiple destinations; data is now exported in the Iceberg format.
This PR will remove all support for export of CSV-formatted data. 
Spark Downsampler job currently exports data in CSV format.
Implements changes in Spark Downsampler Job to export data in Iceberg format and write to Iceberg Table in a specific schema.
Changes includes the following:
- Updates in `BatchExporter.scala` to be able to be to create RDD in new schema and convert RDD to DF to be able to write to Iceberg Table. 
- `filodb-defaults.conf` changes for export includes the following: 
1. Adds catalog, database conf Iceberg properties in filodb-defaults.conf.
2. Under groups, each group should also …

feat(downsample): support export to multiple paths in Iceberg format

---

coordinator/src/main/scala/filodb.coordinator/ActorSystemHolder.scala
coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
coordinator/src/test/scala/filodb.coordinator/ProtoConvertersSpec.scala

Integration tests would not succeed if proto execution plans are used.
Integration tests would succeed if proto execution plans are used.

fix(coordinator) cleanup and fixes for ExecPlans to/from proto conversions

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala

fix @modifier for multiple partition time series.

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala

Bug fix: Enclose table location path in quotes in Iceberg export create sql query
Table location in CREATE SQL query needs to be enclosed in quotes.

fix(export-iceberg): Enclose table location path in quotes in Iceberg export create sql query

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Fix error: Cannot write 'labels': string is incompatible with map<string,string>.
Solution: Change type of labels column in `StructType` from` StringType` to `MapType`

bug-fix(export-iceberg): change type of labels column in StructType from StringType to MapType

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Currently, exported column values might include e.g. `Some(~)` around an actual label value. This PR instead exports only the value itself.
Additionally, the `timestamp` column's value was a `LocalDateTime`; this is incompatible with Spark. The value is now a `java.sql.Timestamp`.

fix(downsample): remove Option wrapper around export values

---

coordinator/src/main/scala/filodb.coordinator/ActorPlanDispatcher.scala
coordinator/src/main/scala/filodb/coordinator/v2/FiloDbClusterDiscovery.scala
coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala

**New behavior :** Adding a counter to track the occurrences of actor refs not getting resolved.

fix(cluster): Adding metric to track when actor ref is not getting resolved

---

grpc/src/main/protobuf/query_service.proto
query/src/main/scala/filodb/query/ProtoConverters.scala

This PR adds the following fields missing from the `PlannerParams` proto definition:
- `reduceShardKeyRegexFanout`
- `maxShardKeyRegexFanoutBatchSize`

fix(query): add missing PlannerParams proto fields

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

- Currently, `"distribution-mode": "hash"` is the new default and requests that Spark uses a hash-based exchange to shuffle the incoming write data before writing. Practically, this means that each row is hashed based on the row's partition value and then placed in a corresponding Spark task based upon that value.
Setting `"distribution-mode": "none"`, does not request any shuffles or sort to be performed automatically by Spark.

misc(export-iceberg) Iceberg export disable automatic shuffle while appending data to table

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala

- Distribution mode: none, does not request any shuffles or sort to be performed automatically by Spark. Because no work is done automatically by Spark, the data must be manually sorted by partition value. The data must be sorted either within each spark task, or globally within the entire dataset. A global sort will minimize the number of output files.
- Also, with no sort manually done, seeing `spilling sort data on disk` in logs. 
Trying to `sortWithinPartitions()`, to return a new Dataset with each partition sorted by the given expressions (partition columns) before writing to the table as mentioned above "the data must be manually sorted by partition value. The data must be sorted either within each spark task, or …

misc(iceberg-export): sort within partitions before writing the data to table

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala

Currently, Spark jobs may fail if tasks must be serialized/redistributed; some task metrics are not serializable. This PR adds the `@transient` tag to make them serializable.

fix(sparkJobs): make DS-job metrics serializable

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/store/ChunkSetInfo.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/RateFunctions.scala

- feature flag to disable [starttime inclusiveness in range functions](https://github.com/filodb/FiloDB/pull/1665)

misc(query): feature flag to exclude start time for range functions

---

query/src/main/scala/filodb/query/ProtoConverters.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala

When converting streaming Query response to a single list we assemble the range vectors in following manner
Consider we get the following range vector in batches serialized
``[[1, 2, 3], [4, 5, 6], [7, 8]]``
When assembling the result becomes
``[[7, 8], [4, 5, 6], [1, 2, 3]]``
This was due to the fact we used the cons operator (``::``) to prepend the latest streamed response essentially reversing the order of these batched response. We thus see issues when operations like ``sort_desc`` where the response is strictly ordered but goes out of order in batches.
The cons operator (``::``) is removed and ``Seq`` to preserve the ordering. The unit test reproduces this phenomena and validates the fix. 
None

fix(query) Order of range vectors is not respected when converting from streaming to QueryResult

---

core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
version.sbt

Current behavior :
Some labels as configured in label-column-mapping (to add as more columns in the table) may not exist in all the timeseries. So, the assert statement can fail the export job if the label may not exist in the timeseries and hence, label-value can be None.
Currently, `none` strings are appearing in the Iceberg Table when some column has no values. 
New behavior :
- Remove the assert statement such that, if the label doesn't exist in the timeseries. 
- Remove dynamic setting of `none` string in favor of Iceberg columns can be of only NULL Type or NOT NULL Type.
- When there is no value for a label, write it as `None` from spark to the Iceberg Table column, iceberg will automatically treat it as a `null` value and will show empty values in the table's column. 
- Remove …

misc(iceberg-export): remove assert and allow None label-values as some labels may not exist in all timeseries

---

gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala

**Current behavior :** Gateway server is publishing untyped record schemas for when gen-gauge-data is selected. 
**New behavior :** Publishing the gauge schema records when gen-gauge-data is selected.

fix(gateway): Filodb Gateway was publishing untyped schema instead of gauge schema for `gen-gauge-data` flag

---

cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysByUpdateTimeTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysV2Table.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala

**Current behavior :** Read queries is not retried by default since it is not marked as idempotent.
**New behavior :** Marking read queries as idempotent for better retry handling.

fix(cassandra): Marking cassandra reads as idempotent

---

query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala

**Current behavior :** Assertion error happening in cases where
1.  metric name has a suffix `_min`  or `_max` AND 
2. query have lots of label filters which causes some `TimeSeriesShard` returning `no` data AND
3. have another metric without the suffix.
**New behavior :** We are reverting the query change added with the support for min/max histograms to fix the bug in the short term.

fix(query): Reverting the min max suffix replacement

---

http/src/main/scala/filodb/http/HealthRoute.scala
http/src/main/scala/filodb/http/apiv1/HttpSchema.scala

**New behavior :** Adding a new http endpoint for liveness checks of filodb instance. This api is a low cost endpoint to make sure the instance is reachable over the given network.

misc(http): Adding a simple http endpoint for liveness checks

---

prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/parse/AntlrParser.scala
prometheus/src/test/scala/filodb/prometheus/parse/ParserSpec.scala

Error code does not indicate that the regex is too long.
`valid_query: Cannot parse […]`
Error code will indicate that the regex is too long.
The error will contain meaningful message
`Regular expression filters should be <=`

fix(query) misleading message when label filter is too long.

---

cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/test/scala/filodb.cassandra/MemstoreCassandraSinkSpec.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/CassandraColumnStoreSpec.scala
cassandra/src/test/scala/filodb.cassandra/columnstore/OdpSpec.scala
conf/timeseries-dev-preagg-source.conf
conf/timeseries-dev-source.conf
conf/timeseries-filodb-server-ds.conf
coordinator/src/main/scala/filodb.coordinator/NodeCoordinatorActor.scala
coordinator/src/main/scala/filodb/coordinator/v2/NewNodeCoordinatorActor.scala
core/src/main/scala/filodb.core/store/ChunkSink.scala
core/src/test/scala/filodb.core/store/ColumnStoreSpec.scala
filodb-dev-start.sh
jmh/src/main/scala/filodb.jmh/QueryOnDemandBenchmark.scala
project/FiloBuild.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala
spark-jobs/src/main/scala/filodb/repair/ChunkCopier.scala
spark-jobs/src/main/scala/filodb/repair/PartitionKeysCopier.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala
spark-jobs/src/test/scala/filodb/repair/ChunkCopierSpec.scala
spark-jobs/src/test/scala/filodb/repair/PartitionKeysCopierSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/ClusterSingletonFailoverSpec.scala
standalone/src/multi-jvm/scala/filodb/standalone/IngestionAndRecoverySpec.scala

As of now there is a stipulation that all the datasets that are configured in a FiloDB cluster needs to use one Keyspace for raw (actively ingesting) data. With this change, keyspaces can be configured per dataset with the exception of MetaStore (checkpoints).
This is especially useful to merge two clusters for better resource utilization without the need for data migration. With the caveat that checkpoint records need to be migrated from source cluster to target cluster.

feat(core): support for per dataset cassandra keyspace overrides

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanUtilsSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala

**New behavior :** Adding new helper method to get column filter list along with leaf plan

feat(misc): Adding new helper method to get column filter list along with leaf plan

---

http/src/main/scala/filodb/http/HealthRoute.scala
http/src/test/scala/filodb/http/HealthRouteSpec.scala

**Current behavior :** The liveness check just returned `UP` response without any consideration.
**New behavior :** Liveness endpoint checks for connectivity to kafka and cassandra i.e. the shards to be in recovery or active state.

feat(cluster): Enhancing liveness check to include cassandra and kafka connectivity at startup

---

cli/src/main/scala/filodb.cli/CliMain.scala
coordinator/src/main/scala/filodb.coordinator/QueryActor.scala
core/src/main/scala/filodb.core/memstore/ratelimit/CardinalityTracker.scala
core/src/main/scala/filodb.core/memstore/ratelimit/QuotaExceededProtocol.scala
core/src/main/scala/filodb.core/memstore/ratelimit/QuotaSource.scala
core/src/main/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStore.scala
core/src/test/scala/filodb.core/memstore/ratelimit/CardinalityTrackerSpec.scala
core/src/test/scala/filodb.core/memstore/ratelimit/RocksDbCardinalityStoreSpec.scala
query/src/main/scala/filodb/query/PromCirceSupport.scala
query/src/main/scala/filodb/query/PromQueryResponse.scala
query/src/main/scala/filodb/query/exec/MetadataExecPlan.scala

**Current behavior :** `CardinalityValue` and `CardinalityRowReader` store and retrieve the cardinality data using `Int` type. This is causing overflow issues for various `_ns_` and `_ws_` cardinality queries.   
**New behavior :** Changing the above types from `Int` to `Long` 
- RESULT_SCHEMA changes for `CardinalityResult`

fix(cardinality): converting cardinality storage and query types from int to long to avoid integer overflow

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

**Current behavior :** We send a string "multiple" when passing a regex for a shard key label/column filter. This doesn't give us visibility of of the actual value passed in the query stats.
**New behavior :** Added a match case which allows to return the column-filter regex values.

fix(QueryStats): return namespace regex value as given instead of using "multiple" string

---

core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

Cherry picking the query stats field to integration branch.

Cherry Pick: fix(QueryStats): return namespace regex value as given instead of using "multiple" string

---

query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala

Currently, `RemoteExec` plans sometimes hang during execution when `RangeVectorTransformer`s are applied. This PR instead schedules transformer application on the `global` `Scheduler` to prevent possible deadlock.

fix(exec): fix RemoteExec transformer deadlock

---

query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
version.sbt

fix(exec): cherry-pick RemoteExec deadlock fix

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
version.sbt

Revert "fix(exec): cherry-pick RemoteExec deadlock fix" This reverts commit 08260b044df82b5fa6a5cb3b3ee6f7031909b4af, reversing changes made to 7c66afa80ff74823233ac1f48c62d4a84aa0cc82.
Revert "fix(query): 0.9.25.5 RemoteExec RVT hotfix (#1769)" This reverts commit 7c66afa80ff74823233ac1f48c62d4a84aa0cc82.

revert(exec): revert RemoteExec deadlock fixes

---

query/src/main/scala/filodb/query/exec/ExecPlan.scala
query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQLGrpcRemoteExec.scala
query/src/main/scala/filodb/query/exec/PromQlRemoteExec.scala
query/src/main/scala/filodb/query/exec/RemoteExec.scala
query/src/test/scala/filodb/query/exec/PromQLGrpcRemoteExecSpec.scala
query/src/test/scala/filodb/query/exec/RemoteMetadataExecSpec.scala

Currently, `RangeVectorTransformers` are never applied to `RemoteExec` plans; they are not applied because `RemoteExec` plans-- unlike others--  override the default `execute` method.
This PR removes the `execute` override and instead implements `doExecute` (similar to other plan types).
Note: this solution prioritizes result correctness over plan correctness; `RemoteExec` plans should never have `RangeVectorTransformers` attached, given that the transformations can be pushed-down to the machines serving the remote data. An `info` log is now written every time a `RangeVectorTransformer` is attached to a `RemoteExec` plan.

fix(query): apply transformers to RemoteExecs

---

query/src/main/scala/filodb/query/exec/MetadataRemoteExec.scala

reverting behavior, so that we do not apply limits on `MetadataRemoteExec`. Limits still get applied at leaf level

misc(fix): do not apply limits to metadata queries

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
version.sbt

Current behavior :
In case of large volume of data to be exported, with sortWithinPartitions() is causing spill(disk) & spill(memory).
New behavior :
Removing this operation will not do sorting within partitions and will not cause memory & disk spill.

(misc-iceberg-export): Remove sortWithinPartitions to avoid spill(memory) and spill(disk)

---

core/src/main/scala/filodb.core/TargetSchemaProvider.scala
core/src/main/scala/filodb.core/query/ColumnFilterMap.scala
core/src/test/scala/filodb.core/query/ColumnFilterMapSpec.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala

Adds `FastColumnFilterMap`. Snippet from the javadoc:
```
* Bare-bones but (in some cases) ultra-fast ColumnFilterMap.
* At most two label-values are read during a get() call:
*   - One to be matched by equality.
*   - One to be matched by any arbitrary filter.
* Useful for performance-critical use-cases where this minimal functionality is sufficient:
*   at most two labels are filtered, and only one supports non-equals filters.
```
Local tests demonstrate that-- although it is significantly more constrained--  `FastColumnFilterMap`  is about 4x faster than `DefaultColumnFilterMap` in these limited-filtering scenarios.

perf(query): add FastColumnFilterMap

---

.github/workflows/scala.yml
README.md
project/RustPlugin.scala
project/build.sbt

Add build integration to build Rust librarie that can be used for native methods in a module:
* Opt in plugin that enables Rust integration
* compile, test, lint, package steps
* Support for multi-arch build allowing the final jar to support more than one platform
No libraries are using this as of this commit, follow ups will add Rust code usage
- [n/a] Tests for the changes have been added (for bug fixes / features) ?
**Current behavior :**  No support for Rust projects
**New behavior :** Opt in support via RustPlugin to build Rust libraries

misc(build): Add support for Rust JNI libraries

---

core/src/main/scala/filodb.core/Utils.scala
core/src/main/scala/filodb.core/memstore/OnDemandPagingShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyIndex.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/PartKeyQueryBuilderSpec.scala

In preparation for new index types separate common logic from Lucene specific logic.  No functional changes are made as part of this commit, just moving code around and refactoring to accept multiple index implementations.
In most cases this amounts to moving code out of PartKeyLuceneIndex and into PartKeyIndexRaw without further changes.  In a few cases things that were instaniating Lucene specific types now use callbacks or other approaches to allow instantiating index specific types.

refactor(core): Move common index logic to abstract base class

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala

Metadata queries do not support filtering based on metric type using `_type_` filter
Added support.
Note that only new documents of persisted downsample index will have the _type_ field. Index needs to be rebuilt if full support is needed. Can be skipped if metadata queries don't hit downsample index.

feat(core): Now metadata queries support _type_ filter

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala

If clustering V2 is enabled, shard level failover is enabled, and a shard is not assigned, HighAvailabilityPlanner would throw a NullPointerException while producing a plan.
HighAvailabilityPlanner produces a plan and no exception is thrown.
n/a

fix(query): fix NullPointerException if shard is unassigned

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/TestData.scala
core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
gateway/src/test/scala/filodb/gateway/conversion/InputRecordBuilderSpec.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/test/scala/filodb/query/exec/AggrOverRangeVectorsSpec.scala
query/src/test/scala/filodb/query/exec/HistogramQuantileMapperSpec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala
query/src/test/scala/filodb/query/exec/PeriodicSamplesMapperSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala
query/src/test/scala/filodb/query/exec/rangefn/InstantFunctionSpec.scala

**Current behavior :** back compatibility of queries spanning across prom-histograms and otel histograms with same metric name.
**New behavior :** supporting this behavior.
- Changed storage schema of `otel-cumulative-histogram` and `otel-delta-histogram`. Moved histogram to column 3 from column 5.

feat(histograms): Supporting back compatibility of queries which spans across prom histograms and otel histograms for same metric

---

spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchExporter.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Currently, the `ColumnFilterMap` used in `BatchExporter::getRuleIfShouldExport` will choose an export config arbitrarily from multiple key filter matches. For example, if the map contains:
```
{l1=foo.*} -> config1
{l1=fooA.*} -> config2
```
Then this series would technically match both keys:
```
{l1=fooABC}
```
-- and either `config1` or `config2` may be returned.
Since both contain their own `allow`/`block` rules, it's possible the series should be exported according to `config1` but no export rule is returned because it is blocked by `config2`.
Since anyways an `RDD` with _all_ rows is iterated once per table, it is both less confusing and more correct to consider exclusively the rules for one table per iteration. This PR adds a table config parameter to …

fix(downsample): apply correct export rules

---

query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala

**Current behavior :** We don't have unit tests for StitchRvsExec which uses Histogram values.
**New behavior :** Adding unit tests for `StitchRvsExec` with histogram values.

misc(core): Adding unit tests for histograms for StitchRvsExec

---

core/src/main/scala/filodb.core/query/TransientRow.scala
memory/src/main/scala/filodb.memory/format/RowReader.scala
query/src/main/scala/filodb/query/exec/StitchRvsExec.scala
query/src/test/scala/filodb/query/exec/StitchRvsExecSpec.scala

The current Transient row can only handle a schema (Long, Double). However, there are different schemas for histogram, Avg and so on. Create a NaNRowReader to handle any schemas.
- Changes …

fix bugs caused by stitching empty and non-empty data.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/NodeCoordinatorActorSpec.scala
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala
prometheus/src/main/scala/filodb/prometheus/ast/Vectors.scala
prometheus/src/main/scala/filodb/prometheus/query/PrometheusModel.scala
query/src/test/scala/filodb/query/exec/MetadataExecSpec.scala
version.sbt

This revert will prevent a new error that occurs when filodb ingests data with a pre-existing `_type_` label:
```
java.lang.IllegalArgumentException: dimension "_type_" is not multiValued, but it appears more than once in this document
```

hotfix(0.9.27.1): revert "Now metadata queries support _type_ filter (#1819)"

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/resources/application_test.conf

Addition of `_type_` field to index is now configurable for each cluster, false by default for now.
Also, if the part-key already has the `_type_` field we don't index that since it is a reserved field that we populate.

feat(core): Do not index any existing _type_ field since it is a reserved field

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/memstore/PartKeyIndex.scala
core/src/main/scala/filodb.core/memstore/PartKeyLuceneIndex.scala
core/src/main/scala/filodb.core/memstore/PartKeyTantivyIndex.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/rust/filodb_core/src/index.rs
core/src/test/resources/application_test.conf
core/src/test/scala/filodb.core/memstore/PartKeyIndexRawSpec.scala
core/src/test/scala/filodb.core/memstore/PartKeyLuceneIndexSpec.scala
core/src/test/scala/filodb.core/memstore/PartKeyTantivyIndexSpec.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexExternalBenchmark.scala
jmh/src/main/scala/filodb.jmh/PartKeyIndexIngestionBenchmark.scala
project/RustPlugin.scala
project/plugins.sbt
run_benchmarks.sh

This contains the Scala side of query support.  This completes the basic end to end flow, so it also includes regression and performance tests.
There will be some small cleanup PRs after this for things like additional metrics, but with this PR the Tantivy index can be successfully activated via config.
Adds query logic to call into Rust code and tests

feat(core): Add Scala side of Tantivy query support

---

core/src/main/scala/filodb.core/memstore/PartKeyTantivyIndex.scala
core/src/rust/filodb_core/src/profile.rs

Add two new metrics for commit processing time and cache hit rates.  These will be used for monitoring as we roll out and turn the feature on for testing.
Add two new metrics to help with diagnostics

feat(core): Add tantivy metrics

---

project/RustPlugin.scala

Previously the code only optimized if a flag was passed during sbt invocation or if we're building multi-arch.  This has created confusing results where perf drifts because debug mode was used.
After doing testing and development it was found that release is a suitable default - it does incremental build, includes symbols for debugging, and while not as fast as debug builds is still fast enough for an inner loop.
You can still build with debug by setting rust.optimize=false for any cases where it is needed during local development.
Defaults to building debug rust code
Defaults to …

feat(core): Optimize Rust code by default

---

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/main/scala/filodb/query/exec/rangefn/RateFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

This change is to handle a case where a time series ends with a NaN value. Currently this results into a new chunk/row with a single NaN value. 
As we default NaN to zero value during rate/increase window calculation, this sets highestValue to be zero. This is resulting into negative rate/increase values, since rate = highestValue-lowestValue.
This fix is to short `addTimeChunks` operation and return without any effect on highestValue calculation.

fix(query): negative rate/increase due to NaN chunk

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

Generalizing the column filter check to span multiple tenants instead of just `_ws_`.
**Current behavior :** Currently enabling of max-min columns is  dependent on having the `_ws_` label.  This will cause issues if a timeseries doesn't have this required label.
**New behavior :** Allowing for users to configure to use any desired label for this feature flag.

fix(query): Generalizing the column filter check to span multiple tenants instead of just `_ws_`.

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
query/src/main/scala/filodb/query/exec/MultiSchemaPartitionsExec.scala
query/src/test/scala/filodb/query/exec/MultiSchemaPartitionsExecSpec.scala

Generalizing the column filter check to span multiple tenants instead of just `_ws_`.
**Current behavior :** Currently enabling of max-min columns is  dependent on having the `_ws_` label.  This will cause issues if a timeseries doesn't have this required label.
**New behavior :** Allowing for users to configure to use any desired label for this feature flag.

fix(query): hotfix_main: Generalizing the column filter check to span multiple tenants instead of just `_ws_`.

---

core/src/rust/filodb_core/Cargo.toml
core/src/rust/tantivy_utils/Cargo.toml
core/src/rust/tantivy_utils/src/collectors/part_key_record_collector.rs

Add a qualifier to imports to support slightly older Rust versions. Tag cargo metadata with min tested version to give a better error.

fix(core): Support Rust 1.78

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala

If query server fails over to the buddy cluster because local FiloDB clusters have shard(s) down no metric is emitted. 
Now we emit 4 metrics:
* legacy failover
* full failover with local planning
* partial failover (shard level failover) with local planning
* failure to execute the query because no shards are available 
N/A

feat(query): Add metrics for failover

---

project/RustPlugin.scala

Rust names the x86-64 architecture as x86_64.  Java names it as amd64. This mismatch causes errors during library load as they can't agree on the file path.
The fix is to normalize the Rust name into the Java name, so it can locate the output binaries.

fix(core): Fix Rust publishing of x86_64 binaries

---

project/RustPlugin.scala

If you're targetting an older Linux distro the default glibc version being linked against may be too high to produce runnable images.
cargo zigbuild supports specifying a specific glibc version to use for a link target by appending ".<version>" to the target triple.  For example, "x86_64-unknown-linux-gnu.2.17" will target v2.17.
For the most part this just works but we need to strip this suffix when looking for output binaries.  This fix adds that logic.
Support glibc target suffixes

fix(build): Support glibc qualifiers for Rust targets

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala

name is "plans" materialized
changed it to "failovers" materialized

fix(query): Fix metrics name for failovers

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala

feat(query):  cherry picking shard level failover metrics

---

spark-jobs/src/main/scala/filodb/downsampler/index/DSIndexJob.scala

- sometimes spark executor exits before Kamon flushes the metrics. This change is to wait for upto 62seconds for Kamon to flush and close the modules.

misc(sparkjobs): force push metrics publish from index job

---

core/src/rust/filodb_core/src/index.rs
core/src/rust/filodb_core/src/state.rs
core/src/rust/tantivy_utils/src/collectors/column_cache.rs

Columns in the column cache hold a reference to the mmaped file data that backs the segment.  These segments can be deleted during segment merging, but if a column for that segment is in the cache it prevents the mmap from closing and releasing RAM.
To fix this we subscribe for notifications on segment list changes and clear the column cache when these occur so stale segments can be reclaimed.
Old segments can remain in memory via column cache
Column cache is reset on segment list changes

fix(core): Fix tantivy column cache not releasing memory from deleted segments

---

project/Dependencies.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala
query/src/test/scala/filodb/query/util/HierarchicalQueryExperienceSpec.scala

**Current behavior :** No metric to track the updated hierarchical query plans. 
1. Added a counter to track the updated hierarchical query plans
2. Added capability to test kamon metric updates in our unit tests

misc(query): increment counter when query plan updated with next level aggregated metric

---

core/src/main/scala/filodb.core/memstore/PartKeyTantivyIndex.scala
core/src/rust/filodb_core/src/reader.rs
core/src/rust/tantivy_utils/src/collectors.rs
core/src/rust/tantivy_utils/src/collectors/index_collector.rs
core/src/rust/tantivy_utils/src/collectors/string_field_collector.rs
jmh/src/main/scala/filodb.jmh/PartKeyIndexBenchmark.scala

indexValues was falling way behind Lucene due to a few reasons:
1. We were copying results directly into Java objects, which was incurring a lot of JNI back and forth overhead
2. When querying the entire index we were looking at docs instead of the reverse index, which increased the count of items to process
This PR does a few things:
1. Add perf benchmarks for the missing functions
2. Add a new IndexCollector trait that can be used to walk the index vs docs
3. Remove the JNI object usage in indexValues vs byte serialized data
4. Return encoded string arrays instead of creating JVM strings in native code
5. Glue all these optimizations togther.
With this Tantivy is still a bit behind Lucene for this path, but it's almost 100x faster than before.

fix(core): Improve performance for Tantivy indexValues call

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala
query/src/test/scala/filodb/query/util/HierarchicalQueryExperienceSpec.scala

**Current behavior :** (link exiting issues here : LogicalPlan updates for hierarchical query experience expects metrics using the same aggregation suffix.
**New behavior :** Adding support for specifying multiple aggregation suffixes and rules and the logical plan update will appropriately pick up the suffix to be used. 
Example query for which the hierarchical logical plan updated will be now supported:
> sum(metric1:::`suffix1`{})  + sum(metric2:::`suffix2`{})

feat(query): Support multiple aggregation rules for HierarchicalQueryExperience logicalPlan update

---

core/src/main/scala/filodb.core/memstore/IndexBootstrapper.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

When bootstrapping the raw index we skip over tracking items with invalid schemas, signified by partId = -1.  However, today we still index them which can create query errors later on like the following:
```
java.lang.IllegalStateException: This shouldn't happen since every document should have a partIdDv
at filodb.core.memstore.PartIdCollector.collect(PartKeyLuceneIndex.scala:963)
at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:305)
at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:247)
at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:776)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:551)
at …
```

fix(core): Don't index part keys with invalid schema

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
core/src/main/resources/filodb-defaults.conf
query/src/test/scala/filodb/query/util/HierarchicalQueryExperienceSpec.scala

**Current behavior :**  aggregation operator like max and min will not work with rate and increase 
**New behavior :** removing these aggregation operators

fix(query): removing max/min aggregations from hierarchical query experience

---

conf/logback-dev.xml
coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala
coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/main/scala/filodb.core/query/QueryUtils.scala
core/src/test/resources/application_test.conf
jmh/src/main/scala/filodb.jmh/PlannerBenchmark.scala
project/Dependencies.scala

Though there is no expected change in the behavior for the end users,  the memory allocation for  methods ``getPushdownShards``, ``isTargetSchemaChanging`` and  ``QueryUtils.makeAllKeyValueCombos`` is high. This high memory allocation can be reduced by memoizing the responses which are repeatedly called by recursing the logical plan tree
With no caching enabled the JMH tests for materialize give following results
```
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                        Mode  Cnt   Score    Error  Units
[info] PlannerBenchmark.benchmarkMaterializePlan        avgt    5  20.819 ± 13.145  ms/op
```
As seen above, ``getPushdownShards``, ``isTargetSchemaChanging``  show up …

perf(query) Memoize the part of the logical plan tree traversal for reduced memory allocation and faster planning

---

core/src/main/scala/filodb.core/query/RangeVector.scala
grpc/src/main/protobuf/range_vector.proto
query/src/main/scala/filodb/query/ProtoConverters.scala

RepeatValueVector creates containers and incorrectly estimates the size of the row. This record creation creation shows up in the  Memory allocation profile and is unnecessary. 
Unnecessary allocations are avoided

perf(query) Eliminate the allocation of memory for RepeatValueVector

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanUtils.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanUtilsSpec.scala

**New behavior :** Adding helper functions to get the max offset and lookback in milliseconds.

misc(query): Adding helper functions for hqe

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala

Pull Request checklist
Current behavior : when histograms add buckets with different sizes, it returns a 5xx error
New behavior : it returns an IllegalArgumentException with a meaningful message

feat(histogram): add meaningful exception when histograms add buckets with different sizes

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/main/scala/filodb.core/metadata/Column.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
core/src/test/scala/filodb.core/metadata/ColumnSpec.scala
core/src/test/scala/filodb.core/metadata/SchemasSpec.scala
query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala
query/src/test/scala/filodb/query/exec/rangefn/PeriodicRateFunctionsSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Rate requires 2 samples in lookback window. Instead of returning empty result for rate in downsampled dataset (such queries with small window and smaller publish interval are encountered frequently in downsampled dataset), ~~we extend the lookback to two downsampled resolutions~~  we error the query out when lookback is insufficient. This fix is imperfect, but serves as a workaround until a better solution is delivered. Status quo affects customers by producing wrong query results and leads to thinking that there is data loss, or even worse, implicit trust that the query results are right.

fix(core): Error downsampled query if lookback is short when querying rate/increase

---

memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala

Removed 'size' from error message to clarify bucket configuration differences and avoid misleading users about bucket sizes.

fix(histogram): delete misleading words in exception message

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
query/src/main/scala/filodb/query/util/HierarchicalQueryExperience.scala
query/src/test/scala/filodb/query/util/HierarchicalQueryExperienceSpec.scala

**Current behavior :** Aggregation queries with labels/tags with `.*` regex is included in the HQE check against the higher level aggregation rule. So queries like following won't be optimized - 
```
aggregation rule - includeTags - {
level1:[ "device", "host"],
level2:["host"] 
}
query - sum(rate(my_metric{host="abc", "device"=~".*"}[5m]))
```
**New behavior :** We are ignoring the labels / tags with `.*` regex for the HQE check. So the above query will be optimized.

fix(query): Ignoring query-filter labels with .* regex in the HQE higher level checks

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/SingleClusterPlannerSpec.scala

**Current behavior :** Queries are failing when le=+Inf bucket is being selected for functions like rate, increase
**New behavior :** Supporting le=+Inf, le=Inf bucket values

fix(query): histogram le filter should support +Inf gracefully

---

.github/workflows/scala.yml
core/src/rust/filodb_core/src/ingestion/fields.rs
core/src/rust/filodb_core/src/query_parser.rs
core/src/rust/tantivy_utils/src/collectors/column_cache.rs
core/src/rust/tantivy_utils/src/collectors/string_field_collector.rs
core/src/rust/tantivy_utils/src/collectors/time_collector.rs
core/src/rust/tantivy_utils/src/collectors/time_range_filter.rs
core/src/rust/tantivy_utils/src/query/cache.rs

* Fix doc comments that had a incorrect line break
* Remove unneeded explicit lifetimes from many impls that can elide them
* Pin Rust toolchain version in workflow to avoid unexpected breaks like this going forward
Build failure with clippy errors
Build passes

fix(core): Fix latest clippy errors in Rust code

---

http/src/main/scala/filodb/http/PromQLGrpcServer.scala
version.sbt

- [ X ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
PromQLGrpcServer does not process requests bigger than 4MB.
PromQLGrpcServer would process requests up to the limit given in the configuraiton.

cherry-pick fix(query): fixing shard level failover by allowing bigger GRPC requests

---

.github/workflows/scala.yml
core/src/rust/filodb_core/src/ingestion/fields.rs
core/src/rust/filodb_core/src/query_parser.rs
core/src/rust/tantivy_utils/src/collectors/column_cache.rs
core/src/rust/tantivy_utils/src/collectors/string_field_collector.rs
core/src/rust/tantivy_utils/src/collectors/time_collector.rs
core/src/rust/tantivy_utils/src/collectors/time_range_filter.rs
core/src/rust/tantivy_utils/src/query/cache.rs

* Fix doc comments that had a incorrect line break
* Remove unneeded explicit lifetimes from many impls that can elide them
* Pin Rust toolchain version in workflow to avoid unexpected breaks like this going forward
- …

fix(core): Fix latest clippy errors in Rust code (#1895)

---

coordinator/src/main/scala/filodb.coordinator/GrpcPlanDispatcher.scala

- [ X ] The commit(s) message(s) follows the contribution [guidelines](CONTRIBUTING.md) ?
When a GRPCPlanDispatcher needs to be serialized using Kryo (as opposed to ProtoBuf) it fails because the class has a member that does not have a default constructor (logger). Serialization fails and shard level failover fails.
Removed the logger from the execution class, serialization does not fail.
n/a

fix (core): removing logger from an execution plan

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/DefaultPlanner.scala
coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
grpc/src/main/protobuf/query_service.proto
prometheus/src/main/scala/filodb/prometheus/ast/Functions.scala
query/src/main/scala/filodb/query/PlanEnums.scala

This PR introduces support for the optimize_with_agg function in the Logical Plan. The optimize_with_agg function is a no-operation (no-op) that is used in conjunction with aggregation queries. It ensures that the optimization logic is preserved and applied correctly during the aggregation phase without interfering with the underlying data or query execution flow. This enhancement allows users to pass queries with optimize_with_agg and see a proper Logical Plan with the correct tree structure.
1. Adds `optimize_with_agg` to MiscellaneousFunctionId.
2. Updates ProtoConverters to support `optimize_with_agg`.
3. Updates Query Service Proto to include `OPTIMIZE_WITH_AGG`.
4. Modifies DefaultPlanner to handle `optimize_with_agg` as a no-op.
5. Ensures proper Logical Plan tree structure for …

feat(query): Adding support of optimize_with_agg logical plan to make use of aggregated metrics in HQE

---

.github/workflows/scala.yml

**Current behavior :** FiloDB's test suite is not compatible with the ubuntu-latest image of GitHub actions - [ubuntu-24 image rollout announcement](https://github.com/actions/runner-images/issues/10636)
**New behavior :** Pinning the FiloDB github action's image to `ubuntu-22` image for now, to unblock the test runs.

fix(build): pinning the ubuntu base version of github action workflow to unblock test suites

---

core/src/main/scala/filodb.core/query/RangeVector.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala

The rows() is a closable resources. We can use Using to protect it. However, the current logic calls rows() twice and only close it once. This commit would fix this issue.
Potential resource leak due to unclosed resources.
Resource leak fixed.
- Over the wire formats for Akka …

fix potential resource leak.

---

coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
grpc/src/main/protobuf/query_service.proto

RepeatTransformer should be added as a case.

fix Unexpected Range Vector Transformer.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala

If shard level failover (SLFO) is enabled even if a full failover happens (ie the entire query is forwarded to the buddy cluster), planning of the entire query happens on a remote cluster. In that case the plan might be fairly big because proto execution plans do not have references. This might cause issues as the plan size can go above 30MB. 
When FULL failover happens (ie we do not just pull data from a few shards from the buddy cluster), we will continue to forward promql as we used to do previously (legacy full failover). Shard level failover would be planned entirely on the cluster that received the request. This should not cause issues as the proto plans that would be sent to the buddy clusters will be very small …

query(fix) planning for local and remote clusters only if absolutely needed

---

.github/workflows/scala.yml
coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala
coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
core/src/main/scala/filodb.core/query/RangeVector.scala
grpc/src/main/protobuf/query_service.proto
query/src/main/scala/filodb/query/exec/AggrOverRangeVectors.scala
query/src/main/scala/filodb/query/exec/aggregator/CountValuesRowAggregator.scala
query/src/main/scala/filodb/query/exec/aggregator/TopBottomKRowAggregator.scala
query/src/test/scala/filodb/query/exec/LocalPartitionDistConcatExecSpec.scala

fixing filodb's github test action workflow (#1928)

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala

If shard level failover is enabled but is not required, ie the local cluster is not healthy but the remote cluster is healthy we switch to legacy failover when promql is issued to the buddy cluster. However, the query context parameters still have shard level failover flag enabled that does not allow to properly resolve shards.
When legacy failover is enabled the query context parameter is set to "legacy".
n/a

query(fix): enforce legacy failover when needed

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/HighAvailabilityPlanner.scala

fix (query): cherry picking ensure that legacy failover stays legacy failover 

---

core/src/main/scala/filodb.core/RateLimiter.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesShard.scala
core/src/test/scala/filodb.core/RateLimiterSpec.scala

"Negative" ingestion latencies i.e. where a `RecordContainer`'s timestamp occurs after the current time) might occur as a result of clock skew.
Currently, negative ingestion latencies will cause Kamon histograms to throw exceptions.
This PR adds one additional metric `negativeIngestionPipelineLatency` to record negative pipeline latencies (as their absolute values). Additionally, values recorded into the two usual ingestion latency metrics are now wrapped inside `Math.max(0, value)` calls.

fix(memstore): account for clock drift during latency measurement

---

core/src/main/scala/filodb.core/RateLimiter.scala
core/src/test/scala/filodb.core/RateLimiterSpec.scala

New `RateLimiter` tests are flaky. Two possible resons:
- `System.currentTimeMillis()` is [random enough](https://stackoverflow.com/a/2979239) that the tests fail.
- One of the test’s `Thread.sleep()`s was too short prior to a validation.
This PR addresses both possible problems (and will be merged only after 5 consecutive PRB successes).

fix(memstore): fix flaky rate-limiter test

---

query/src/main/scala/filodb/query/exec/PeriodicSamplesMapper.scala

- bug fix to make start time inclusive when default behavior is overridden. This is especially needed for metrics that are generated by preprocessing for e.g preagg, recordingrules.

fix(query): fix bug to make start time inclusive on config

---

coordinator/src/main/scala/filodb/coordinator/ProtoConverters.scala
grpc/src/main/protobuf/query_service.proto
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/InternalRangeFunction.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/main/scala/filodb/query/exec/rangefn/RangeFunction.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

New range function `last_over_time_is_mad_outlier()` which classifies the last data point in the range window as an anomaly  or not based on other points in the window.
This is especially useful in subqueries. This query executes a subquery and calculates outliers in request rate for a service. The outlier points are returned as part of the results.
```
last_over_time_is_mad_outlier(3, sum(rate(http_req_total{...}[5m]))[1d:5m])
```

feat(query) Range function to identify outliers using MAD

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/binaryrecord2/RecordSchema.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreForMetadataSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

Two fixes:
1. When multiple labels are queried in label-value query, and `_type_` is included, it would not work
2. Downsample Main Spec's exponential histogram unit test was using wrong schema and didnt test min/max

bug(core): Type field not returned in mult-label-value query + unit test fix

---

conf/timeseries-dev-source.conf
core/src/main/scala/filodb.core/Utils.scala
core/src/main/scala/filodb.core/downsample/DownsampledTimeSeriesShard.scala
core/src/main/scala/filodb.core/store/ChunkSource.scala
core/src/main/scala/filodb.core/store/ReadablePartition.scala
core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

1. Queries are throwing SchemaMismatch errors when the metrics are transitioning from legacy histogram types ( prom, delta ) to ( otel-cummulative, otel-delta).
2. Code is not seamlessly handling the above scenario as it is for raw chunk source. The issue stems when the data is being paged from cassandra.
3. Unit test gaps in downsampling of otel-histograms ( both ingestion and queries).
1. Handling the SchemaMismatch errors while paging data from cassandra in downsample cluster.
2. Improving the unit test coverage by adding tests for `otel-cummulative`, `otel-delta` and mixed histogram schemas ( `prom + otel-cummulative` and `delta + otel-delta` )

fix(downsample): Back compatibility of legacy and otel histograms in downsample cluster

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LogicalPlanParser.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LogicalPlanParserSpec.scala
query/src/main/scala/filodb/query/PlanEnums.scala
query/src/main/scala/filodb/query/exec/rangefn/AggrOverTimeFunctions.scala
query/src/test/scala/filodb/query/exec/rangefn/AggrOverTimeFunctionsSpec.scala

Users of the `last_over_time_is_mad_outlier` function can now customize to do upper, or lower or both bounds check

feat(query): Mad outlier function can be customized for lower/upper bounds checks

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala

This reverts commit 4e62a494733feefe13fa081a630332203a431677.
Stitching data from the Raw and DownSample clusters is not supported due to schema differences:
Raw cluster data schema has a column of (value),
DownSample cluster data schema has a column of (avg).
When stitching these two plan, it tries to reduce schema and throws SchemaMismatch Error. 
Reverting this commit to remove the stitch logic.

Revert "feat(coord): raw-data query with range expression also route to downSample cluster (#1947)"

---

core/src/main/scala/filodb.core/query/RangeVector.scala
query/src/main/scala/filodb/query/ProtoConverters.scala
query/src/main/scala/filodb/query/exec/RangeVectorTransformer.scala
query/src/test/scala/filodb/query/ProtoConvertersSpec.scala

``RepeatValueVector``  calls ``next`` on the underlying transformer and stores the value of the first item as part of it. This might be unnecessary and the call is deferred to the point when ``rows`` is invoked. Currently both the key and the first item of the underlying  RV (as ``TransientRow``) is stored in the instance of RepeatValueVector.
We do not invoke next or keys on the wrapped RangeVector until the rows are requested.
**BREAKING CHANGES :**
`RepeatValueVector` no longer implements `SerializableRangeVector` This means , any deserialization of this vector will arrive over the wire as a SerializableRangeVector (which would have consumed ``RepeatValueVector`` on the producer side ) and the not as …

perf(query) Optimize RepeatValueVector to not store the key and the first item in the data eagerly

---

memory/src/main/scala/filodb.memory/format/NibblePack.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramVectorTest.scala

Mutable histograms, when used for exponential histograms rate calculations were truncating decimals since they were being converted to Long during serialization. This fixes the conversion to use `writeDoubles` instead of `writeDeltas`. The latter should be used for LongHistogram only during ingestion.

bug(memory): MutableHistogram vectors when serialized with Exp histograms were truncating decimals

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/LongTimeRangePlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/LongTimeRangePlannerSpec.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/PlannerHierarchySpec.scala

- Instant queries with a range expression (raw data export) are routed only to raw clusters.
- These queries do not retrieve data beyond the raw retention period (7 days).
- Queries are routed only to downsampled clusters when the time range exceeds the raw retention period.
- No stitching occurs between raw data and downsampled data.
- Queries within the raw retention period retrieve all data from raw clusters.
- Queries beyond the raw retention period retrieve all data from downsampled clusters (data loss may occur after latestDownsampleTime: now - 6h).

feat(coord): Raw data export route to downsample cluster when needed

---

core/src/main/scala/filodb.core/memstore/TimeSeriesPartition.scala
core/src/test/scala/filodb.core/memstore/TimeSeriesPartitionSpec.scala

When ``TimeRangeChunkScan`` is provided, all chunkInfos are iterated and the relevant ``ChunkSetInfos`` are filtered that contains the data for the given range. The change will avoid this scan and first check if the requested data is available in the currentInfo and return that one chunk of interest. 
Just return the ``currentInfo`` if thats where all the requested data range lies.

perf(memstore) TimeRangeChunkScan optimization when querying data in current ingesting chunk

---

coordinator/src/main/scala/filodb.coordinator/ShardHealthStats.scala
coordinator/src/main/scala/filodb.coordinator/ShardMapper.scala
coordinator/src/main/scala/filodb.coordinator/ShardStatus.scala
coordinator/src/main/scala/filodb/coordinator/v2/FiloDbClusterDiscovery.scala
coordinator/src/test/scala/filodb.coordinator/FiloDbClusterDiscoverySpec.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
coordinator/src/test/scala/filodb.coordinator/ShardMapperSpec.scala

**Current behavior :** minimalEvents for state `ShardStatusError` incorrectly marks shards as `ShardStatusActive`. 
**New behavior :** minimalEvents is marking the shards correctly as `ShardStatusActive` using `IngestionError` shardEvent.
Shard Status Response will look as following:
```
{
"status": "success",
"data": [
{
"shard": 0,
"status": "ShardStatusActive",
"address": "akka://filo-standalone"
},
{
"shard": 1,
"status": "ShardStatusActive",
"address": "akka://filo-standalone"
},
{
"shard": 2,
"status": "ShardStatusError(test exception)",
"address": ""
},
{
"shard": 3,
"status": "ShardStatusRecovery(0)",
"address": "akka.tcp://filo-standalone@127.0.0.1:3552"
}
]
}
```

fix(cluster): Fixing minimal events for state `ShardStatusError`

---

coordinator/src/main/scala/filodb.coordinator/IngestionActor.scala
coordinator/src/main/scala/filodb.coordinator/IngestionStream.scala
coordinator/src/main/scala/filodb.coordinator/sources/CsvStream.scala
coordinator/src/test/scala/filodb.coordinator/IngestionStreamSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/GlobalConfig.scala
kafka/src/main/scala/filodb/kafka/KafkaIngestionStream.scala

1. `doRecovery` during shard startup only recovers to the max of "previously flushed group checkpoints for the shard". 
2. In case the shard is down for multiple minutes or hours and ingestion is actively happening, the shard doesn't recovers to latest ingestion stream offset and becomes active for query much sooner.  This will result in incorrect queries.
1.  Adding a new config driven functionality, where the shard recovery process can fetch the end offset of the ingestion stream and recover to that offset. 
2. This can be done multiple times in recursive fashion to reach to the latest ingested offset before marking shard as ready for query.

fix(ingestion): shard recovery should fetch the end of IngestionStream to recover the index

---

conf/timeseries-dev-source.conf
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/downsample/ChunkDownsampler.scala
core/src/main/scala/filodb.core/memstore/TimeSeriesStore.scala
core/src/main/scala/filodb.core/metadata/Schemas.scala
gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/gateway/conversion/InputRecord.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesProducer.scala
gateway/src/test/scala/filodb/gateway/conversion/InputRecordBuilderSpec.scala
jmh/src/main/scala/filodb.jmh/Base2ExponentialHistogramQueryBenchmark.scala
jmh/src/main/scala/filodb.jmh/HistVectorBenchmark.scala
memory/src/main/scala/filodb.memory/format/MemoryReader.scala
memory/src/main/scala/filodb.memory/format/NibblePack.scala
memory/src/main/scala/filodb.memory/format/Section.scala
memory/src/main/scala/filodb.memory/format/WireFormat.scala
memory/src/main/scala/filodb.memory/format/vectors/ExpHistogramVector.scala
memory/src/main/scala/filodb.memory/format/vectors/Histogram.scala
memory/src/main/scala/filodb.memory/format/vectors/HistogramVector.scala
memory/src/test/scala/filodb.memory/format/NibblePackTest.scala
memory/src/test/scala/filodb.memory/format/vectors/ExpHistogramVectorTest.scala
memory/src/test/scala/filodb.memory/format/vectors/HistogramTest.scala
run_benchmarks.sh
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

From tests, we are finding that OTel Exponential histogram scale, bucketOffset and bucketCount can be volatile from sample to sample from same source. Frequently changing bucket scheme results in new chunk being created, and this can bleed at high scale.
This PR creates a new vector ExpHistogramVector which stores the bucket definition along with each sample in the vector. During reads, we reuse the values array that stores bucket counts to avoid object allocation.
E2E local test works.
Optimizations done after benchmark. There was a performance hits were because of `Math.pow` due to reset of bucket scheme for each same. They have been optimized with pre computation and usage of `Math.exp`.
```
[info] Benchmark                                Mode  Cnt …
```

feat(core): Exponential histogram vector to address volatility in exp bucketing scheme

---

core/src/rust/Cargo.lock
core/src/rust/filodb_core/Cargo.toml
core/src/rust/filodb_core/src/ingestion.rs
core/src/rust/filodb_core/src/ingestion/fields.rs
core/src/rust/filodb_core/src/query_parser.rs
core/src/rust/filodb_core/src/query_parser/filodb_query.rs
core/src/rust/tantivy_utils/Cargo.toml
core/src/rust/tantivy_utils/src/collectors/column_cache.rs
core/src/rust/tantivy_utils/src/collectors/part_key_collector.rs
core/src/rust/tantivy_utils/src/collectors/part_key_record_collector.rs
core/src/rust/tantivy_utils/src/query/cache.rs

No change in behavior expected, tantity upgraded
NA
Following are the results for the JMH tests
Lucene 
```
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                                         Mode  Cnt        Score       Error  Units
[info] PartKeyLuceneIndexBenchmark.emptyPartIdsLookupWithEqualsFilters  thrpt    5    59244.289 ±  3745.757  ops/s
[info] PartKeyLuceneIndexBenchmark.getLabelNames                        thrpt    5      496.276 ±    10.932  ops/s
[info] PartKeyLuceneIndexBenchmark.getMetricNames                       thrpt    5      417.537 ±     5.399  ops/s
[info] PartKeyLuceneIndexBenchmark.getMetricNamesSearchAndIterate       thrpt    5 …
```

maint(index) Upgrade tantivy 0.22 -> 0.24

---

core/src/main/scala/filodb.core/Utils.scala
core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala

**Current behavior :** Not supporting compatibility of preagg legacy and otel histogram schemas on query path.
**New behavior :** Added support for compatibility of preagg legacy and otel histogram schemas on query path.

fix(query): Back compatibility of legacy and otel histograms for preagg schemas

---

core/src/main/scala/filodb.core/Utils.scala
core/src/test/scala/filodb.core/store/ReadablePartitionSpec.scala
version.sbt

Adding support for back compatibility of legacy and otel histograms for preagg.

cherry-pick(bugfix): Back compatibility of legacy and otel histograms for preagg schemas

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

NaN is not comparable. Check if the value is NaN before comparison.

(query) fix negative rate value by leading NaN.

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/SingleClusterPlanner.scala
core/src/main/resources/filodb-defaults.conf
core/src/test/scala/filodb.core/memstore/TimeSeriesMemStoreSpec.scala

We are hitting SchemaMismatch error from DownsampleShard. The correct fix for this would be to eagerly filter using the _type_ field from the index rather than manually filtering it later now that we always enable this indexing.

bug(core): Now that type field indexing is on, use it in queries (#2019)

---

spark-jobs/src/main/scala/filodb/labelchurnfinder/LabelChurnFinder.scala
spark-jobs/src/main/scala/filodb/labelchurnfinder/LcfTask.scala
spark-jobs/src/test/scala/filodb/labelchurnfinder/LabelChurnFinderSpec.scala

Instead of taking total time series, we can customize the cut off time during which churn will be calculated.
Time series not ingesting during the time will not be involved in calculation of churn.

feat(spark-jobs): Label churn finder job can customize startTime for calculating churn

---

memory/src/main/scala/filodb.memory/format/vectors/DoubleVector.scala
memory/src/test/scala/filodb.memory/format/vectors/DoubleVectorTest.scala
query/src/test/scala/filodb/query/exec/rangefn/RateFunctionsSpec.scala

* (query) fix negative rate value by leading NaN.
NaN is not comparable. Check if the value is NaN before comparison.
---------
**Other …

(query) fix negative rate value by leading NaN. (#2009)

---

coordinator/src/main/scala/filodb.coordinator/queryplanner/MultiPartitionPlanner.scala
coordinator/src/test/scala/filodb.coordinator/queryplanner/MultiPartitionPlannerSpec.scala
core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/query/QueryConfig.scala
core/src/test/resources/application_test.conf
query/src/main/scala/filodb/query/LogicalPlan.scala
query/src/test/scala/filodb/query/LogicalPlanSpec.scala

Enabling and disabling stick is a global config with no way to disable at tenant level if the global config is enabled. 
Add capabilities to disable the feature per tenant

fix(query) Add support to disable remote stitch by tenants

---

cassandra/src/main/scala/filodb.cassandra/columnstore/BaseDatasetTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/CassandraColumnStore.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/IngestionTimeIndexTable.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/PartitionKeysV2Table.scala
cassandra/src/main/scala/filodb.cassandra/columnstore/TimeSeriesChunksTable.scala
core/src/main/resources/filodb-defaults.conf
spark-jobs/src/main/scala/filodb/downsampler/chunk/BatchDownsampler.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerMain.scala
spark-jobs/src/main/scala/filodb/downsampler/chunk/DownsamplerSettings.scala
spark-jobs/src/test/scala/filodb/downsampler/DownsamplerMainSpec.scala

BatchDownsampler currently performs two functions: (1) downsampling the data (2) persisting the data
ChunkPersitor trait is added allowing to use ChunkPersistor to save the downsampled data. DSPartitionReader is added allowing to read the data that needs to be downsampled.

feat(downsample): Allowing to persist downsampled data using arbitrary implementation of ChunkPersistor and DSPartitionReader

---

core/src/main/resources/filodb-defaults.conf
core/src/main/scala/filodb.core/metadata/Schemas.scala

New preagg-gauge schema with additional columns to support gauge last-over-time aggregations. This is to match promql aggregation query behavior.
- countl = `count(last-over-time(http_requests{job="web-server"}[2m]))`
- minl = `min(last-over-time(http_requests{job="web-server"}[2m]))`
- suml = `sum(last-over-time(http_requests{job="web-server"}[2m]))`
- maxl = `max(last-over-time(http_requests{job="web-server"}[2m]))`

support for last-over-time gauge aggregations to match promql

---

coordinator/src/test/scala/filodb.coordinator/queryplanner/AggLpOptimizationSpec.scala
query/src/main/scala/filodb/query/lpopt/AggLpOptimization.scala

Choose aggregation rule only if it is active for the entire duration of query

bug(query): Pick agg rule only if it is valid for entire query duration

---

dev-gateway.sh
gateway/src/main/scala/filodb/timeseries/TestTimeseriesPrometheusConsumer.scala
project/Dependencies.scala
project/FiloBuild.scala

Currently gateway produces data to Kafka
Added new Kafka consumer TestTimeseriesPrometheusConsumer to ingest data to Prometheus by using pushgateway
**Limitations :**
Supports only counter/gauge metric types

Added Kafka consumer to ingest data to Prometheus

---

gateway/src/main/scala/filodb/gateway/GatewayServer.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesConsumer.scala
gateway/src/main/scala/filodb/timeseries/TestTimeseriesPrometheusConsumer.scala

This PR fixes the way the timeseries-dev-source.conf is parsed to resolve the new substitutions introduced by the following PR https://github.com/filodb/FiloDB/pull/2053

fix(gateway) fix the parsing of timeseries-dev-source.conf to address the new substitutions
